//! Generates `include/tulip_rs_ffi_counts.h` and
//! `examples/tulip_rs_ffi_counts.h` -- one `#define <NAME>_INPUTS N` /
//! `#define <NAME>_OPTIONS N` pair per indicator, read directly from the
//! real `tulip_rs::indicators::<name>::{INPUTS, OPTIONS}` constants at
//! *build time* (this crate depends on `tulip_rs` as a build-dependency
//! purely for this).
//!
//! This is deliberately not done via `cbindgen`: cbindgen only *parses*
//! Rust source, it never evaluates it, so a `pub const ADOSC_INPUTS: usize
//! = tulip_rs::indicators::adosc::INPUTS;` in `src/adosc.rs` would come out
//! as the broken macro `#define ADOSC_INPUTS INPUTS` (verified against
//! cbindgen 0.29.4). Compiling this build script, by contrast, actually
//! runs the real Rust code, so the numbers it writes out can never drift
//! from the core crate -- there's nothing to keep in sync by hand.
//!
//! The two output locations mirror the crate's two existing headers:
//! `include/tulip_rs_ffi.h` (cbindgen's output, for external consumers) and
//! `examples/tulip_rs_ffi.h` (the hand-written header the bundled examples
//! build against, with no `-I` flag). Both `#include
//! "tulip_rs_ffi_counts.h"` from their own directory.
//!
//! The only thing maintained by hand here is the list of indicator names
//! below -- and that's not new upkeep: adding an indicator already requires
//! adding `pub mod <name>;` to `src/lib.rs` and writing `src/<name>.rs`, so
//! adding one more line to this list is the same class of edit, not an
//! extra source of truth for the *values*.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

macro_rules! counts_header {
    ($($prefix:literal => ($inputs:expr, $options:expr)),+ $(,)?) => {{
        let mut out = String::new();
        out.push_str(
            "// Auto-generated by tulip_rs_ffi/build.rs from the corresponding\n",
        );
        out.push_str(
            "// tulip_rs::indicators::<name>::{INPUTS, OPTIONS} constants.\n",
        );
        out.push_str(
            "// Do not edit by hand -- edit the core crate instead and rebuild.\n\n",
        );
        out.push_str("#ifndef TULIP_RS_FFI_COUNTS_H\n#define TULIP_RS_FFI_COUNTS_H\n\n");
        $(
            writeln!(
                out,
                "#define {p}_INPUTS {i}\n#define {p}_OPTIONS {o}\n",
                p = $prefix,
                i = $inputs,
                o = $options,
            )
            .unwrap();
        )+
        out.push_str("#endif // TULIP_RS_FFI_COUNTS_H\n");
        out
    }};
}

fn main() {
    let out = counts_header! {
        "AD" => (tulip_rs::indicators::ad::INPUTS, tulip_rs::indicators::ad::OPTIONS),
        "ADAPTIVEMSW" => (tulip_rs::indicators::adaptivemsw::INPUTS, tulip_rs::indicators::adaptivemsw::OPTIONS),
        "ADOSC" => (tulip_rs::indicators::adosc::INPUTS, tulip_rs::indicators::adosc::OPTIONS),
        "ADX" => (tulip_rs::indicators::adx::INPUTS, tulip_rs::indicators::adx::OPTIONS),
        "ADXR" => (tulip_rs::indicators::adxr::INPUTS, tulip_rs::indicators::adxr::OPTIONS),
        "AO" => (tulip_rs::indicators::ao::INPUTS, tulip_rs::indicators::ao::OPTIONS),
        "APO" => (tulip_rs::indicators::apo::INPUTS, tulip_rs::indicators::apo::OPTIONS),
        "AROON" => (tulip_rs::indicators::aroon::INPUTS, tulip_rs::indicators::aroon::OPTIONS),
        "AROONOSC" => (tulip_rs::indicators::aroonosc::INPUTS, tulip_rs::indicators::aroonosc::OPTIONS),
        "ATR" => (tulip_rs::indicators::atr::INPUTS, tulip_rs::indicators::atr::OPTIONS),
        "AVGPRICE" => (tulip_rs::indicators::avgprice::INPUTS, tulip_rs::indicators::avgprice::OPTIONS),
        "BBANDS" => (tulip_rs::indicators::bbands::INPUTS, tulip_rs::indicators::bbands::OPTIONS),
        "BOP" => (tulip_rs::indicators::bop::INPUTS, tulip_rs::indicators::bop::OPTIONS),
        "CANDLESTICK" => (tulip_rs::indicators::candlestick::INPUTS, tulip_rs::indicators::candlestick::OPTIONS),
        "CCFISHER" => (tulip_rs::indicators::ccfisher::INPUTS, tulip_rs::indicators::ccfisher::OPTIONS),
        "CCI" => (tulip_rs::indicators::cci::INPUTS, tulip_rs::indicators::cci::OPTIONS),
        "CHAIKINMF" => (tulip_rs::indicators::chaikinmf::INPUTS, tulip_rs::indicators::chaikinmf::OPTIONS),
        "CHANDELIEREXIT" => (tulip_rs::indicators::chandelierexit::INPUTS, tulip_rs::indicators::chandelierexit::OPTIONS),
        "CMO" => (tulip_rs::indicators::cmo::INPUTS, tulip_rs::indicators::cmo::OPTIONS),
        "CVI" => (tulip_rs::indicators::cvi::INPUTS, tulip_rs::indicators::cvi::OPTIONS),
        "CYBERCYCLE" => (tulip_rs::indicators::cybercycle::INPUTS, tulip_rs::indicators::cybercycle::OPTIONS),
        "DEMA" => (tulip_rs::indicators::dema::INPUTS, tulip_rs::indicators::dema::OPTIONS),
        "DI" => (tulip_rs::indicators::di::INPUTS, tulip_rs::indicators::di::OPTIONS),
        "DM" => (tulip_rs::indicators::dm::INPUTS, tulip_rs::indicators::dm::OPTIONS),
        "DONCHIANCHANNEL" => (tulip_rs::indicators::donchianchannel::INPUTS, tulip_rs::indicators::donchianchannel::OPTIONS),
        "DPO" => (tulip_rs::indicators::dpo::INPUTS, tulip_rs::indicators::dpo::OPTIONS),
        "DX" => (tulip_rs::indicators::dx::INPUTS, tulip_rs::indicators::dx::OPTIONS),
        "EF" => (tulip_rs::indicators::ef::INPUTS, tulip_rs::indicators::ef::OPTIONS),
        "ELDERRAY" => (tulip_rs::indicators::elderray::INPUTS, tulip_rs::indicators::elderray::OPTIONS),
        "EMA" => (tulip_rs::indicators::ema::INPUTS, tulip_rs::indicators::ema::OPTIONS),
        "EMV" => (tulip_rs::indicators::emv::INPUTS, tulip_rs::indicators::emv::OPTIONS),
        "FISHER" => (tulip_rs::indicators::fisher::INPUTS, tulip_rs::indicators::fisher::OPTIONS),
        "FOSC" => (tulip_rs::indicators::fosc::INPUTS, tulip_rs::indicators::fosc::OPTIONS),
        "HIGHPASS" => (tulip_rs::indicators::highpass::INPUTS, tulip_rs::indicators::highpass::OPTIONS),
        "HILBERTTRANSFORM" => (tulip_rs::indicators::hilberttransform::INPUTS, tulip_rs::indicators::hilberttransform::OPTIONS),
        "HMA" => (tulip_rs::indicators::hma::INPUTS, tulip_rs::indicators::hma::OPTIONS),
        "HOMODYNEDISCRIMINATOR" => (tulip_rs::indicators::homodynediscriminator::INPUTS, tulip_rs::indicators::homodynediscriminator::OPTIONS),
        "ICHIMOKU" => (tulip_rs::indicators::ichimoku::INPUTS, tulip_rs::indicators::ichimoku::OPTIONS),
        "INSTANTANEOUSTRENDLINE" => (tulip_rs::indicators::instantaneoustrendline::INPUTS, tulip_rs::indicators::instantaneoustrendline::OPTIONS),
        "KAMA" => (tulip_rs::indicators::kama::INPUTS, tulip_rs::indicators::kama::OPTIONS),
        "KELTNERCHANNEL" => (tulip_rs::indicators::keltnerchannel::INPUTS, tulip_rs::indicators::keltnerchannel::OPTIONS),
        "KVO" => (tulip_rs::indicators::kvo::INPUTS, tulip_rs::indicators::kvo::OPTIONS),
        "LINREG" => (tulip_rs::indicators::linreg::INPUTS, tulip_rs::indicators::linreg::OPTIONS),
        "MACD" => (tulip_rs::indicators::macd::INPUTS, tulip_rs::indicators::macd::OPTIONS),
        "MAMA" => (tulip_rs::indicators::mama::INPUTS, tulip_rs::indicators::mama::OPTIONS),
        "MARKETFI" => (tulip_rs::indicators::marketfi::INPUTS, tulip_rs::indicators::marketfi::OPTIONS),
        "MASS" => (tulip_rs::indicators::mass::INPUTS, tulip_rs::indicators::mass::OPTIONS),
        "MAX" => (tulip_rs::indicators::max::INPUTS, tulip_rs::indicators::max::OPTIONS),
        "MD" => (tulip_rs::indicators::md::INPUTS, tulip_rs::indicators::md::OPTIONS),
        "MEDPRICE" => (tulip_rs::indicators::medprice::INPUTS, tulip_rs::indicators::medprice::OPTIONS),
        "MFI" => (tulip_rs::indicators::mfi::INPUTS, tulip_rs::indicators::mfi::OPTIONS),
        "MIN" => (tulip_rs::indicators::min::INPUTS, tulip_rs::indicators::min::OPTIONS),
        "MOM" => (tulip_rs::indicators::mom::INPUTS, tulip_rs::indicators::mom::OPTIONS),
        "MSW" => (tulip_rs::indicators::msw::INPUTS, tulip_rs::indicators::msw::OPTIONS),
        "NATR" => (tulip_rs::indicators::natr::INPUTS, tulip_rs::indicators::natr::OPTIONS),
        "NVI" => (tulip_rs::indicators::nvi::INPUTS, tulip_rs::indicators::nvi::OPTIONS),
        "OBV" => (tulip_rs::indicators::obv::INPUTS, tulip_rs::indicators::obv::OPTIONS),
        "PIVOTPOINT" => (tulip_rs::indicators::pivotpoint::INPUTS, tulip_rs::indicators::pivotpoint::OPTIONS),
        "PPO" => (tulip_rs::indicators::ppo::INPUTS, tulip_rs::indicators::ppo::OPTIONS),
        "PSAR" => (tulip_rs::indicators::psar::INPUTS, tulip_rs::indicators::psar::OPTIONS),
        "PVI" => (tulip_rs::indicators::pvi::INPUTS, tulip_rs::indicators::pvi::OPTIONS),
        "QSTICK" => (tulip_rs::indicators::qstick::INPUTS, tulip_rs::indicators::qstick::OPTIONS),
        "ROC" => (tulip_rs::indicators::roc::INPUTS, tulip_rs::indicators::roc::OPTIONS),
        "ROCR" => (tulip_rs::indicators::rocr::INPUTS, tulip_rs::indicators::rocr::OPTIONS),
        "ROOFINGFILTER" => (tulip_rs::indicators::roofingfilter::INPUTS, tulip_rs::indicators::roofingfilter::OPTIONS),
        "RSI" => (tulip_rs::indicators::rsi::INPUTS, tulip_rs::indicators::rsi::OPTIONS),
        "SMA" => (tulip_rs::indicators::sma::INPUTS, tulip_rs::indicators::sma::OPTIONS),
        "SMAENVELOPE" => (tulip_rs::indicators::smaenvelope::INPUTS, tulip_rs::indicators::smaenvelope::OPTIONS),
        "STDDEV" => (tulip_rs::indicators::stddev::INPUTS, tulip_rs::indicators::stddev::OPTIONS),
        "STOCH" => (tulip_rs::indicators::stoch::INPUTS, tulip_rs::indicators::stoch::OPTIONS),
        "STOCHRSI" => (tulip_rs::indicators::stochrsi::INPUTS, tulip_rs::indicators::stochrsi::OPTIONS),
        "SUPERSMOOTHER" => (tulip_rs::indicators::supersmoother::INPUTS, tulip_rs::indicators::supersmoother::OPTIONS),
        "SUPERTREND" => (tulip_rs::indicators::supertrend::INPUTS, tulip_rs::indicators::supertrend::OPTIONS),
        "TEMA" => (tulip_rs::indicators::tema::INPUTS, tulip_rs::indicators::tema::OPTIONS),
        "TR" => (tulip_rs::indicators::tr::INPUTS, tulip_rs::indicators::tr::OPTIONS),
        "TRENDMODE" => (tulip_rs::indicators::trendmode::INPUTS, tulip_rs::indicators::trendmode::OPTIONS),
        "TRIMA" => (tulip_rs::indicators::trima::INPUTS, tulip_rs::indicators::trima::OPTIONS),
        "TRIX" => (tulip_rs::indicators::trix::INPUTS, tulip_rs::indicators::trix::OPTIONS),
        "TRVI" => (tulip_rs::indicators::trvi::INPUTS, tulip_rs::indicators::trvi::OPTIONS),
        "TSF" => (tulip_rs::indicators::tsf::INPUTS, tulip_rs::indicators::tsf::OPTIONS),
        "TYPPRICE" => (tulip_rs::indicators::typprice::INPUTS, tulip_rs::indicators::typprice::OPTIONS),
        "ULTOSC" => (tulip_rs::indicators::ultosc::INPUTS, tulip_rs::indicators::ultosc::OPTIONS),
        "VHF" => (tulip_rs::indicators::vhf::INPUTS, tulip_rs::indicators::vhf::OPTIONS),
        "VIDYA" => (tulip_rs::indicators::vidya::INPUTS, tulip_rs::indicators::vidya::OPTIONS),
        "VOLATILITY" => (tulip_rs::indicators::volatility::INPUTS, tulip_rs::indicators::volatility::OPTIONS),
        "VORTEX" => (tulip_rs::indicators::vortex::INPUTS, tulip_rs::indicators::vortex::OPTIONS),
        "VOSC" => (tulip_rs::indicators::vosc::INPUTS, tulip_rs::indicators::vosc::OPTIONS),
        "VWAP" => (tulip_rs::indicators::vwap::INPUTS, tulip_rs::indicators::vwap::OPTIONS),
        "VWMA" => (tulip_rs::indicators::vwma::INPUTS, tulip_rs::indicators::vwma::OPTIONS),
        "WAD" => (tulip_rs::indicators::wad::INPUTS, tulip_rs::indicators::wad::OPTIONS),
        "WCPRICE" => (tulip_rs::indicators::wcprice::INPUTS, tulip_rs::indicators::wcprice::OPTIONS),
        "WILDERS" => (tulip_rs::indicators::wilders::INPUTS, tulip_rs::indicators::wilders::OPTIONS),
        "WILLR" => (tulip_rs::indicators::willr::INPUTS, tulip_rs::indicators::willr::OPTIONS),
        "WMA" => (tulip_rs::indicators::wma::INPUTS, tulip_rs::indicators::wma::OPTIONS),
        "ZLEMA" => (tulip_rs::indicators::zlema::INPUTS, tulip_rs::indicators::zlema::OPTIONS),
    };

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    for rel_dir in ["include", "examples"] {
        let dest = Path::new(&manifest_dir)
            .join(rel_dir)
            .join("tulip_rs_ffi_counts.h");
        fs::write(&dest, &out)
            .unwrap_or_else(|e| panic!("failed to write {}: {}", dest.display(), e));
    }

    println!("cargo:rerun-if-changed=../tulip_rs/tulip_rs/src");
    println!("cargo:rerun-if-changed=build.rs");
}
