// ADAPTIVEMSW (Adaptive Mesa Sine Wave) example for tulip_rs_ffi.
// Mirrors tulip_rs_python/examples/ti_adaptivemsw_example.py: same sample data,
// same options, same "compute partial, continue via batch, verify against a
// full recompute" flow, plus SIMD by-assets/by-options demonstrations.
//
// ADAPTIVEMSW_INPUTS/ADAPTIVEMSW_OPTIONS come from ../include/tulip_rs_ffi_counts.h,
// generated by ../build.rs from the real tulip_rs::indicators::adaptivemsw::
// {INPUTS, OPTIONS} constants (run `cargo build` at least once so that file
// exists/is current). The main header is the cbindgen-generated one in
// ../include/, which is the up-to-date API surface.
//
// Build (from the tulip_rs_ffi directory):
//   cc -O2 -o adaptivemsw_example examples/adaptivemsw_example.c \
//       -L target/release -ltulip_rs_ffi -Wl,-rpath,target/release
// Run:
//   ./adaptivemsw_example

#include <stdio.h>
#include <stdlib.h>

#include "../include/tulip_rs_ffi.h"

static const double close[] = {81.59, 81.06, 82.87, 83.00, 83.61, 83.15, 82.84, 83.99, 84.55, 84.36, 85.53, 86.54, 86.89, 87.77, 87.29, 87.50, 88.10, 88.50, 87.90, 88.20, 88.80, 89.10, 88.70, 89.30, 89.70, 90.10, 89.50, 90.20, 90.80, 91.10, 90.50, 91.20, 91.80, 92.10, 91.50, 92.20, 92.80, 93.10, 92.50, 93.20};

#define TOTAL 40
#define PARTIAL (TOTAL - 5)
#define REST (TOTAL - PARTIAL)

static void print_row(const char *label, const double *row, size_t len) {
    printf("  %-16s: [", label);
    for (size_t i = 0; i < len; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < len) printf(", ");
    }
    printf("]\n");
}

static void print_row_head(const char *label, const double *row, size_t len, size_t max_print) {
    printf("  %-16s: [", label);
    size_t n = len < max_print ? len : max_print;
    for (size_t i = 0; i < n; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < n) printf(", ");
    }
    printf(len > max_print ? ", ...]\n" : "]\n");
}

static int allclose(const double *a, const double *b, size_t len) {
    for (size_t i = 0; i < len; i++) {
        double diff = a[i] - b[i];
        if (diff < 0) diff = -diff;
        if (diff > 1e-9) return 0;
    }
    return 1;
}

int main(void) {
    const double options[ADAPTIVEMSW_OPTIONS] = {}; // no options
    double full_sine[TOTAL];
    size_t full_sine_len = 0;

    CIndicatorInfo info = adaptivemsw_info();
    printf("=== %s (%s) ===\n", info.name, info.full_name);
    printf("Inputs: %u, Options: %u (none), Optional outputs: %u\n",
           (unsigned)ADAPTIVEMSW_INPUTS, (unsigned)ADAPTIVEMSW_OPTIONS,
           (unsigned)info.optional_outputs.len);
    printf("Minimum data required: %zu\n", adaptivemsw_min_data(options));

    printf("\n=== ADAPTIVEMSW: full calculation (all optional outputs) ===\n");
    {
        const double *inputs[ADAPTIVEMSW_INPUTS] = {close};
        bool optional_outputs[1] = {true}; // dc_period

        CIndicatorResult r = adaptivemsw_indicator(inputs, TOTAL, options, optional_outputs, 1);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "adaptivemsw_indicator failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_outputs=%zu\n", r.num_outputs);
        print_row("sine", r.outputs[0], r.output_lens[0]);
        print_row("lead_sine", r.outputs[1], r.output_lens[1]);
        print_row("dc_period", r.outputs[2], r.output_lens[2]);

        // Keep a copy of the mandatory "sine" row for later verification.
        full_sine_len = r.output_lens[0];
        for (size_t i = 0; i < full_sine_len; i++) full_sine[i] = r.outputs[0][i];

        void *unused_state = r.state;
        tulip_ffi_result_free(r);
        adaptivemsw_state_free(unused_state);
    }

    printf("\n=== ADAPTIVEMSW: partial calculation + batch continuation ===\n");
    {
        const double *partial_inputs[ADAPTIVEMSW_INPUTS] = {close};
        CIndicatorResult pr = adaptivemsw_indicator(partial_inputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "adaptivemsw_indicator (partial) failed: error=%d\n", pr.error);
            return 1;
        }
        print_row("sine (partial)", pr.outputs[0], pr.output_lens[0]);
        print_row("lead_sine (partial)", pr.outputs[1], pr.output_lens[1]);
        void *state = pr.state;
        tulip_ffi_result_free(pr); // outputs freed; state kept alive

        const double *rest_inputs[ADAPTIVEMSW_INPUTS] = {close + PARTIAL};
        CBatchResult br = adaptivemsw_batch(state, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "adaptivemsw_batch failed: error=%d\n", br.error);
            return 1;
        }
        print_row("sine (continued)", br.outputs[0], br.output_lens[0]);
        print_row("lead_sine (continued)", br.outputs[1], br.output_lens[1]);

        printf("\n=== Verification: partial+continued vs. full recompute ===\n");
        int ok = 1;
        size_t continued_len = br.output_lens[0];
        size_t tail_start = full_sine_len - continued_len;
        for (size_t i = 0; i < continued_len; i++) {
            double a = full_sine[tail_start + i];
            double b = br.outputs[0][i];
            double diff = a > b ? a - b : b - a;
            if (diff > 1e-9) {
                ok = 0;
                printf("  mismatch at %zu: full=%.6f continued=%.6f\n", i, a, b);
            }
        }
        printf(ok ? "  MATCH: partial+continued sine equals full recompute\n"
                  : "  MISMATCH detected!\n");

        tulip_ffi_batch_result_free(br);
        adaptivemsw_state_free(state);
    }

    printf("\n=== ADAPTIVEMSW: SIMD by assets (N=4) ===\n");
    {
        // Asset 1: original data.
        const double *const asset1[ADAPTIVEMSW_INPUTS] = {close};

        // Asset 2: scaled up (+20%).
        double close_2[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) close_2[i] = close[i] * 1.2;
        const double *const asset2[ADAPTIVEMSW_INPUTS] = {close_2};

        // Asset 3: different upward trend.
        double close_3[TOTAL];
        for (size_t i = 0; i < TOTAL; i++)
            close_3[i] = 90.0 + (double)i * 0.5 + close[i] * 0.1;
        const double *const asset3[ADAPTIVEMSW_INPUTS] = {close_3};

        // Asset 4: downward trend.
        double close_4[TOTAL];
        for (size_t i = 0; i < TOTAL; i++)
            close_4[i] = 100.0 - (double)i * 0.3 + close[i] * 0.05;
        const double *const asset4[ADAPTIVEMSW_INPUTS] = {close_4};

        // simd_inputs is indexed by asset (the N=4 SIMD lanes), NOT by input
        // series -- hence [4] here stays a lane count.
        const double *const *const simd_inputs[4] = {asset1, asset2, asset3, asset4};
        bool optional_outputs[1] = {true};

        CSimdResult r = adaptivemsw_simd_by_assets(simd_inputs, 4, TOTAL, options, optional_outputs, 1);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "adaptivemsw_simd_by_assets failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            printf("Asset %zu ", i + 1);
            print_row("sine", r.outputs[i][0], r.output_lens[i][0]);
        }

        printf("\nVerification - calculating each asset individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = adaptivemsw_indicator(
                simd_inputs[i], TOTAL, options, optional_outputs, 1);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "adaptivemsw_indicator (asset %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            printf("  Asset %zu: %s\n", i + 1, match ? "MATCH" : "MISMATCH");
            if (!match) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            adaptivemsw_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) adaptivemsw_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-assets equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    // Note: ADAPTIVEMSW has 0 options, so no simd_by_options function exists
    printf("\n=== ADAPTIVEMSW: SIMD by options (N=4) ===\n");
    printf("  SKIPPED - ADAPTIVEMSW has 0 options and does not provide simd_by_options.\n");

    return 0;
}
