// ADOSC (Accumulation/Distribution Oscillator) example for tulip_rs_ffi.
// Mirrors tulip_rs_python/examples/ti_adosc_example.py: same sample data,
// same options, same "compute partial, continue via batch, verify against a
// full recompute" flow, plus SIMD by-assets/by-options demonstrations.
//
// ADOSC_INPUTS/ADOSC_OPTIONS come from tulip_rs_ffi_counts.h, generated by
// ../build.rs from the real tulip_rs::indicators::adosc::{INPUTS, OPTIONS}
// constants (run `cargo build` at least once so that file exists/is current).
//
// Build:
//   cc -O2 -o adosc_example examples/adosc_example.c -Iinclude \
//       -L target/release -ltulip_rs_ffi -Wl,-rpath,target/release
// Run:
//   ./adosc_example

#include <stdio.h>
#include <stdlib.h>

#include "../include/tulip_rs_ffi.h"

static const double high[]   = {82.15, 81.89, 83.03, 83.30, 83.85, 83.90, 83.33, 84.30, 84.84, 85.00, 85.90, 86.58, 87.87, 88.15, 87.60};
static const double low[]    = {81.29, 80.64, 82.65, 82.70, 83.07, 82.65, 82.20, 83.35, 84.15, 84.11, 85.39, 86.04, 86.58, 87.32, 87.00};
static const double close[]  = {81.59, 81.06, 82.87, 83.00, 83.61, 83.15, 82.84, 83.99, 84.55, 84.36, 85.53, 86.54, 86.89, 87.77, 87.29};
static const double volume[] = {1000000, 1100000, 900000, 1200000, 800000, 950000, 1050000, 1150000, 1300000, 1000000, 1100000, 1250000, 980000, 1180000, 1080000};

#define TOTAL 15
#define PARTIAL 10
#define REST (TOTAL - PARTIAL)

static void print_row(const char *label, const double *row, size_t len) {
    printf("  %-12s: [", label);
    for (size_t i = 0; i < len; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < len) printf(", ");
    }
    printf("]\n");
}

static void print_row_head(const char *label, const double *row, size_t len, size_t max_print) {
    printf("  %-14s: [", label);
    size_t n = len < max_print ? len : max_print;
    for (size_t i = 0; i < n; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < n) printf(", ");
    }
    printf(len > max_print ? ", ...]\n" : "]\n");
}

static int allclose(const double *a, const double *b, size_t len) {
    for (size_t i = 0; i < len; i++) {
        double diff = a[i] - b[i];
        if (diff < 0) diff = -diff;
        if (diff > 1e-9) return 0;
    }
    return 1;
}

int main(void) {
    const double options[ADOSC_OPTIONS] = {3.0, 10.0}; // short_period, long_period
    double full_adosc[TOTAL];
    size_t full_adosc_len = 0;

    printf("ADOSC takes %d input series (high, low, close, volume) and %d options"
           " (short_period, long_period)\n",
           ADOSC_INPUTS, ADOSC_OPTIONS);

    printf("\n=== ADOSC: full calculation (all optional outputs) ===\n");
    {
        const double *inputs[ADOSC_INPUTS] = {high, low, close, volume};
        bool optional_outputs[3] = {true, true, true}; // short_ema, long_ema, ad

        CIndicatorResult r = adosc_indicator(inputs, TOTAL, options, optional_outputs, 3);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "adosc_indicator failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_outputs=%zu\n", r.num_outputs);
        print_row("adosc", r.outputs[0], r.output_lens[0]);
        print_row("short_ema", r.outputs[1], r.output_lens[1]);
        print_row("long_ema", r.outputs[2], r.output_lens[2]);
        print_row("ad", r.outputs[3], r.output_lens[3]);

        // Keep a copy of the mandatory "adosc" row for later verification.
        full_adosc_len = r.output_lens[0];
        for (size_t i = 0; i < full_adosc_len; i++) full_adosc[i] = r.outputs[0][i];

        void *unused_state = r.state;
        tulip_ffi_result_free(r);
        adosc_state_free(unused_state);
    }

    printf("\n=== ADOSC: partial calculation + batch continuation ===\n");
    {
        const double *partial_inputs[ADOSC_INPUTS] = {high, low, close, volume};
        CIndicatorResult pr = adosc_indicator(partial_inputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "adosc_indicator (partial) failed: error=%d\n", pr.error);
            return 1;
        }
        print_row("adosc (partial)", pr.outputs[0], pr.output_lens[0]);
        void *state = pr.state;
        tulip_ffi_result_free(pr); // outputs freed; state kept alive

        const double *rest_inputs[ADOSC_INPUTS] = {
            high + PARTIAL, low + PARTIAL, close + PARTIAL, volume + PARTIAL};
        CBatchResult br = adosc_batch(state, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "adosc_batch failed: error=%d\n", br.error);
            return 1;
        }
        print_row("adosc (continued)", br.outputs[0], br.output_lens[0]);

        printf("\n=== Verification: partial+continued vs. full recompute ===\n");
        int ok = 1;
        size_t continued_len = br.output_lens[0];
        size_t tail_start = full_adosc_len - continued_len;
        for (size_t i = 0; i < continued_len; i++) {
            double a = full_adosc[tail_start + i];
            double b = br.outputs[0][i];
            double diff = a > b ? a - b : b - a;
            if (diff > 1e-9) {
                ok = 0;
                printf("  mismatch at %zu: full=%.6f continued=%.6f\n", i, a, b);
            }
        }
        printf(ok ? "  MATCH: partial+continued adosc equals full recompute\n"
                  : "  MISMATCH detected!\n");

        tulip_ffi_batch_result_free(br);
        adosc_state_free(state);
    }
    printf("\n=== ADOSC: state persistence (serialize / deserialize) ===\n");
    {
        const double *pinputs[ADOSC_INPUTS] = {high, low, close, volume};
        CIndicatorResult pr = adosc_indicator(pinputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) { fprintf(stderr, "adosc_indicator failed\n"); return 1; }
        void *st = pr.state;
        tulip_ffi_result_free(pr);

        CBytes blob = tulip_state_serialize(C_INDICATOR_ID_ADOSC, C_STATE_FORMAT_BINCODE, st);
        if (blob.ptr == NULL) { fprintf(stderr, "serialize failed\n"); return 1; }
        printf("  blob: %zu bytes, magic=%.4s, name=%.32s\n",
               blob.len, (const char *)blob.ptr, (const char *)blob.ptr + 6);

        void *rs = tulip_state_deserialize(blob.ptr, blob.len);
        tulip_ffi_bytes_free(blob);
        if (rs == NULL) { fprintf(stderr, "deserialize failed\n"); return 1; }

        const double *rinputs[ADOSC_INPUTS] = {high + PARTIAL, low + PARTIAL, close + PARTIAL, volume + PARTIAL};
        CBatchResult a = adosc_batch(st, rinputs, REST, NULL, 0);
        CBatchResult b = adosc_batch(rs, rinputs, REST, NULL, 0);
        int persist_ok = a.error == C_INDICATOR_ERROR_OK && b.error == C_INDICATOR_ERROR_OK &&
                         a.output_lens[0] == b.output_lens[0] &&
                         allclose(a.outputs[0], b.outputs[0], a.output_lens[0]);
        printf(persist_ok ? "  MATCH: deserialized state continues identically\n"
                          : "  MISMATCH detected!\n");
        tulip_ffi_batch_result_free(a);
        tulip_ffi_batch_result_free(b);
        adosc_state_free(st);
        adosc_state_free(rs);
    }


    printf("\n=== ADOSC: SIMD by assets (N=4) ===\n");
    {
        // Asset 1: original data.
        const double *const asset1[ADOSC_INPUTS] = {high, low, close, volume};

        // Asset 2: scaled up (+20%).
        double high_2[TOTAL], low_2[TOTAL], close_2[TOTAL], volume_2[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_2[i] = high[i] * 1.2;
            low_2[i] = low[i] * 1.2;
            close_2[i] = close[i] * 1.2;
            volume_2[i] = volume[i] * 1.2;
        }
        const double *const asset2[ADOSC_INPUTS] = {high_2, low_2, close_2, volume_2};

        // Asset 3: different upward trend.
        double high_3[TOTAL], low_3[TOTAL], close_3[TOTAL], volume_3[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_3[i] = 90.0 + (double) i * 0.5 + high[i] * 0.1;
            low_3[i] = 90.0 + (double) i * 0.5 + low[i] * 0.1;
            close_3[i] = 90.0 + (double) i * 0.5 + close[i] * 0.1;
            volume_3[i] = 90.0 + (double) i * 0.5 + volume[i] * 0.1;
        }
        const double *const asset3[ADOSC_INPUTS] = {high_3, low_3, close_3, volume_3};

        // Asset 4: downward trend.
        double high_4[TOTAL], low_4[TOTAL], close_4[TOTAL], volume_4[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_4[i] = 100.0 - (double) i * 0.3 + high[i] * 0.05;
            low_4[i] = 100.0 - (double) i * 0.3 + low[i] * 0.05;
            close_4[i] = 100.0 - (double) i * 0.3 + close[i] * 0.05;
            volume_4[i] = 100.0 - (double) i * 0.3 + volume[i] * 0.05;
        }
        const double *const asset4[ADOSC_INPUTS] = {high_4, low_4, close_4, volume_4};

        // simd_inputs is indexed by asset (the N=4 SIMD lanes), NOT by input
        // series -- hence [4] here stays a lane count.
        const double *const *const simd_inputs[4] = {asset1, asset2, asset3, asset4};
        bool optional_outputs[3] = {true, true, true};

        CSimdResult r = adosc_simd_by_assets(simd_inputs, 4, TOTAL, options, optional_outputs, 3);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "adosc_simd_by_assets failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            printf("Asset %zu ", i + 1);
            print_row("adosc", r.outputs[i][0], r.output_lens[i][0]);
        }

        printf("\nVerification - calculating each asset individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = adosc_indicator(
                simd_inputs[i], TOTAL, options, optional_outputs, 3);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "adosc_indicator (asset %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            printf("  Asset %zu: %s\n", i + 1, match ? "MATCH" : "MISMATCH");
            if (!match) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            adosc_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) adosc_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-assets equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    printf("\n=== ADOSC: SIMD by options (N=4) ===\n");
    {
        // Tile the base series 20x so longer-period option sets have enough data.
        #define EXPANDED_LEN (TOTAL * 20)
        static double high_expanded[EXPANDED_LEN];
        static double low_expanded[EXPANDED_LEN];
        static double close_expanded[EXPANDED_LEN];
        static double volume_expanded[EXPANDED_LEN];
        for (size_t i = 0; i < 20; i++) {
            for (size_t j = 0; j < TOTAL; j++) {
                high_expanded[i * TOTAL + j] = high[j];
                low_expanded[i * TOTAL + j] = low[j];
                close_expanded[i * TOTAL + j] = close[j];
                volume_expanded[i * TOTAL + j] = volume[j];
            }
        }
        const double *expanded_inputs[ADOSC_INPUTS] = {
            high_expanded, low_expanded, close_expanded, volume_expanded};

        static const double options_1[ADOSC_OPTIONS] = {3.0, 10.0};
        static const double options_2[ADOSC_OPTIONS] = {4.0, 12.0};
        static const double options_3[ADOSC_OPTIONS] = {5.0, 15.0};
        static const double options_4[ADOSC_OPTIONS] = {6.0, 20.0};
        // simd_options is indexed by option set (the N=4 lanes), each lane
        // pointing at ADOSC_OPTIONS values.
        const double *const simd_options[4] = {options_1, options_2, options_3, options_4};

        CSimdResult r = adosc_simd_by_options(
            expanded_inputs, EXPANDED_LEN, simd_options, 4, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "adosc_simd_by_options failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            char label[32];
            snprintf(label, sizeof(label), "option set %zu", i + 1);
            print_row_head(label, r.outputs[i][0], r.output_lens[i][0], 5);
        }

        printf("\nVerification - calculating each option set individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = adosc_indicator(
                expanded_inputs, EXPANDED_LEN, simd_options[i], NULL, 0);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "adosc_indicator (option set %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            printf("  Option set %zu: %s\n", i + 1, match ? "MATCH" : "MISMATCH");
            if (!match) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            adosc_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) adosc_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-options equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    return 0;
}
