// ADX (Average Directional Index) example for tulip_rs_ffi.
// Mirrors tulip_rs_python/examples/ti_adx_example.py: same sample data,
// same options, same "compute partial, continue via batch, verify against a
// full recompute" flow, plus SIMD by-assets/by-options demonstrations.
//
// ADX_INPUTS/ADX_OPTIONS come from ../include/tulip_rs_ffi_counts.h,
// generated by ../build.rs from the real tulip_rs::indicators::adx::
// {INPUTS, OPTIONS} constants (run `cargo build` at least once so that file
// exists/is current). The main header is the cbindgen-generated one in
// ../include/, which is the up-to-date API surface.
//
// Build (from the tulip_rs_ffi directory):
//   cc -O2 -o adx_example examples/adx_example.c \
//       -L target/release -ltulip_rs_ffi -Wl,-rpath,target/release
// Run:
//   ./adx_example

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../include/tulip_rs_ffi.h"

static const double high[]    = {82.15, 81.89, 83.03, 83.30, 83.85, 83.90, 83.33, 84.30, 84.84, 85.00, 85.90, 86.58, 86.98, 88.00, 87.87};
static const double low[]     = {81.29, 80.64, 81.31, 82.65, 83.07, 83.11, 82.49, 82.30, 84.15, 84.11, 84.03, 85.39, 85.76, 87.17, 87.01};
static const double close[]   = {81.59, 81.06, 82.87, 83.00, 83.61, 83.15, 82.84, 83.99, 84.55, 84.36, 85.53, 86.54, 86.89, 87.77, 87.29};

#define TOTAL 15
#define PARTIAL (TOTAL - 5)
#define REST (TOTAL - PARTIAL)

static void print_row(const char *label, const double *row, size_t len) {
    printf("  %-14s: [", label);
    for (size_t i = 0; i < len; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < len) printf(", ");
    }
    printf("]\n");
}

static void print_row_head(const char *label, const double *row, size_t len, size_t max_print) {
    printf("  %-14s: [", label);
    size_t n = len < max_print ? len : max_print;
    for (size_t i = 0; i < n; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < n) printf(", ");
    }
    printf(len > max_print ? ", ...]\n" : "]\n");
}

static int allclose(const double *a, const double *b, size_t len) {
    for (size_t i = 0; i < len; i++) {
        double diff = a[i] - b[i];
        if (diff < 0) diff = -diff;
        if (diff > 1e-9) return 0;
    }
    return 1;
}

int main(void) {
    const double options[ADX_OPTIONS] = {5.0}; // period
    double full_adx[TOTAL];
    size_t full_adx_len = 0;

    CIndicatorInfo info = adx_info();
    printf("=== %s (%s) ===\n", info.name, info.full_name);
    printf("Inputs: %u, Options: %u (period), Optional outputs: %u\n",
           (unsigned)ADX_INPUTS, (unsigned)ADX_OPTIONS,
           (unsigned)info.optional_outputs.len);
    printf("Minimum data required: %zu\n", adx_min_data(options));

    printf("\n=== ADX: full calculation (all optional outputs) ===\n");
    {
        const double *inputs[ADX_INPUTS] = {high, low, close};
        bool optional_outputs[3] = {true, true, true}; // dx, atr, tr

        CIndicatorResult r = adx_indicator(inputs, TOTAL, options, optional_outputs, 3);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "adx_indicator failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_outputs=%zu\n", r.num_outputs);
        print_row("adx", r.outputs[0], r.output_lens[0]);
        print_row("dx", r.outputs[1], r.output_lens[1]);
        print_row("atr", r.outputs[2], r.output_lens[2]);
        print_row("tr", r.outputs[3], r.output_lens[3]);

        // Keep a copy of the mandatory "adx" row for later verification.
        full_adx_len = r.output_lens[0];
        for (size_t i = 0; i < full_adx_len; i++) full_adx[i] = r.outputs[0][i];

        void *unused_state = r.state;
        tulip_ffi_result_free(r);
        adx_state_free(unused_state);
    }

    printf("\n=== ADX: partial calculation + batch continuation ===\n");
    {
        const double *partial_inputs[ADX_INPUTS] = {high, low, close};
        CIndicatorResult pr = adx_indicator(partial_inputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "adx_indicator (partial) failed: error=%d\n", pr.error);
            return 1;
        }
        print_row("adx (partial)", pr.outputs[0], pr.output_lens[0]);
        void *state = pr.state;
        tulip_ffi_result_free(pr); // outputs freed; state kept alive

        const double *rest_inputs[ADX_INPUTS] = {high + PARTIAL, low + PARTIAL, close + PARTIAL};
        CBatchResult br = adx_batch(state, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "adx_batch failed: error=%d\n", br.error);
            return 1;
        }
        print_row("adx (continued)", br.outputs[0], br.output_lens[0]);

        printf("\n=== Verification: partial+continued vs. full recompute ===\n");
        int ok = 1;
        size_t continued_len = br.output_lens[0];
        size_t tail_start = full_adx_len - continued_len;
        for (size_t i = 0; i < continued_len; i++) {
            double a = full_adx[tail_start + i];
            double b = br.outputs[0][i];
            double diff = a > b ? a - b : b - a;
            if (diff > 1e-9) {
                ok = 0;
                printf("  mismatch at %zu: full=%.6f continued=%.6f\n", i, a, b);
            }
        }
        printf(ok ? "  MATCH: partial+continued adx equals full recompute\n"
                  : "  MISMATCH detected!\n");

        tulip_ffi_batch_result_free(br);
        adx_state_free(state);
    }

    printf("\n=== ADX: state persistence (serialize / deserialize / clone) ===\n");
    {
        // Same partial+batch flow as above, but the streaming state is now
        // saved as an opaque byte blob (bincode) in between. This is what a
        // binding layer writes to a DB/file: the bytes are meaningless to
        // the caller, and only ever go back through tulip_state_deserialize().
        const double *partial_inputs[ADX_INPUTS] = {high, low, close};
        CIndicatorResult pr = adx_indicator(partial_inputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "adx_indicator (persist demo) failed: error=%d\n", pr.error);
            return 1;
        }
        void *state = pr.state;
        tulip_ffi_result_free(pr);

        // Serialize the live state (bincode format). The state handle is
        // read-only here: it stays valid and usable afterwards.
        CBytes blob = tulip_state_serialize(C_INDICATOR_ID_ADX, C_STATE_FORMAT_BINCODE, state);
        if (blob.ptr == NULL || blob.len == 0) {
            fprintf(stderr, "tulip_state_serialize failed\n");
            return 1;
        }
        printf("  bincode blob: %zu bytes, magic=%.4s, schema=%u, name=%.32s\n",
               blob.len, (const char *)blob.ptr, (unsigned)blob.ptr[4],
               (const char *)blob.ptr + 6);

        // Deserialize into a fresh, independent state handle -- indist-
        // inguishable from what adx_indicator() handed out. Free it with
        // adx_state_free() like any other state.
        void *restored = tulip_state_deserialize(blob.ptr, blob.len);
        if (restored == NULL) {
            fprintf(stderr, "tulip_state_deserialize failed\n");
            return 1;
        }

        // Continue the RESTORED state and verify it matches the full
        // recompute tail-for-tail (same check the batch section does).
        const double *rest_inputs[ADX_INPUTS] = {high + PARTIAL, low + PARTIAL, close + PARTIAL};
        CBatchResult br = adx_batch(restored, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "adx_batch (restored) failed: error=%d\n", br.error);
            return 1;
        }
        print_row("adx (restored)", br.outputs[0], br.output_lens[0]);
        size_t cont_len = br.output_lens[0];
        size_t tail_start = full_adx_len - cont_len;
        int persist_ok = allclose(full_adx + tail_start, br.outputs[0], cont_len);
        printf(persist_ok
                   ? "  MATCH: deserialized state continues identically\n"
                   : "  MISMATCH detected!\n");
        tulip_ffi_batch_result_free(br);
        adx_state_free(restored);

        // JSON format (1): human-readable for debugging only -- NOT valid
        // to hand back to tulip_state_deserialize as if it were the
        // persistence format? It IS (the format byte round-trips), but
        // serde_json rejects non-finite f64s, so bincode is recommended.
        CBytes json_blob = tulip_state_serialize(C_INDICATOR_ID_ADX, C_STATE_FORMAT_JSON, state);
        if (json_blob.ptr == NULL) {
            fprintf(stderr, "tulip_state_serialize (json) failed\n");
            return 1;
        }
        printf("  json blob (%zu bytes, %zu after header): %.*s%s\n", json_blob.len,
               json_blob.len - 38,
               (int)(json_blob.len - 38 < 80 ? json_blob.len - 38 : 80),
               (const char *)json_blob.ptr + 38,
               json_blob.len - 38 > 80 ? "..." : "");
        void *from_json = tulip_state_deserialize(json_blob.ptr, json_blob.len);
        printf("  json roundtrip: %s\n", from_json ? "OK" : "FAILED");
        if (from_json) adx_state_free(from_json);
        tulip_ffi_bytes_free(json_blob);

        // Clone: an in-process deep copy via Rust's Clone (no serde
        // involved), same ownership rules as a deserialized state.
        void *cloned = tulip_state_clone(C_INDICATOR_ID_ADX, state);
        CBatchResult cb = adx_batch(cloned, rest_inputs, REST, NULL, 0);
        CBatchResult ob = adx_batch(state, rest_inputs, REST, NULL, 0);
        int clone_ok = cloned != NULL &&
                       cb.error == C_INDICATOR_ERROR_OK &&
                       ob.error == C_INDICATOR_ERROR_OK &&
                       cb.output_lens[0] == ob.output_lens[0] &&
                       allclose(cb.outputs[0], ob.outputs[0], cb.output_lens[0]);
        printf(clone_ok
                   ? "  MATCH: cloned state continues identically\n"
                   : "  MISMATCH detected!\n");
        tulip_ffi_batch_result_free(cb);
        tulip_ffi_batch_result_free(ob);
        adx_state_free(cloned);

        // Misuse checks: the blob is self-describing (the TRFS header
        // embeds the indicator NAME), so there is no id argument to get
        // wrong on deserialize -- instead, corruption must be caught: a
        // bad schema version byte or a corrupted name both yield NULL,
        // never a wrong-typed handle. And an unknown id is rejected on
        // the serialize side.
        CBytes noblob = tulip_state_serialize(999, C_STATE_FORMAT_BINCODE, state);
        uint8_t *corrupt = malloc(blob.len);
        memcpy(corrupt, blob.ptr, blob.len);
        corrupt[4] = 1; // claim the retired schema-1 layout
        void *bad1 = tulip_state_deserialize(corrupt, blob.len);
        corrupt[4] = 2; corrupt[6] = 'q'; // no indicator is named "qdx"
        void *bad2 = tulip_state_deserialize(corrupt, blob.len);
        printf("  misuse checks: unknown-serialize-id %s, bad-schema %s, bad-name %s\n",
               noblob.ptr == NULL ? "rejected" : "ACCEPTED (BUG!)",
               bad1 == NULL ? "rejected" : "ACCEPTED (BUG!)",
               bad2 == NULL ? "rejected" : "ACCEPTED (BUG!)");
        free(corrupt);
        if (noblob.ptr || bad1 || bad2) persist_ok = 0;

        tulip_ffi_bytes_free(blob); // exactly once; blob is now dead
        adx_state_free(state);
        printf(persist_ok ? "  ALL GOOD: persistence round-trips clean\n"
                          : "  PERSISTENCE DEMO FAILED!\n");
    }

    printf("\n=== ADX: SIMD by assets (N=4) ===\n");
    {
        // Asset 1: original data.
        const double *const asset1[ADX_INPUTS] = {high, low, close};

        // Asset 2: scaled up (+20%).
        double high_2[TOTAL], low_2[TOTAL], close_2[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_2[i] = high[i] * 1.2;
            low_2[i] = low[i] * 1.2;
            close_2[i] = close[i] * 1.2;
        }
        const double *const asset2[ADX_INPUTS] = {high_2, low_2, close_2};

        // Asset 3: different upward trend.
        double high_3[TOTAL], low_3[TOTAL], close_3[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_3[i] = 90.0 + (double)i * 0.5 + high[i] * 0.1;
            low_3[i] = 90.0 + (double)i * 0.5 + low[i] * 0.1;
            close_3[i] = 90.0 + (double)i * 0.5 + close[i] * 0.1;
        }
        const double *const asset3[ADX_INPUTS] = {high_3, low_3, close_3};

        // Asset 4: downward trend.
        double high_4[TOTAL], low_4[TOTAL], close_4[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_4[i] = 100.0 - (double)i * 0.3 + high[i] * 0.05;
            low_4[i] = 100.0 - (double)i * 0.3 + low[i] * 0.05;
            close_4[i] = 100.0 - (double)i * 0.3 + close[i] * 0.05;
        }
        const double *const asset4[ADX_INPUTS] = {high_4, low_4, close_4};

        // simd_inputs is indexed by asset (the N=4 SIMD lanes), NOT by input
        // series -- hence [4] here stays a lane count.
        const double *const *const simd_inputs[4] = {asset1, asset2, asset3, asset4};
        bool optional_outputs[3] = {true, true, true};

        CSimdResult r = adx_simd_by_assets(simd_inputs, 4, TOTAL, options, optional_outputs, 3);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "adx_simd_by_assets failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            printf("Asset %zu ", i + 1);
            print_row("adx", r.outputs[i][0], r.output_lens[i][0]);
        }

        printf("\nVerification - calculating each asset individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = adx_indicator(
                simd_inputs[i], TOTAL, options, optional_outputs, 3);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "adx_indicator (asset %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            printf("  Asset %zu: %s\n", i + 1, match ? "MATCH" : "MISMATCH");
            if (!match) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            adx_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) adx_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-assets equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    printf("\n=== ADX: SIMD by options (N=4) ===\n");
    {
        // Tile the base series 20x so longer-period option sets have enough data.
        #define EXPANDED_LEN (TOTAL * 20)
        static double high_expanded[EXPANDED_LEN];
        static double low_expanded[EXPANDED_LEN];
        static double close_expanded[EXPANDED_LEN];
        for (size_t i = 0; i < 20; i++) {
            for (size_t j = 0; j < TOTAL; j++) {
                high_expanded[i * TOTAL + j] = high[j];
                low_expanded[i * TOTAL + j] = low[j];
                close_expanded[i * TOTAL + j] = close[j];
            }
        }
        const double *expanded_inputs[ADX_INPUTS] = {high_expanded, low_expanded, close_expanded};

        static const double options_1[ADX_OPTIONS] = {3.0};
        static const double options_2[ADX_OPTIONS] = {5.0};
        static const double options_3[ADX_OPTIONS] = {7.0};
        static const double options_4[ADX_OPTIONS] = {10.0};
        // simd_options is indexed by option set (the N=4 lanes), each lane
        // pointing at ADX_OPTIONS values.
        const double *const simd_options[4] = {options_1, options_2, options_3, options_4};

        CSimdResult r = adx_simd_by_options(
            expanded_inputs, EXPANDED_LEN, simd_options, 4, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "adx_simd_by_options failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            char label[32];
            snprintf(label, sizeof(label), "option set %zu", i + 1);
            print_row_head(label, r.outputs[i][0], r.output_lens[i][0], 5);
        }

        printf("\nVerification - calculating each option set individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = adx_indicator(
                expanded_inputs, EXPANDED_LEN, simd_options[i], NULL, 0);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "adx_indicator (option set %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            printf("  Option set %zu: %s\n", i + 1, match ? "MATCH" : "MISMATCH");
            if (!match) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            adx_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) adx_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-options equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    return 0;
}
