// AO (Awesome Oscillator) example for tulip_rs_ffi.
// Mirrors tulip_rs_python/examples/ti_ao_example.py: same sample data,
// same options, same "compute partial, continue via batch, verify against a
// full recompute" flow, plus SIMD by-assets/by-options demonstrations.
//
// AO_INPUTS/AO_OPTIONS come from ../include/tulip_rs_ffi_counts.h,
// generated by ../build.rs from the real tulip_rs::indicators::ao::
// {INPUTS, OPTIONS} constants (run `cargo build` at least once so that file
// exists/is current). The main header is the cbindgen-generated one in
// ../include/, which is the up-to-date API surface.
//
// Build (from the tulip_rs_ffi directory):
//   cc -O2 -o ao_example examples/ao_example.c \
//       -L target/release -ltulip_rs_ffi -Wl,-rpath,target/release
// Run:
//   ./ao_example

#include <stdio.h>
#include <stdlib.h>

#include "../include/tulip_rs_ffi.h"

static const double high_base[] = {82.15, 81.89, 83.03, 83.30, 83.85, 83.90, 83.33, 84.30, 84.84, 85.00, 85.90, 86.58, 86.98, 88.00, 87.87};
static const double low_base[]  = {81.29, 80.64, 81.31, 82.65, 83.07, 83.11, 82.49, 82.30, 84.15, 84.11, 84.03, 85.39, 85.76, 87.17, 87.01};

// Extend the data 5 times as in Python example (base * 5)
static const double high[] = {
    82.15, 81.89, 83.03, 83.30, 83.85, 83.90, 83.33, 84.30, 84.84, 85.00,
    85.90, 86.58, 86.98, 88.00, 87.87,
    82.15, 81.89, 83.03, 83.30, 83.85, 83.90, 83.33, 84.30, 84.84, 85.00,
    85.90, 86.58, 86.98, 88.00, 87.87,
    82.15, 81.89, 83.03, 83.30, 83.85, 83.90, 83.33, 84.30, 84.84, 85.00,
    85.90, 86.58, 86.98, 88.00, 87.87,
    82.15, 81.89, 83.03, 83.30, 83.85, 83.90, 83.33, 84.30, 84.84, 85.00,
    85.90, 86.58, 86.98, 88.00, 87.87,
    82.15, 81.89, 83.03, 83.30, 83.85, 83.90, 83.33, 84.30, 84.84, 85.00,
    85.90, 86.58, 86.98, 88.00, 87.87
};

static const double low[] = {
    81.29, 80.64, 81.31, 82.65, 83.07, 83.11, 82.49, 82.30, 84.15, 84.11,
    84.03, 85.39, 85.76, 87.17, 87.01,
    81.29, 80.64, 81.31, 82.65, 83.07, 83.11, 82.49, 82.30, 84.15, 84.11,
    84.03, 85.39, 85.76, 87.17, 87.01,
    81.29, 80.64, 81.31, 82.65, 83.07, 83.11, 82.49, 82.30, 84.15, 84.11,
    84.03, 85.39, 85.76, 87.17, 87.01,
    81.29, 80.64, 81.31, 82.65, 83.07, 83.11, 82.49, 82.30, 84.15, 84.11,
    84.03, 85.39, 85.76, 87.17, 87.01,
    81.29, 80.64, 81.31, 82.65, 83.07, 83.11, 82.49, 82.30, 84.15, 84.11,
    84.03, 85.39, 85.76, 87.17, 87.01
};

#define TOTAL 75
#define PARTIAL (TOTAL - 5)
#define REST (TOTAL - PARTIAL)

static void print_row(const char *label, const double *row, size_t len) {
    printf("  %-14s: [", label);
    for (size_t i = 0; i < len; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < len) printf(", ");
    }
    printf("]\n");
}

static void print_row_head(const char *label, const double *row, size_t len, size_t max_print) {
    printf("  %-14s: [", label);
    size_t n = len < max_print ? len : max_print;
    for (size_t i = 0; i < n; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < n) printf(", ");
    }
    printf(len > max_print ? ", ...]\n" : "]\n");
}

static int allclose(const double *a, const double *b, size_t len) {
    for (size_t i = 0; i < len; i++) {
        double diff = a[i] - b[i];
        if (diff < 0) diff = -diff;
        if (diff > 1e-9) return 0;
    }
    return 1;
}

int main(void) {
    const double options[AO_OPTIONS] = {}; // no options
    double full_ao[TOTAL];
    size_t full_ao_len = 0;

    CIndicatorInfo info = ao_info();
    printf("=== %s (%s) ===\n", info.name, info.full_name);
    printf("Inputs: %u, Options: %u (none), Optional outputs: %u\n",
           (unsigned)AO_INPUTS, (unsigned)AO_OPTIONS,
           (unsigned)info.optional_outputs.len);
    printf("Minimum data required: %zu\n", ao_min_data(options));

    printf("\n=== AO: full calculation (all optional outputs) ===\n");
    {
        const double *inputs[AO_INPUTS] = {high, low};
        bool optional_outputs[2] = {true, true}; // short_sma, long_sma

        CIndicatorResult r = ao_indicator(inputs, TOTAL, options, optional_outputs, 2);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "ao_indicator failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_outputs=%zu\n", r.num_outputs);
        print_row("ao", r.outputs[0], r.output_lens[0]);
        print_row("short_sma", r.outputs[1], r.output_lens[1]);
        print_row("long_sma", r.outputs[2], r.output_lens[2]);

        // Keep a copy of the mandatory "ao" row for later verification.
        full_ao_len = r.output_lens[0];
        for (size_t i = 0; i < full_ao_len; i++) full_ao[i] = r.outputs[0][i];

        void *unused_state = r.state;
        tulip_ffi_result_free(r);
        ao_state_free(unused_state);
    }

    printf("\n=== AO: partial calculation + batch continuation ===\n");
    {
        const double *partial_inputs[AO_INPUTS] = {high, low};
        CIndicatorResult pr = ao_indicator(partial_inputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "ao_indicator (partial) failed: error=%d\n", pr.error);
            return 1;
        }
        print_row("ao (partial)", pr.outputs[0], pr.output_lens[0]);
        void *state = pr.state;
        tulip_ffi_result_free(pr); // outputs freed; state kept alive

        const double *rest_inputs[AO_INPUTS] = {high + PARTIAL, low + PARTIAL};
        CBatchResult br = ao_batch(state, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "ao_batch failed: error=%d\n", br.error);
            return 1;
        }
        print_row("ao (continued)", br.outputs[0], br.output_lens[0]);

        printf("\n=== Verification: partial+continued vs. full recompute ===\n");
        int ok = 1;
        size_t continued_len = br.output_lens[0];
        size_t tail_start = full_ao_len - continued_len;
        for (size_t i = 0; i < continued_len; i++) {
            double a = full_ao[tail_start + i];
            double b = br.outputs[0][i];
            double diff = a > b ? a - b : b - a;
            if (diff > 1e-9) {
                ok = 0;
                printf("  mismatch at %zu: full=%.6f continued=%.6f\n", i, a, b);
            }
        }
        printf(ok ? "  MATCH: partial+continued ao equals full recompute\n"
                  : "  MISMATCH detected!\n");

        tulip_ffi_batch_result_free(br);
        ao_state_free(state);
    }

    printf("\n=== AO: SIMD by assets (N=4) ===\n");
    {
        // Asset 1: original data.
        const double *const asset1[AO_INPUTS] = {high, low};

        // Asset 2: scaled up (+20%).
        double high_2[TOTAL], low_2[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_2[i] = high[i] * 1.2;
            low_2[i] = low[i] * 1.2;
        }
        const double *const asset2[AO_INPUTS] = {high_2, low_2};

        // Asset 3: different upward trend.
        double high_3[TOTAL], low_3[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_3[i] = 90.0 + (double)i * 0.5 + high[i] * 0.1;
            low_3[i] = 90.0 + (double)i * 0.5 + low[i] * 0.1;
        }
        const double *const asset3[AO_INPUTS] = {high_3, low_3};

        // Asset 4: downward trend.
        double high_4[TOTAL], low_4[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_4[i] = 100.0 - (double)i * 0.3 + high[i] * 0.05;
            low_4[i] = 100.0 - (double)i * 0.3 + low[i] * 0.05;
        }
        const double *const asset4[AO_INPUTS] = {high_4, low_4};

        // simd_inputs is indexed by asset (the N=4 SIMD lanes), NOT by input
        // series -- hence [4] here stays a lane count.
        const double *const *const simd_inputs[4] = {asset1, asset2, asset3, asset4};
        bool optional_outputs[2] = {true, true};

        CSimdResult r = ao_simd_by_assets(simd_inputs, 4, TOTAL, options, optional_outputs, 2);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "ao_simd_by_assets failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            printf("Asset %zu ", i + 1);
            print_row("ao", r.outputs[i][0], r.output_lens[i][0]);
        }

        printf("\nVerification - calculating each asset individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = ao_indicator(
                simd_inputs[i], TOTAL, options, optional_outputs, 2);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "ao_indicator (asset %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            printf("  Asset %zu: %s\n", i + 1, match ? "MATCH" : "MISMATCH");
            if (!match) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            ao_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) ao_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-assets equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    // Note: AO has 0 options, so no simd_by_options function exists
    printf("\n=== AO: SIMD by options (N=4) ===\n");
    printf("  SKIPPED - AO has 0 options and does not provide simd_by_options.\n");

    return 0;
}
