// AROONOSC (Aroon Oscillator) example for tulip_rs_ffi.
// Mirrors tulip_rs_python/examples/ti_aroonosc_example.py: same sample data,
// same options, same "compute partial, continue via batch, verify against a
// full recompute" flow, plus SIMD by-assets/by-options demonstrations.
//
// AROONOSC_INPUTS/AROONOSC_OPTIONS come from ../include/tulip_rs_ffi_counts.h,
// generated by ../build.rs from the real tulip_rs::indicators::aroonosc::
// {INPUTS, OPTIONS} constants (run `cargo build` at least once so that file
// exists/is current). The main header is the cbindgen-generated one in
// ../include/, which is the up-to-date API surface.
//
// Build (from the tulip_rs_ffi directory):
//   cc -O2 -o aroonosc_example examples/aroonosc_example.c \
//       -L target/release -ltulip_rs_ffi -Wl,-rpath,target/release
// Run:
//   ./aroonosc_example

#include <stdio.h>
#include <stdlib.h>

#include "../include/tulip_rs_ffi.h"

static const double high[] = {82.15, 81.89, 83.03, 83.30, 83.85, 83.90, 83.33, 84.30, 84.84, 85.00, 85.90, 86.58, 86.98, 88.00, 87.87};
static const double low[] = {81.29, 80.64, 81.31, 82.65, 83.07, 83.11, 82.49, 82.30, 84.15, 84.11, 84.03, 85.39, 85.76, 87.17, 87.01};

#define TOTAL 15
#define PARTIAL (TOTAL - 5)
#define REST (TOTAL - PARTIAL)

static void print_row(const char *label, const double *row, size_t len) {
    printf("  %-14s: [", label);
    for (size_t i = 0; i < len; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < len) printf(", ");
    }
    printf("]\n");
}

static void print_row_head(const char *label, const double *row, size_t len, size_t max_print) {
    printf("  %-14s: [", label);
    size_t n = len < max_print ? len : max_print;
    for (size_t i = 0; i < n; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < n) printf(", ");
    }
    printf(len > max_print ? ", ...]\n" : "]\n");
}

static int allclose(const double *a, const double *b, size_t len) {
    for (size_t i = 0; i < len; i++) {
        double diff = a[i] - b[i];
        if (diff < 0) diff = -diff;
        if (diff > 1e-9) return 0;
    }
    return 1;
}

int main(void) {
    const double options[AROONOSC_OPTIONS] = {5.0}; // period
    double full_aroonosc[TOTAL];
    size_t full_aroonosc_len = 0;

    CIndicatorInfo info = aroonosc_info();
    printf("=== %s (%s) ===\n", info.name, info.full_name);
    printf("Inputs: %u, Options: %u (period), Optional outputs: %u\n",
           (unsigned)AROONOSC_INPUTS, (unsigned)AROONOSC_OPTIONS,
           (unsigned)info.optional_outputs.len);
    printf("Minimum data required: %zu\n", aroonosc_min_data(options));

    printf("\n=== AROONOSC: full calculation ===\n");
    {
        const double *inputs[AROONOSC_INPUTS] = {high, low};
        bool optional_outputs[2] = {true, true}; // aroon_down, aroon_up

        CIndicatorResult r = aroonosc_indicator(inputs, TOTAL, options, optional_outputs, 2);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "aroonosc_indicator failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_outputs=%zu\n", r.num_outputs);
        print_row("aroonosc", r.outputs[0], r.output_lens[0]);
        print_row("aroon_down", r.outputs[1], r.output_lens[1]);
        print_row("aroon_up", r.outputs[2], r.output_lens[2]);

        // Keep a copy of the mandatory "aroonosc" row for later verification.
        full_aroonosc_len = r.output_lens[0];
        for (size_t i = 0; i < full_aroonosc_len; i++) full_aroonosc[i] = r.outputs[0][i];

        void *unused_state = r.state;
        tulip_ffi_result_free(r);
        aroonosc_state_free(unused_state);
    }

    printf("\n=== AROONOSC: partial calculation + batch continuation ===\n");
    {
        const double *partial_inputs[AROONOSC_INPUTS] = {high, low};
        CIndicatorResult pr = aroonosc_indicator(partial_inputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "aroonosc_indicator (partial) failed: error=%d\n", pr.error);
            return 1;
        }
        print_row("aroonosc (partial)", pr.outputs[0], pr.output_lens[0]);
        void *state = pr.state;
        tulip_ffi_result_free(pr); // outputs freed; state kept alive

        const double *rest_inputs[AROONOSC_INPUTS] = {high + PARTIAL, low + PARTIAL};
        CBatchResult br = aroonosc_batch(state, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "aroonosc_batch failed: error=%d\n", br.error);
            return 1;
        }
        print_row("aroonosc (continued)", br.outputs[0], br.output_lens[0]);

        printf("\n=== Verification: partial+continued vs. full recompute ===\n");
        int ok = 1;
        size_t continued_len = br.output_lens[0];
        size_t tail_start = full_aroonosc_len - continued_len;
        for (size_t i = 0; i < continued_len; i++) {
            double a = full_aroonosc[tail_start + i];
            double b = br.outputs[0][i];
            double diff = a > b ? a - b : b - a;
            if (diff > 1e-9) {
                ok = 0;
                printf("  mismatch at %zu: full=%.6f continued=%.6f\n", i, a, b);
            }
        }
        printf(ok ? "  MATCH: partial+continued aroonosc equals full recompute\n"
                  : "  MISMATCH detected!\n");

        tulip_ffi_batch_result_free(br);
        aroonosc_state_free(state);
    }

    printf("\n=== AROONOSC: SIMD by assets (N=4) ===\n");
    {
        // Asset 1: original data.
        const double *const asset1[AROONOSC_INPUTS] = {high, low};

        // Asset 2: scaled up (+20%).
        double high_2[TOTAL], low_2[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_2[i] = high[i] * 1.2;
            low_2[i] = low[i] * 1.2;
        }
        const double *const asset2[AROONOSC_INPUTS] = {high_2, low_2};

        // Asset 3: different upward trend.
        double high_3[TOTAL], low_3[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_3[i] = 90.0 + (double)i * 0.5 + high[i] * 0.1;
            low_3[i] = 90.0 + (double)i * 0.5 + low[i] * 0.1;
        }
        const double *const asset3[AROONOSC_INPUTS] = {high_3, low_3};

        // Asset 4: downward trend.
        double high_4[TOTAL], low_4[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_4[i] = 100.0 - (double)i * 0.3 + high[i] * 0.05;
            low_4[i] = 100.0 - (double)i * 0.3 + low[i] * 0.05;
        }
        const double *const asset4[AROONOSC_INPUTS] = {high_4, low_4};

        // simd_inputs is indexed by asset (the N=4 SIMD lanes), NOT by input
        // series -- hence [4] here stays a lane count.
        const double *const *const simd_inputs[4] = {asset1, asset2, asset3, asset4};
        bool optional_outputs[2] = {true, true};

        CSimdResult r = aroonosc_simd_by_assets(simd_inputs, 4, TOTAL, options, optional_outputs, 2);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "aroonosc_simd_by_assets failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            printf("Asset %zu ", i + 1);
            print_row("aroonosc", r.outputs[i][0], r.output_lens[i][0]);
        }

        printf("\nVerification - calculating each asset individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = aroonosc_indicator(
                simd_inputs[i], TOTAL, options, optional_outputs, 2);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "aroonosc_indicator (asset %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            printf("  Asset %zu: %s\n", i + 1, match ? "MATCH" : "MISMATCH");
            if (!match) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            aroonosc_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) aroonosc_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-assets equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    printf("\n=== AROONOSC: SIMD by options (N=4) ===\n");
    {
        // Tile the base series 20x so longer-period option sets have enough data.
        #define EXPANDED_LEN (TOTAL * 20)
        static double high_expanded[EXPANDED_LEN];
        static double low_expanded[EXPANDED_LEN];
        for (size_t i = 0; i < 20; i++) {
            for (size_t j = 0; j < TOTAL; j++) {
                high_expanded[i * TOTAL + j] = high[j];
                low_expanded[i * TOTAL + j] = low[j];
            }
        }
        const double *expanded_inputs[AROONOSC_INPUTS] = {high_expanded, low_expanded};

        static const double options_1[AROONOSC_OPTIONS] = {3.0};
        static const double options_2[AROONOSC_OPTIONS] = {5.0};
        static const double options_3[AROONOSC_OPTIONS] = {7.0};
        static const double options_4[AROONOSC_OPTIONS] = {10.0};
        // simd_options is indexed by option set (the N=4 lanes), each lane
        // pointing at AROONOSC_OPTIONS values.
        const double *const simd_options[4] = {options_1, options_2, options_3, options_4};

        CSimdResult r = aroonosc_simd_by_options(
            expanded_inputs, EXPANDED_LEN, simd_options, 4, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "aroonosc_simd_by_options failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            char label[32];
            snprintf(label, sizeof(label), "option set %zu", i + 1);
            print_row_head(label, r.outputs[i][0], r.output_lens[i][0], 5);
        }

        printf("\nVerification - calculating each option set individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = aroonosc_indicator(
                expanded_inputs, EXPANDED_LEN, simd_options[i], NULL, 0);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "aroonosc_indicator (option set %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            printf("  Option set %zu: %s\n", i + 1, match ? "MATCH" : "MISMATCH");
            if (!match) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            aroonosc_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) aroonosc_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-options equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    return 0;
}
