// BBands (Bollinger Bands) example for tulip_rs_ffi.
// Mirrors tulip_rs_python/examples/ti_bbands_example.py: same sample data,
// same options, same "compute partial, continue via batch, verify against a
// full recompute" flow, plus SIMD by-assets/by-options demonstrations.
//
// BBANDS_INPUTS/BBANDS_OPTIONS come from tulip_rs_ffi_counts.h, generated by
// ../build.rs from the real tulip_rs::indicators::bbands::{INPUTS, OPTIONS}
// constants (run `cargo build` at least once so that file exists/is current).
//
// Build:
//   cc -O2 -o bbands_example examples/bbands_example.c \
//       -L target/release -ltulip_rs_ffi -Wl,-rpath,target/release
// Run:
//   ./bbands_example

#include <stdio.h>
#include <stdlib.h>

#include "../include/tulip_rs_ffi.h"

static const double close[] = {81.59, 81.06, 82.87, 83.00, 83.61, 83.15, 82.84, 83.99, 84.55, 84.36, 85.53, 86.54, 86.89, 87.77, 87.29};

#define TOTAL 15
#define PARTIAL (TOTAL - 5)
#define REST (TOTAL - PARTIAL)

static void print_row(const char *label, const double *row, size_t len) {
    printf("  %-14s: [", label);
    for (size_t i = 0; i < len; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < len) printf(", ");
    }
    printf("]\n");
}

static void print_row_head(const char *label, const double *row, size_t len, size_t max_print) {
    printf("  %-14s: [", label);
    size_t n = len < max_print ? len : max_print;
    for (size_t i = 0; i < n; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < n) printf(", ");
    }
    printf(len > max_print ? ", ...]\n" : "]\n");
}

static int allclose(const double *a, const double *b, size_t len) {
    for (size_t i = 0; i < len; i++) {
        double diff = a[i] - b[i];
        if (diff < 0) diff = -diff;
        if (diff > 1e-9) return 0;
    }
    return 1;
}

int main(void) {
    const double options[BBANDS_OPTIONS] = {5.0, 2.0}; // period, std_dev
    double full_lower[TOTAL];
    double full_middle[TOTAL];
    double full_upper[TOTAL];
    size_t full_len = 0;

    printf("BBands takes %d input series (real) and %d options"
           " (period, std_dev)\n",
           BBANDS_INPUTS, BBANDS_OPTIONS);

    printf("\n=== BBands: full calculation (all optional outputs) ===\n");
    {
        const double *inputs[BBANDS_INPUTS] = {close};
        bool optional_outputs[0] = {}; // no optional outputs

        CIndicatorResult r = bbands_indicator(inputs, TOTAL, options, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "bbands_indicator failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_outputs=%zu\n", r.num_outputs);
        print_row("lower_band", r.outputs[0], r.output_lens[0]);
        print_row("middle_band", r.outputs[1], r.output_lens[1]);
        print_row("upper_band", r.outputs[2], r.output_lens[2]);

        full_len = r.output_lens[0];
        for (size_t i = 0; i < full_len; i++) {
            full_lower[i] = r.outputs[0][i];
            full_middle[i] = r.outputs[1][i];
            full_upper[i] = r.outputs[2][i];
        }

        void *unused_state = r.state;
        tulip_ffi_result_free(r);
        bbands_state_free(unused_state);
    }

    printf("\n=== BBands: partial calculation + batch continuation ===\n");
    {
        const double *partial_inputs[BBANDS_INPUTS] = {close};
        CIndicatorResult pr = bbands_indicator(partial_inputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "bbands_indicator (partial) failed: error=%d\n", pr.error);
            return 1;
        }
        print_row("lower_band (partial)", pr.outputs[0], pr.output_lens[0]);
        print_row("middle_band (partial)", pr.outputs[1], pr.output_lens[1]);
        print_row("upper_band (partial)", pr.outputs[2], pr.output_lens[2]);
        void *state = pr.state;
        tulip_ffi_result_free(pr); // outputs freed; state kept alive

        const double *rest_inputs[BBANDS_INPUTS] = {close + PARTIAL};
        CBatchResult br = bbands_batch(state, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "bbands_batch failed: error=%d\n", br.error);
            return 1;
        }
        print_row("lower_band (continued)", br.outputs[0], br.output_lens[0]);
        print_row("middle_band (continued)", br.outputs[1], br.output_lens[1]);
        print_row("upper_band (continued)", br.outputs[2], br.output_lens[2]);

        printf("\n=== Verification: partial+continued vs. full recompute ===\n");
        int ok = 1;
        size_t continued_len = br.output_lens[0];
        size_t tail_start = full_len - continued_len;
        for (size_t i = 0; i < continued_len; i++) {
            double diff_lower = full_lower[tail_start + i] - br.outputs[0][i];
            if (diff_lower < 0) diff_lower = -diff_lower;
            double diff_middle = full_middle[tail_start + i] - br.outputs[1][i];
            if (diff_middle < 0) diff_middle = -diff_middle;
            double diff_upper = full_upper[tail_start + i] - br.outputs[2][i];
            if (diff_upper < 0) diff_upper = -diff_upper;
            if (diff_lower > 1e-9 || diff_middle > 1e-9 || diff_upper > 1e-9) {
                ok = 0;
                printf("  mismatch at %zu: lower_full=%.6f continued=%.6f middle_full=%.6f continued=%.6f upper_full=%.6f continued=%.6f\n",
                       i, full_lower[tail_start + i], br.outputs[0][i],
                       full_middle[tail_start + i], br.outputs[1][i],
                       full_upper[tail_start + i], br.outputs[2][i]);
            }
        }
        printf(ok ? "  MATCH: partial+continued BBands equals full recompute\n"
                  : "  MISMATCH detected!\n");

        tulip_ffi_batch_result_free(br);
        bbands_state_free(state);
    }

    printf("\n=== BBands: SIMD by assets (N=4) ===\n");
    {
        // Asset 1: original data.
        const double *const asset1[BBANDS_INPUTS] = {close};

        // Asset 2: scaled up (+20%).
        double close_2[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) close_2[i] = close[i] * 1.2;
        const double *const asset2[BBANDS_INPUTS] = {close_2};

        // Asset 3: different upward trend.
        double close_3[TOTAL];
        for (size_t i = 0; i < TOTAL; i++)
            close_3[i] = 90.0 + (double)i * 0.5 + close[i] * 0.1;
        const double *const asset3[BBANDS_INPUTS] = {close_3};

        // Asset 4: downward trend.
        double close_4[TOTAL];
        for (size_t i = 0; i < TOTAL; i++)
            close_4[i] = 100.0 - (double)i * 0.3 + close[i] * 0.05;
        const double *const asset4[BBANDS_INPUTS] = {close_4};

        // simd_inputs is indexed by asset (the N=4 SIMD lanes), NOT by input
        // series -- hence [4] here stays a lane count.
        const double *const *const simd_inputs[4] = {asset1, asset2, asset3, asset4};
        bool optional_outputs[0] = {};

        CSimdResult r = bbands_simd_by_assets(simd_inputs, 4, TOTAL, options, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "bbands_simd_by_assets failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            printf("Asset %zu\n", i + 1);
            print_row("lower_band", r.outputs[i][0], r.output_lens[i][0]);
            print_row("middle_band", r.outputs[i][1], r.output_lens[i][1]);
            print_row("upper_band", r.outputs[i][2], r.output_lens[i][2]);
        }

        printf("\nVerification - calculating each asset individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = bbands_indicator(
                simd_inputs[i], TOTAL, options, NULL, 0);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "bbands_indicator (asset %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match_lower = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            int match_middle = allclose(r.outputs[i][1], ind.outputs[1], r.output_lens[i][1]);
            int match_upper = allclose(r.outputs[i][2], ind.outputs[2], r.output_lens[i][2]);
            printf("  Asset %zu: lower=%s middle=%s upper=%s\n", i + 1,
                   match_lower ? "MATCH" : "MISMATCH",
                   match_middle ? "MATCH" : "MISMATCH",
                   match_upper ? "MATCH" : "MISMATCH");
            if (!match_lower || !match_middle || !match_upper) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            bbands_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) bbands_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-assets equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    printf("\n=== BBands: SIMD by options (N=4) ===\n");
    {
        // Tile the base series 20x so longer-period option sets have enough data.
        #define EXPANDED_LEN (TOTAL * 20)
        static double close_expanded[EXPANDED_LEN];
        for (size_t i = 0; i < 20; i++) {
            for (size_t j = 0; j < TOTAL; j++) {
                close_expanded[i * TOTAL + j] = close[j];
            }
        }
        const double *expanded_inputs[BBANDS_INPUTS] = {close_expanded};

        static const double options_1[BBANDS_OPTIONS] = {3.0, 1.0};
        static const double options_2[BBANDS_OPTIONS] = {5.0, 2.0};
        static const double options_3[BBANDS_OPTIONS] = {7.0, 3.0};
        static const double options_4[BBANDS_OPTIONS] = {10.0, 4.0};
        // simd_options is indexed by option set (the N=4 lanes), each lane
        // pointing at BBANDS_OPTIONS values.
        const double *const simd_options[4] = {options_1, options_2, options_3, options_4};

        CSimdResult r = bbands_simd_by_options(
            expanded_inputs, EXPANDED_LEN, simd_options, 4, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "bbands_simd_by_options failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            char label[32];
            snprintf(label, sizeof(label), "option set %zu", i + 1);
            print_row_head(label, r.outputs[i][0], r.output_lens[i][0], 5);
        }

        printf("\nVerification - calculating each option set individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = bbands_indicator(
                expanded_inputs, EXPANDED_LEN, simd_options[i], NULL, 0);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "bbands_indicator (option set %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match_lower = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            int match_middle = allclose(r.outputs[i][1], ind.outputs[1], r.output_lens[i][1]);
            int match_upper = allclose(r.outputs[i][2], ind.outputs[2], r.output_lens[i][2]);
            printf("  Option set %zu: lower=%s middle=%s upper=%s\n", i + 1,
                   match_lower ? "MATCH" : "MISMATCH",
                   match_middle ? "MATCH" : "MISMATCH",
                   match_upper ? "MATCH" : "MISMATCH");
            if (!match_lower || !match_middle || !match_upper) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            bbands_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) bbands_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-options equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    return 0;
}
