// BOP (Balance of Power) example for tulip_rs_ffi.
// Mirrors tulip_rs_python/examples/ti_bop_example.py: same sample data,
// same options, same "compute partial, continue via batch, verify against a
// full recompute" flow, plus SIMD by-assets demonstrations.
//
// NOTE: BOP has 0 options and does NOT support SIMD-by-options (see header docs).
// Thus this example only includes SIMD-by-assets section.
//
// BOP_INPUTS/BOP_OPTIONS come from tulip_rs_ffi_counts.h, generated by
// ../build.rs from the real tulip_rs::indicators::bop::{INPUTS, OPTIONS}
// constants (run `cargo build` at least once so that file exists/is current).
//
// Build:
//   cc -O2 -o bop_example examples/bop_example.c \
//       -L target/release -ltulip_rs_ffi -Wl,-rpath,target/release
// Run:
//   ./bop_example

#include <stdio.h>
#include <stdlib.h>

#include "../include/tulip_rs_ffi.h"

static const double open[] = {81.85, 81.20, 81.55, 82.91, 83.10, 83.41, 82.71, 82.70, 84.20, 84.25, 84.03, 85.45, 86.18, 88.00, 87.60};
static const double high[] = {82.15, 81.89, 83.03, 83.30, 83.85, 83.90, 83.33, 84.30, 84.84, 85.00, 85.90, 86.58, 86.98, 88.00, 87.87};
static const double low[] = {81.29, 80.64, 81.31, 82.65, 83.07, 83.11, 82.49, 82.30, 84.15, 84.11, 84.03, 85.39, 85.76, 87.17, 87.01};
static const double close[] = {81.59, 81.06, 82.87, 83.00, 83.61, 83.15, 82.84, 83.99, 84.55, 84.36, 85.53, 86.54, 86.89, 87.77, 87.29};

#define TOTAL 15
#define PARTIAL (TOTAL - 5)
#define REST (TOTAL - PARTIAL)

static void print_row(const char *label, const double *row, size_t len) {
    printf("  %-14s: [", label);
    for (size_t i = 0; i < len; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < len) printf(", ");
    }
    printf("]\n");
}

static void print_row_head(const char *label, const double *row, size_t len, size_t max_print) {
    printf("  %-14s: [", label);
    size_t n = len < max_print ? len : max_print;
    for (size_t i = 0; i < n; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < n) printf(", ");
    }
    printf(len > max_print ? ", ...]\n" : "]\n");
}

static int allclose(const double *a, const double *b, size_t len) {
    for (size_t i = 0; i < len; i++) {
        double diff = a[i] - b[i];
        if (diff < 0) diff = -diff;
        if (diff > 1e-9) return 0;
    }
    return 1;
}

int main(void) {
    printf("BOP takes %d input series (open, high, low, close) and %d options"
           " (none)\n",
           BOP_INPUTS, BOP_OPTIONS);

    printf("\n=== BOP: full calculation (all optional outputs) ===\n");
    {
        const double *inputs[BOP_INPUTS] = {open, high, low, close};
        bool optional_outputs[0] = {}; // no optional outputs

        CIndicatorResult r = bop_indicator(inputs, TOTAL, NULL, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "bop_indicator failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_outputs=%zu\n", r.num_outputs);
        print_row("bop_line", r.outputs[0], r.output_lens[0]);

        void *unused_state = r.state;
        tulip_ffi_result_free(r);
        bop_state_free(unused_state);
    }

    printf("\n=== BOP: partial calculation + batch continuation ===\n");
    {
        const double *partial_inputs[BOP_INPUTS] = {open, high, low, close};
        CIndicatorResult pr = bop_indicator(partial_inputs, PARTIAL, NULL, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "bop_indicator (partial) failed: error=%d\n", pr.error);
            return 1;
        }
        print_row("bop_line (partial)", pr.outputs[0], pr.output_lens[0]);
        void *state = pr.state;
        tulip_ffi_result_free(pr); // outputs freed; state kept alive

        const double *rest_inputs[BOP_INPUTS] = {open + PARTIAL, high + PARTIAL, low + PARTIAL, close + PARTIAL};
        CBatchResult br = bop_batch(state, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "bop_batch failed: error=%d\n", br.error);
            return 1;
        }
        print_row("bop_line (continued)", br.outputs[0], br.output_lens[0]);

        printf("\n=== Verification: partial+continued vs. full recompute ===\n");
        int ok = 1;
        size_t continued_len = br.output_lens[0];
        // Recompute full to verify properly
        {
            const double *full_inputs[BOP_INPUTS] = {open, high, low, close};
            CIndicatorResult fr = bop_indicator(full_inputs, TOTAL, NULL, NULL, 0);
            if (fr.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "bop_indicator (full recompute) failed: error=%d\n", fr.error);
                return 1;
            }
            size_t full_len = fr.output_lens[0];
            size_t tail_start = full_len - continued_len;
            for (size_t i = 0; i < continued_len; i++) {
                double a = fr.outputs[0][tail_start + i];
                double b = br.outputs[0][i];
                double diff = a > b ? a - b : b - a;
                if (diff > 1e-9) {
                    ok = 0;
                    printf("  mismatch at %zu: full=%.6f continued=%.6f\n", i, a, b);
                }
            }
            void *fr_state = fr.state;
            tulip_ffi_result_free(fr);
            bop_state_free(fr_state);
        }
        printf(ok ? "  MATCH: partial+continued BOP equals full recompute\n"
                  : "  MISMATCH detected!\n");

        tulip_ffi_batch_result_free(br);
        bop_state_free(state);
    }

    printf("\n=== BOP: SIMD by assets (N=4) ===\n");
    {
        // Asset 1: original data.
        const double *const asset1[BOP_INPUTS] = {open, high, low, close};

        // Asset 2: scaled up (+20%).
        double open_2[TOTAL], high_2[TOTAL], low_2[TOTAL], close_2[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            open_2[i] = open[i] * 1.2;
            high_2[i] = high[i] * 1.2;
            low_2[i] = low[i] * 1.2;
            close_2[i] = close[i] * 1.2;
        }
        const double *const asset2[BOP_INPUTS] = {open_2, high_2, low_2, close_2};

        // Asset 3: different upward trend.
        double open_3[TOTAL], high_3[TOTAL], low_3[TOTAL], close_3[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            open_3[i] = 90.0 + (double)i * 0.5 + open[i] * 0.1;
            high_3[i] = 90.0 + (double)i * 0.5 + high[i] * 0.1;
            low_3[i] = 90.0 + (double)i * 0.5 + low[i] * 0.1;
            close_3[i] = 90.0 + (double)i * 0.5 + close[i] * 0.1;
        }
        const double *const asset3[BOP_INPUTS] = {open_3, high_3, low_3, close_3};

        // Asset 4: downward trend.
        double open_4[TOTAL], high_4[TOTAL], low_4[TOTAL], close_4[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            open_4[i] = 100.0 - (double)i * 0.3 + open[i] * 0.05;
            high_4[i] = 100.0 - (double)i * 0.3 + high[i] * 0.05;
            low_4[i] = 100.0 - (double)i * 0.3 + low[i] * 0.05;
            close_4[i] = 100.0 - (double)i * 0.3 + close[i] * 0.05;
        }
        const double *const asset4[BOP_INPUTS] = {open_4, high_4, low_4, close_4};

        // simd_inputs is indexed by asset (the N=4 SIMD lanes), NOT by input
        // series -- hence [4] here stays a lane count.
        const double *const *const simd_inputs[4] = {asset1, asset2, asset3, asset4};
        bool optional_outputs[0] = {};

        CSimdResult r = bop_simd_by_assets(simd_inputs, 4, TOTAL, NULL, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "bop_simd_by_assets failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            printf("Asset %zu ", i + 1);
            print_row("bop_line", r.outputs[i][0], r.output_lens[i][0]);
        }

        printf("\nVerification - calculating each asset individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = bop_indicator(
                simd_inputs[i], TOTAL, NULL, NULL, 0);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "bop_indicator (asset %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            printf("  Asset %zu: %s\n", i + 1, match ? "MATCH" : "MISMATCH");
            if (!match) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            bop_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) bop_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-assets equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    return 0;
}
