// CCFisher (Composite Cycle Fisher) example for tulip_rs_ffi.
// Mirrors tulip_rs_python/examples/ti_ccfisher_example.py: same sample data,
// same options, same "compute partial, continue via batch, verify against a
// full recompute" flow, plus SIMD by-assets/by-options demonstrations.
//
// CCFISHER_INPUTS/CCFISHER_OPTIONS come from tulip_rs_ffi_counts.h, generated by
// ../build.rs from the real tulip_rs::indicators::ccfisher::{INPUTS, OPTIONS}
// constants (run `cargo build` at least once so that file exists/is current).
//
// Build:
//   cc -O2 -o ccfisher_example examples/ccfisher_example.c \
//       -L target/release -ltulip_rs_ffi -Wl,-rpath,target/release
// Run:
//   ./ccfisher_example

#include <stdio.h>
#include <stdlib.h>

#include "../include/tulip_rs_ffi.h"

static const double close[] = {81.59, 81.06, 82.87, 83.00, 83.61, 83.15, 82.84, 83.99, 84.55, 84.36, 85.53, 86.54, 86.89, 87.77, 87.29, 87.50, 88.10, 88.50, 87.90, 88.20, 88.80, 89.10, 88.70, 89.30, 89.70, 90.10, 89.50, 90.20, 90.80, 91.10, 90.50, 91.20, 91.80, 92.10, 91.50, 92.20, 92.80, 93.10, 92.50, 93.20, 93.80, 94.10, 93.50, 94.20, 94.80, 95.10, 94.50, 95.20, 95.80, 96.10, 95.50, 96.20, 96.80, 97.10, 96.50, 97.20, 97.80, 98.10, 97.50, 98.20, 98.80, 99.10, 98.50, 99.20, 99.80, 100.10, 99.50, 100.20, 100.80, 101.10, 100.50, 101.20, 101.80, 102.10, 101.50, 102.20, 102.80, 103.10, 102.50, 103.20};

#define TOTAL 70
#define PARTIAL (TOTAL - 5)
#define REST (TOTAL - PARTIAL)

static void print_row(const char *label, const double *row, size_t len) {
    printf("  %-14s: [", label);
    for (size_t i = 0; i < len; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < len) printf(", ");
    }
    printf("]\n");
}

static void print_row_head(const char *label, const double *row, size_t len, size_t max_print) {
    printf("  %-14s: [", label);
    size_t n = len < max_print ? len : max_print;
    for (size_t i = 0; i < n; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < n) printf(", ");
    }
    printf(len > max_print ? ", ...]\n" : "]\n");
}

static int allclose(const double *a, const double *b, size_t len) {
    for (size_t i = 0; i < len; i++) {
        double diff = a[i] - b[i];
        if (diff < 0) diff = -diff;
        if (diff > 1e-9) return 0;
    }
    return 1;
}

int main(void) {
    const double options[CCFISHER_OPTIONS] = {0.0}; // alpha=0.0 for adaptive mode
    double full_fisher[TOTAL];
    double full_signal[TOTAL];
    size_t full_len = 0;

    printf("CC Fisher takes %d input series (real) and %d options"
           " (alpha)\n",
           CCFISHER_INPUTS, CCFISHER_OPTIONS);

    bool optional_outputs_full[3] = {true, true, true}; // trendmode, cycle, peak

    printf("\n=== CC Fisher: full calculation (all optional outputs) ===\n");
    {
        const double *inputs[CCFISHER_INPUTS] = {close};

        CIndicatorResult r = ccfisher_indicator(inputs, TOTAL, options, optional_outputs_full, 3);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "ccfisher_indicator failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_outputs=%zu\n", r.num_outputs);
        print_row("fisher", r.outputs[0], r.output_lens[0]);
        print_row("signal", r.outputs[1], r.output_lens[1]);
        print_row("trendmode", r.outputs[2], r.output_lens[2]);
        print_row("cycle", r.outputs[3], r.output_lens[3]);
        print_row("peak", r.outputs[4], r.output_lens[4]);

        full_len = r.output_lens[0];
        for (size_t i = 0; i < full_len; i++) {
            full_fisher[i] = r.outputs[0][i];
            full_signal[i] = r.outputs[1][i];
        }

        void *unused_state = r.state;
        tulip_ffi_result_free(r);
        ccfisher_state_free(unused_state);
    }

    printf("\n=== CC Fisher: partial calculation + batch continuation ===\n");
    {
        const double *partial_inputs[CCFISHER_INPUTS] = {close};
        CIndicatorResult pr = ccfisher_indicator(partial_inputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "ccfisher_indicator (partial) failed: error=%d\n", pr.error);
            return 1;
        }
        print_row("fisher (partial)", pr.outputs[0], pr.output_lens[0]);
        print_row("signal (partial)", pr.outputs[1], pr.output_lens[1]);
        void *state = pr.state;
        tulip_ffi_result_free(pr); // outputs freed; state kept alive

        const double *rest_inputs[CCFISHER_INPUTS] = {close + PARTIAL};
        CBatchResult br = ccfisher_batch(state, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "ccfisher_batch failed: error=%d\n", br.error);
            return 1;
        }
        print_row("fisher (continued)", br.outputs[0], br.output_lens[0]);
        print_row("signal (continued)", br.outputs[1], br.output_lens[1]);

        printf("\n=== Verification: partial+continued vs. full recompute ===\n");
        int ok = 1;
        size_t continued_len = br.output_lens[0];
        size_t tail_start = full_len - continued_len;
        for (size_t i = 0; i < continued_len; i++) {
            double diff_fisher = full_fisher[tail_start + i] - br.outputs[0][i];
            if (diff_fisher < 0) diff_fisher = -diff_fisher;
            double diff_signal = full_signal[tail_start + i] - br.outputs[1][i];
            if (diff_signal < 0) diff_signal = -diff_signal;
            if (diff_fisher > 1e-9 || diff_signal > 1e-9) {
                ok = 0;
                printf("  mismatch at %zu: fisher_full=%.6f continued=%.6f signal_full=%.6f continued=%.6f\n",
                       i, full_fisher[tail_start + i], br.outputs[0][i],
                       full_signal[tail_start + i], br.outputs[1][i]);
            }
        }
        printf(ok ? "  MATCH: partial+continued CC Fisher equals full recompute\n"
                  : "  MISMATCH detected!\n");

        tulip_ffi_batch_result_free(br);
        ccfisher_state_free(state);
    }
    printf("\n=== CCFISHER: state persistence (serialize / deserialize) ===\n");
    {
        const double *pinputs[CCFISHER_INPUTS] = {close};
        CIndicatorResult pr = ccfisher_indicator(pinputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) { fprintf(stderr, "ccfisher_indicator failed\n"); return 1; }
        void *st = pr.state;
        tulip_ffi_result_free(pr);

        CBytes blob = tulip_state_serialize(C_INDICATOR_ID_CCFISHER, C_STATE_FORMAT_BINCODE, st);
        if (blob.ptr == NULL) { fprintf(stderr, "serialize failed\n"); return 1; }
        printf("  blob: %zu bytes, magic=%.4s, name=%.32s\n",
               blob.len, (const char *)blob.ptr, (const char *)blob.ptr + 6);

        void *rs = tulip_state_deserialize(blob.ptr, blob.len);
        tulip_ffi_bytes_free(blob);
        if (rs == NULL) { fprintf(stderr, "deserialize failed\n"); return 1; }

        const double *rinputs[CCFISHER_INPUTS] = {close + PARTIAL};
        CBatchResult a = ccfisher_batch(st, rinputs, REST, NULL, 0);
        CBatchResult b = ccfisher_batch(rs, rinputs, REST, NULL, 0);
        int persist_ok = a.error == C_INDICATOR_ERROR_OK && b.error == C_INDICATOR_ERROR_OK &&
                         a.output_lens[0] == b.output_lens[0] &&
                         allclose(a.outputs[0], b.outputs[0], a.output_lens[0]);
        printf(persist_ok ? "  MATCH: deserialized state continues identically\n"
                          : "  MISMATCH detected!\n");
        tulip_ffi_batch_result_free(a);
        tulip_ffi_batch_result_free(b);
        ccfisher_state_free(st);
        ccfisher_state_free(rs);
    }


    printf("\n=== CC Fisher: SIMD by assets (N=4) ===\n");
    {
        // Asset 1: original data.
        const double *const asset1[CCFISHER_INPUTS] = {close};

        // Asset 2: scaled up (+20%).
        double close_2[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) close_2[i] = close[i] * 1.2;
        const double *const asset2[CCFISHER_INPUTS] = {close_2};

        // Asset 3: different upward trend.
        double close_3[TOTAL];
        for (size_t i = 0; i < TOTAL; i++)
            close_3[i] = 90.0 + (double)i * 0.5 + close[i] * 0.1;
        const double *const asset3[CCFISHER_INPUTS] = {close_3};

        // Asset 4: downward trend.
        double close_4[TOTAL];
        for (size_t i = 0; i < TOTAL; i++)
            close_4[i] = 100.0 - (double)i * 0.3 + close[i] * 0.05;
        const double *const asset4[CCFISHER_INPUTS] = {close_4};

        // simd_inputs is indexed by asset (the N=4 SIMD lanes), NOT by input
        // series -- hence [4] here stays a lane count.
        const double *const *const simd_inputs[4] = {asset1, asset2, asset3, asset4};

        CSimdResult r = ccfisher_simd_by_assets(simd_inputs, 4, TOTAL, options, optional_outputs_full, 3);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "ccfisher_simd_by_assets failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            printf("Asset %zu\n", i + 1);
            print_row("fisher", r.outputs[i][0], r.output_lens[i][0]);
            print_row("signal", r.outputs[i][1], r.output_lens[i][1]);
        }

        printf("\nVerification - calculating each asset individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = ccfisher_indicator(
                simd_inputs[i], TOTAL, options, optional_outputs_full, 3);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "ccfisher_indicator (asset %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match_fisher = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            int match_signal = allclose(r.outputs[i][1], ind.outputs[1], r.output_lens[i][1]);
            printf("  Asset %zu: fisher=%s signal=%s\n", i + 1,
                   match_fisher ? "MATCH" : "MISMATCH",
                   match_signal ? "MATCH" : "MISMATCH");
            if (!match_fisher || !match_signal) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            ccfisher_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) ccfisher_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-assets equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    printf("\n=== CC Fisher: SIMD by options (N=4) ===\n");
    {
        // Tile the base series 20x so longer-period option sets have enough data.
        #define EXPANDED_LEN (TOTAL * 20)
        static double close_expanded[EXPANDED_LEN];
        for (size_t i = 0; i < 20; i++) {
            for (size_t j = 0; j < TOTAL; j++) {
                close_expanded[i * TOTAL + j] = close[j];
            }
        }
        const double *expanded_inputs[CCFISHER_INPUTS] = {close_expanded};

        static const double options_1[CCFISHER_OPTIONS] = {0.0};
        static const double options_2[CCFISHER_OPTIONS] = {0.05};
        static const double options_3[CCFISHER_OPTIONS] = {0.07};
        static const double options_4[CCFISHER_OPTIONS] = {0.1};
        // simd_options is indexed by option set (the N=4 lanes), each lane
        // pointing at CCFISHER_OPTIONS values.
        const double *const simd_options[4] = {options_1, options_2, options_3, options_4};

        CSimdResult r = ccfisher_simd_by_options(
            expanded_inputs, EXPANDED_LEN, simd_options, 4, optional_outputs_full, 3);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "ccfisher_simd_by_options failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            char label[32];
            snprintf(label, sizeof(label), "option set %zu", i + 1);
            print_row_head(label, r.outputs[i][0], r.output_lens[i][0], 5);
        }

        printf("\nVerification - calculating each option set individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = ccfisher_indicator(
                expanded_inputs, EXPANDED_LEN, simd_options[i], optional_outputs_full, 3);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "ccfisher_indicator (option set %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match_fisher = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            int match_signal = allclose(r.outputs[i][1], ind.outputs[1], r.output_lens[i][1]);
            printf("  Option set %zu: fisher=%s signal=%s\n", i + 1,
                   match_fisher ? "MATCH" : "MISMATCH",
                   match_signal ? "MATCH" : "MISMATCH");
            if (!match_fisher || !match_signal) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            ccfisher_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) ccfisher_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-options equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    return 0;
}
