// DonchianChannel (Donchian Channel) example for tulip_rs_ffi.
// Mirrors tulip_rs_python/examples/ti_donchianchannel_example.py: same sample data,
// same options, same "compute partial, continue via batch, verify against a
// full recompute" flow, plus SIMD by-assets/by-options demonstrations.
//
// DonchianChannel_INPUTS/DonchianChannel_OPTIONS come from ../include/tulip_rs_ffi_counts.h,
// generated by ../build.rs from the real tulip_rs::indicators::donchianchannel::{INPUTS, OPTIONS}
// constants (run `cargo build` at least once so that file exists/is current).
// The main header is the cbindgen-generated one in ../include/, which is the
// up-to-date API surface.
//
// Build (from the tulip_rs_ffi directory):
//   cc -O2 -o donchianchannel_example examples/donchianchannel_example.c \
//       -L target/release -ltulip_rs_ffi -Wl,-rpath,target/release
// Run:
//   ./donchianchannel_example

#include <stdio.h>
#include <stdlib.h>

#include "../include/tulip_rs_ffi.h"

static const double high[] = {82.15, 81.89, 83.03, 83.30, 83.85, 83.90, 83.33, 84.30, 84.84, 85.00, 85.90, 86.58, 86.98, 88.00, 87.87};
static const double low[]  = {81.29, 80.64, 81.31, 82.65, 83.07, 83.11, 82.49, 82.30, 84.15, 84.11, 84.03, 85.39, 85.76, 87.17, 87.01};

#define TOTAL 15
#define PARTIAL (TOTAL - 5)
#define REST (TOTAL - PARTIAL)

static void print_row(const char *label, const double *row, size_t len) {
    printf("  %-20s: [", label);
    for (size_t i = 0; i < len; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < len) printf(", ");
    }
    printf("]\n");
}

static void print_row_head(const char *label, const double *row, size_t len, size_t max_print) {
    printf("  %-20s: [", label);
    size_t n = len < max_print ? len : max_print;
    for (size_t i = 0; i < n; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < n) printf(", ");
    }
    printf(len > max_print ? ", ...]\n" : "]\n");
}

static int allclose(const double *a, const double *b, size_t len) {
    for (size_t i = 0; i < len; i++) {
        double diff = a[i] - b[i];
        if (diff < 0) diff = -diff;
        if (diff > 1e-9) return 0;
    }
    return 1;
}

int main(void) {
    const double options[DONCHIANCHANNEL_OPTIONS] = {5.0}; // period
    double full_lower[TOTAL];
    double full_middle[TOTAL];
    double full_upper[TOTAL];
    size_t full_len = 0;

    CIndicatorInfo info = donchianchannel_info();
    printf("=== %s (%s) ===\n", info.name, info.full_name);
    printf("Inputs: %u (high, low), Options: %u (period)\n",
           (unsigned)DONCHIANCHANNEL_INPUTS, (unsigned)DONCHIANCHANNEL_OPTIONS);
    printf("Optional outputs: %u\n", (unsigned)info.optional_outputs.len);
    printf("Minimum data required: %zu\n", donchianchannel_min_data(options));

    printf("\n=== DonchianChannel: full calculation ===\n");
    {
        const double *inputs[DONCHIANCHANNEL_INPUTS] = {high, low};

        CIndicatorResult r = donchianchannel_indicator(inputs, TOTAL, options, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "donchianchannel_indicator failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_outputs=%zu\n", r.num_outputs);
        print_row("lower", r.outputs[0], r.output_lens[0]);
        print_row("middle", r.outputs[1], r.output_lens[1]);
        print_row("upper", r.outputs[2], r.output_lens[2]);

        full_len = r.output_lens[0];
        for (size_t i = 0; i < full_len; i++) {
            full_lower[i] = r.outputs[0][i];
            full_middle[i] = r.outputs[1][i];
            full_upper[i] = r.outputs[2][i];
        }

        void *unused_state = r.state;
        tulip_ffi_result_free(r);
        donchianchannel_state_free(unused_state);
    }

    printf("\n=== DonchianChannel: partial calculation + batch continuation ===\n");
    {
        const double *partial_inputs[DONCHIANCHANNEL_INPUTS] = {high, low};
        CIndicatorResult pr = donchianchannel_indicator(partial_inputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "donchianchannel_indicator (partial) failed: error=%d\n", pr.error);
            return 1;
        }
        print_row("lower (partial)", pr.outputs[0], pr.output_lens[0]);
        print_row("middle (partial)", pr.outputs[1], pr.output_lens[1]);
        print_row("upper (partial)", pr.outputs[2], pr.output_lens[2]);
        void *state = pr.state;
        tulip_ffi_result_free(pr); // outputs freed; state kept alive

        const double *rest_inputs[DONCHIANCHANNEL_INPUTS] = {high + PARTIAL, low + PARTIAL};
        CBatchResult br = donchianchannel_batch(state, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "donchianchannel_batch failed: error=%d\n", br.error);
            return 1;
        }
        print_row("lower (continued)", br.outputs[0], br.output_lens[0]);
        print_row("middle (continued)", br.outputs[1], br.output_lens[1]);
        print_row("upper (continued)", br.outputs[2], br.output_lens[2]);

        printf("\n=== Verification: partial+continued vs. full recompute ===\n");
        int ok = 1;
        size_t continued_len = br.output_lens[0];
        size_t tail_start = full_len - continued_len;
        for (size_t i = 0; i < continued_len; i++) {
            double a_lower = full_lower[tail_start + i];
            double b_lower = br.outputs[0][i];
            double diff_lower = a_lower > b_lower ? a_lower - b_lower : b_lower - a_lower;
            if (diff_lower > 1e-9) {
                ok = 0;
                printf("  lower mismatch at %zu: full=%.6f continued=%.6f\n", i, a_lower, b_lower);
            }
            double a_middle = full_middle[tail_start + i];
            double b_middle = br.outputs[1][i];
            double diff_middle = a_middle > b_middle ? a_middle - b_middle : b_middle - a_middle;
            if (diff_middle > 1e-9) {
                ok = 0;
                printf("  middle mismatch at %zu: full=%.6f continued=%.6f\n", i, a_middle, b_middle);
            }
            double a_upper = full_upper[tail_start + i];
            double b_upper = br.outputs[2][i];
            double diff_upper = a_upper > b_upper ? a_upper - b_upper : b_upper - a_upper;
            if (diff_upper > 1e-9) {
                ok = 0;
                printf("  upper mismatch at %zu: full=%.6f continued=%.6f\n", i, a_upper, b_upper);
            }
        }
        printf(ok ? "  MATCH: partial+continued DonchianChannel equals full recompute\n"
                  : "  MISMATCH detected!\n");

        tulip_ffi_batch_result_free(br);
        donchianchannel_state_free(state);
    }

    printf("\n=== DonchianChannel: SIMD by assets (N=4) ===\n");
    {
        // Asset 1: original data.
        const double *const asset1[DONCHIANCHANNEL_INPUTS] = {high, low};

        // Asset 2: scaled up (+20%).
        double high_2[TOTAL], low_2[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_2[i] = high[i] * 1.2;
            low_2[i] = low[i] * 1.2;
        }
        const double *const asset2[DONCHIANCHANNEL_INPUTS] = {high_2, low_2};

        // Asset 3: different upward trend.
        double high_3[TOTAL], low_3[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_3[i] = 90.0 + (double)i * 0.5 + high[i] * 0.1;
            low_3[i] = 90.0 + (double)i * 0.5 + low[i] * 0.1;
        }
        const double *const asset3[DONCHIANCHANNEL_INPUTS] = {high_3, low_3};

        // Asset 4: downward trend.
        double high_4[TOTAL], low_4[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_4[i] = 100.0 - (double)i * 0.3 + high[i] * 0.05;
            low_4[i] = 100.0 - (double)i * 0.3 + low[i] * 0.05;
        }
        const double *const asset4[DONCHIANCHANNEL_INPUTS] = {high_4, low_4};

        // simd_inputs is indexed by asset (the N=4 SIMD lanes), NOT by input
        // series -- hence [4] here stays a lane count.
        const double *const *const simd_inputs[4] = {asset1, asset2, asset3, asset4};

        CSimdResult r = donchianchannel_simd_by_assets(simd_inputs, 4, TOTAL, options, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "donchianchannel_simd_by_assets failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            printf("Asset %zu\n", i + 1);
            print_row("lower", r.outputs[i][0], r.output_lens[i][0]);
            print_row("middle", r.outputs[i][1], r.output_lens[i][1]);
            print_row("upper", r.outputs[i][2], r.output_lens[i][2]);
        }

        printf("\nVerification - calculating each asset individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = donchianchannel_indicator(
                simd_inputs[i], TOTAL, options, NULL, 0);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "donchianchannel_indicator (asset %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match_lower = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            int match_middle = allclose(r.outputs[i][1], ind.outputs[1], r.output_lens[i][1]);
            int match_upper = allclose(r.outputs[i][2], ind.outputs[2], r.output_lens[i][2]);
            printf("  Asset %zu lower: %s, middle: %s, upper: %s\n", i + 1,
                   match_lower ? "MATCH" : "MISMATCH",
                   match_middle ? "MATCH" : "MISMATCH",
                   match_upper ? "MATCH" : "MISMATCH");
            if (!match_lower || !match_middle || !match_upper) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            donchianchannel_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) donchianchannel_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-assets equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    printf("\n=== DonchianChannel: SIMD by options (N=4) ===\n");
    {
        // Tile the base series 20x so longer-period option sets have enough data.
        #define EXPANDED_LEN (TOTAL * 20)
        static double high_expanded[EXPANDED_LEN];
        static double low_expanded[EXPANDED_LEN];
        for (size_t i = 0; i < 20; i++) {
            for (size_t j = 0; j < TOTAL; j++) {
                high_expanded[i * TOTAL + j] = high[j];
                low_expanded[i * TOTAL + j] = low[j];
            }
        }
        const double *expanded_inputs[DONCHIANCHANNEL_INPUTS] = {high_expanded, low_expanded};

        static const double options_1[DONCHIANCHANNEL_OPTIONS] = {5.0};
        static const double options_2[DONCHIANCHANNEL_OPTIONS] = {7.0};
        static const double options_3[DONCHIANCHANNEL_OPTIONS] = {9.0};
        static const double options_4[DONCHIANCHANNEL_OPTIONS] = {12.0};
        // simd_options is indexed by option set (the N=4 lanes), each lane
        // pointing at DONCHIANCHANNEL_OPTIONS values.
        const double *const simd_options[4] = {options_1, options_2, options_3, options_4};

        CSimdResult r = donchianchannel_simd_by_options(
            expanded_inputs, EXPANDED_LEN, simd_options, 4, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "donchianchannel_simd_by_options failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            char label[32];
            snprintf(label, sizeof(label), "option set %zu", i + 1);
            print_row_head(label, r.outputs[i][0], r.output_lens[i][0], 5);
        }

        printf("\nVerification - calculating each option set individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = donchianchannel_indicator(
                expanded_inputs, EXPANDED_LEN, simd_options[i], NULL, 0);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "donchianchannel_indicator (option set %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match_lower = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            int match_middle = allclose(r.outputs[i][1], ind.outputs[1], r.output_lens[i][1]);
            int match_upper = allclose(r.outputs[i][2], ind.outputs[2], r.output_lens[i][2]);
            printf("  Option set %zu lower: %s, middle: %s, upper: %s\n", i + 1,
                   match_lower ? "MATCH" : "MISMATCH",
                   match_middle ? "MATCH" : "MISMATCH",
                   match_upper ? "MATCH" : "MISMATCH");
            if (!match_lower || !match_middle || !match_upper) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            donchianchannel_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) donchianchannel_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-options equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    return 0;
}
