// HILBERTTRANSFORM (Hilbert Transform) example for tulip_rs_ffi.
// Mirrors tulip_rs_python/examples/ti_hilberttransform_example.py: same sample data,
// same options, same "compute partial, continue via batch, verify against a
// full recompute" flow, plus SIMD by-assets/by-options demonstrations.
//
// HILBERTTRANSFORM_INPUTS/HILBERTTRANSFORM_OPTIONS come from ../include/tulip_rs_ffi_counts.h,
// generated by ../build.rs from the real tulip_rs::indicators::hilberttransform::
// {INPUTS, OPTIONS} constants (run `cargo build` at least once so that file
// exists/is current). The main header is the cbindgen-generated one in
// ../include/, which is the up-to-date API surface.
//
// Build (from the tulip_rs_ffi directory):
//   cc -O2 -o hilberttransform_example examples/hilberttransform_example.c \
//       -L target/release -ltulip_rs_ffi -Wl,-rpath,target/release
// Run:
//   ./hilberttransform_example

#include <stdio.h>
#include <stdlib.h>

#include "../include/tulip_rs_ffi.h"

static const double close[] = {81.59, 81.06, 82.87, 83.00, 83.61, 83.15, 82.84, 83.99, 84.55, 84.36, 85.53, 86.54, 86.89, 87.77, 87.29,
                               87.50, 88.10, 88.50, 87.90, 88.20, 88.80, 89.10, 88.70, 89.30, 89.70,
                               90.10, 89.50, 90.20, 90.80, 91.10, 90.50, 91.20, 91.80, 92.10, 91.50,
                               92.20, 92.80, 93.10, 92.50, 93.20};

#define TOTAL 40
#define PARTIAL (TOTAL - 5)
#define REST (TOTAL - PARTIAL)

static void print_row(const char *label, const double *row, size_t len) {
    printf("  %-14s: [", label);
    for (size_t i = 0; i < len; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < len) printf(", ");
    }
    printf("]\n");
}

static void print_row_head(const char *label, const double *row, size_t len, size_t max_print) {
    printf("  %-14s: [", label);
    size_t n = len < max_print ? len : max_print;
    for (size_t i = 0; i < n; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < n) printf(", ");
    }
    printf(len > max_print ? ", ...]\n" : "]\n");
}

static int allclose(const double *a, const double *b, size_t len) {
    for (size_t i = 0; i < len; i++) {
        double diff = a[i] - b[i];
        if (diff < 0) diff = -diff;
        if (diff > 1e-9) return 0;
    }
    return 1;
}

int main(void) {
    const double options[HILBERTTRANSFORM_OPTIONS] = {10.0, 20.0}; // ss_period, hp_period
    double full_in_phase[TOTAL];
    double full_quadrature[TOTAL];
    size_t full_len = 0;

    CIndicatorInfo info = hilberttransform_info();
    printf("=== %s (%s) ===\n", info.name, info.full_name);
    printf("Inputs: %u, Options: %u (ss_period, hp_period), Optional outputs: %u\n",
           (unsigned)HILBERTTRANSFORM_INPUTS, (unsigned)HILBERTTRANSFORM_OPTIONS,
           (unsigned)info.optional_outputs.len);
    printf("Minimum data required: %zu\n", hilberttransform_min_data(options));

    printf("\n=== HILBERTTRANSFORM: full calculation (all optional outputs) ===\n");
    {
        const double *inputs[HILBERTTRANSFORM_INPUTS] = {close};
        bool optional_outputs[2] = {true, true}; // roofing, highpass

        CIndicatorResult r = hilberttransform_indicator(inputs, TOTAL, options, optional_outputs, 2);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "hilberttransform_indicator failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_outputs=%zu\n", r.num_outputs);
        print_row("in_phase", r.outputs[0], r.output_lens[0]);
        print_row("quadrature", r.outputs[1], r.output_lens[1]);
        print_row("roofing (optional)", r.outputs[2], r.output_lens[2]);
        print_row("highpass (optional)", r.outputs[3], r.output_lens[3]);

        // Keep copies of the mandatory outputs for later verification.
        full_len = r.output_lens[0];
        for (size_t i = 0; i < full_len; i++) {
            full_in_phase[i] = r.outputs[0][i];
            full_quadrature[i] = r.outputs[1][i];
        }

        void *unused_state = r.state;
        tulip_ffi_result_free(r);
        hilberttransform_state_free(unused_state);
    }

    printf("\n=== HILBERTTRANSFORM: partial calculation + batch continuation ===\n");
    {
        const double *partial_inputs[HILBERTTRANSFORM_INPUTS] = {close};
        CIndicatorResult pr = hilberttransform_indicator(partial_inputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "hilberttransform_indicator (partial) failed: error=%d\n", pr.error);
            return 1;
        }
        print_row("in_phase (partial)", pr.outputs[0], pr.output_lens[0]);
        print_row("quadrature (partial)", pr.outputs[1], pr.output_lens[1]);
        void *state = pr.state;
        tulip_ffi_result_free(pr); // outputs freed; state kept alive

        const double *rest_inputs[HILBERTTRANSFORM_INPUTS] = {close + PARTIAL};
        CBatchResult br = hilberttransform_batch(state, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "hilberttransform_batch failed: error=%d\n", br.error);
            return 1;
        }
        print_row("in_phase (continued)", br.outputs[0], br.output_lens[0]);
        print_row("quadrature (continued)", br.outputs[1], br.output_lens[1]);

        printf("\n=== Verification: partial+continued vs. full recompute ===\n");
        int ok = 1;
        size_t continued_len = br.output_lens[0];
        size_t tail_start = full_len - continued_len;
        for (size_t i = 0; i < continued_len; i++) {
            double a_ip = full_in_phase[tail_start + i];
            double b_ip = br.outputs[0][i];
            double diff_ip = a_ip > b_ip ? a_ip - b_ip : b_ip - a_ip;
            if (diff_ip > 1e-9) {
                ok = 0;
                printf("  in_phase mismatch at %zu: full=%.6f continued=%.6f\n", i, a_ip, b_ip);
            }
            double a_q = full_quadrature[tail_start + i];
            double b_q = br.outputs[1][i];
            double diff_q = a_q > b_q ? a_q - b_q : b_q - a_q;
            if (diff_q > 1e-9) {
                ok = 0;
                printf("  quadrature mismatch at %zu: full=%.6f continued=%.6f\n", i, a_q, b_q);
            }
        }
        printf(ok ? "  MATCH: partial+continued hilberttransform equals full recompute\n"
                  : "  MISMATCH detected!\n");

        tulip_ffi_batch_result_free(br);
        hilberttransform_state_free(state);
    }

    printf("\n=== HILBERTTRANSFORM: SIMD by assets (N=4) ===\n");
    {
        // Asset 1: original data.
        const double *const asset1[HILBERTTRANSFORM_INPUTS] = {close};

        // Asset 2: scaled up (+20%).
        double close_2[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) close_2[i] = close[i] * 1.2;
        const double *const asset2[HILBERTTRANSFORM_INPUTS] = {close_2};

        // Asset 3: different upward trend.
        double close_3[TOTAL];
        for (size_t i = 0; i < TOTAL; i++)
            close_3[i] = 90.0 + (double)i * 0.5 + close[i] * 0.1;
        const double *const asset3[HILBERTTRANSFORM_INPUTS] = {close_3};

        // Asset 4: downward trend.
        double close_4[TOTAL];
        for (size_t i = 0; i < TOTAL; i++)
            close_4[i] = 100.0 - (double)i * 0.3 + close[i] * 0.05;
        const double *const asset4[HILBERTTRANSFORM_INPUTS] = {close_4};

        // simd_inputs is indexed by asset (the N=4 SIMD lanes), NOT by input
        // series -- hence [4] here stays a lane count.
        const double *const *const simd_inputs[4] = {asset1, asset2, asset3, asset4};
        bool optional_outputs[2] = {true, true};

        CSimdResult r = hilberttransform_simd_by_assets(simd_inputs, 4, TOTAL, options, optional_outputs, 2);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "hilberttransform_simd_by_assets failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            printf("Asset %zu ", i + 1);
            print_row("in_phase", r.outputs[i][0], r.output_lens[i][0]);
        }

        printf("\nVerification - calculating each asset individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = hilberttransform_indicator(
                simd_inputs[i], TOTAL, options, optional_outputs, 2);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "hilberttransform_indicator (asset %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            printf("  Asset %zu in_phase: %s\n", i + 1, match ? "MATCH" : "MISMATCH");
            if (!match) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            hilberttransform_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) hilberttransform_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-assets equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    printf("\n=== HILBERTTRANSFORM: SIMD by options (N=4) ===\n");
    {
        // Tile the base series 10x so longer-period option sets have enough data.
        #define EXPANDED_LEN (TOTAL * 10)
        static double close_expanded[EXPANDED_LEN];
        for (size_t i = 0; i < 10; i++) {
            for (size_t j = 0; j < TOTAL; j++) {
                close_expanded[i * TOTAL + j] = close[j];
            }
        }
        const double *expanded_inputs[HILBERTTRANSFORM_INPUTS] = {close_expanded};

        static const double options_1[HILBERTTRANSFORM_OPTIONS] = {5.0, 10.0};
        static const double options_2[HILBERTTRANSFORM_OPTIONS] = {10.0, 20.0};
        static const double options_3[HILBERTTRANSFORM_OPTIONS] = {15.0, 30.0};
        static const double options_4[HILBERTTRANSFORM_OPTIONS] = {20.0, 40.0};
        // simd_options is indexed by option set (the N=4 lanes), each lane
        // pointing at HILBERTTRANSFORM_OPTIONS values.
        const double *const simd_options[4] = {options_1, options_2, options_3, options_4};

        CSimdResult r = hilberttransform_simd_by_options(
            expanded_inputs, EXPANDED_LEN, simd_options, 4, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "hilberttransform_simd_by_options failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            char label[32];
            snprintf(label, sizeof(label), "option set %zu", i + 1);
            print_row_head(label, r.outputs[i][0], r.output_lens[i][0], 5);
        }

        printf("\nVerification - calculating each option set individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = hilberttransform_indicator(
                expanded_inputs, EXPANDED_LEN, simd_options[i], NULL, 0);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "hilberttransform_indicator (option set %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            printf("  Option set %zu in_phase: %s\n", i + 1, match ? "MATCH" : "MISMATCH");
            if (!match) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            hilberttransform_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) hilberttransform_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-options equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    return 0;
}
