// INSTANTANEOUSTRENDLINE (Instantaneous Trendline) example for tulip_rs_ffi.
// Mirrors tulip_rs_python/examples/ti_instantaneoustrendline_example.py: same sample data,
// same options, same "compute partial, continue via batch, verify against a
// full recompute" flow, plus SIMD by-assets demonstration.
//
// INSTANTANEOUSTRENDLINE_INPUTS/INSTANTANEOUSTRENDLINE_OPTIONS come from ../include/tulip_rs_ffi_counts.h,
// generated by ../build.rs from the real tulip_rs::indicators::instantaneoustrendline::
// {INPUTS, OPTIONS} constants (run `cargo build` at least once so that file
// exists/is current). The main header is the cbindgen-generated one in
// ../include/, which is the up-to-date API surface.
//
// Note: This indicator has OPTIONS=0, so there is NO simd_by_options function.
//
// Build (from the tulip_rs_ffi directory):
//   cc -O2 -o instantaneoustrendline_example examples/instantaneoustrendline_example.c \
//       -L target/release -ltulip_rs_ffi -Wl,-rpath,target/release
// Run:
//   ./instantaneoustrendline_example

#include <stdio.h>
#include <stdlib.h>

#include "../include/tulip_rs_ffi.h"

static const double close[] = {81.59, 81.06, 82.87, 83.00, 83.61, 83.15, 82.84, 83.99, 84.55, 84.36,
                               85.53, 86.54, 86.89, 87.77, 87.29, 87.50, 88.10, 88.50, 87.90, 88.20,
                               88.80, 89.10, 88.70, 89.30, 89.70, 90.10, 89.50, 90.20, 90.80, 91.10,
                               90.50, 91.20, 91.80, 92.10, 91.50, 92.20, 92.80, 93.10, 92.50, 93.20};

#define TOTAL 40
#define PARTIAL (TOTAL - 5)
#define REST (TOTAL - PARTIAL)

static void print_row(const char *label, const double *row, size_t len) {
    printf("  %-16s: [", label);
    for (size_t i = 0; i < len; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < len) printf(", ");
    }
    printf("]\n");
}

static void print_row_head(const char *label, const double *row, size_t len, size_t max_print) {
    printf("  %-16s: [", label);
    size_t n = len < max_print ? len : max_print;
    for (size_t i = 0; i < n; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < n) printf(", ");
    }
    printf(len > max_print ? ", ...]\n" : "]\n");
}

static int allclose(const double *a, const double *b, size_t len) {
    for (size_t i = 0; i < len; i++) {
        double diff = a[i] - b[i];
        if (diff < 0) diff = -diff;
        if (diff > 1e-9) return 0;
    }
    return 1;
}

int main(void) {
    const double options[INSTANTANEOUSTRENDLINE_OPTIONS] = {}; // empty array
    size_t full_trendline_len = 0, full_trigger_len = 0,
           full_dc_period_len = 0, full_alpha_len = 0;
    double full_trendline[40], full_trigger[40],
           full_dc_period[40], full_alpha[40];

    CIndicatorInfo info = instantaneoustrendline_info();
    printf("=== %s (%s) ===\n", info.name, info.full_name);
    printf("Inputs: %u (close), Options: %u (none)\n",
           (unsigned)INSTANTANEOUSTRENDLINE_INPUTS, (unsigned)INSTANTANEOUSTRENDLINE_OPTIONS);
    printf("Outputs: %zu, Optional outputs: %zu\n",
           info.outputs.len, info.optional_outputs.len);
    printf("Minimum data required: %zu\n", instantaneoustrendline_min_data(options));

    printf("\n=== INSTANTANEOUSTRENDLINE: full calculation (all optional outputs) ===\n");
    {
        const double *inputs[INSTANTANEOUSTRENDLINE_INPUTS] = {close};
        bool optional_outputs[4] = {true, true, true, true}; // trigger, dc_period, alpha

        CIndicatorResult r = instantaneoustrendline_indicator(inputs, TOTAL, options, optional_outputs, 4);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "instantaneoustrendline_indicator failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_outputs=%zu\n", r.num_outputs);

        print_row("trendline", r.outputs[0], r.output_lens[0]);
        print_row("trigger", r.outputs[1], r.output_lens[1]);
        print_row("dc_period", r.outputs[2], r.output_lens[2]);
        print_row("alpha", r.outputs[3], r.output_lens[3]);

        // Keep copies of all rows for later verification.
        full_trendline_len = r.output_lens[0];
        for (size_t i = 0; i < full_trendline_len; i++) full_trendline[i] = r.outputs[0][i];

        full_trigger_len = r.output_lens[1];
        for (size_t i = 0; i < full_trigger_len; i++) full_trigger[i] = r.outputs[1][i];

        full_dc_period_len = r.output_lens[2];
        for (size_t i = 0; i < full_dc_period_len; i++) full_dc_period[i] = r.outputs[2][i];

        full_alpha_len = r.output_lens[3];
        for (size_t i = 0; i < full_alpha_len; i++) full_alpha[i] = r.outputs[3][i];

        void *unused_state = r.state;
        tulip_ffi_result_free(r);
        instantaneoustrendline_state_free(unused_state);
    }

    printf("\n=== INSTANTANEOUSTRENDLINE: partial calculation + batch continuation ===\n");
    {
        const double *partial_inputs[INSTANTANEOUSTRENDLINE_INPUTS] = {close};
        CIndicatorResult pr = instantaneoustrendline_indicator(partial_inputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "instantaneoustrendline_indicator (partial) failed: error=%d\n", pr.error);
            return 1;
        }
        print_row("trendline (partial)", pr.outputs[0], pr.output_lens[0]);
        void *state = pr.state;
        tulip_ffi_result_free(pr); // outputs freed; state kept alive

        const double *rest_inputs[INSTANTANEOUSTRENDLINE_INPUTS] = {close + PARTIAL};
        CBatchResult br = instantaneoustrendline_batch(state, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "instantaneoustrendline_batch failed: error=%d\n", br.error);
            return 1;
        }
        print_row("trendline (continued)", br.outputs[0], br.output_lens[0]);

        printf("\n=== Verification: partial+continued vs. full recompute ===\n");
        int ok = 1;
        size_t continued_len = br.output_lens[0];
        size_t tail_start = full_trendline_len - continued_len;
        for (size_t i = 0; i < continued_len; i++) {
            double a = full_trendline[tail_start + i];
            double b = br.outputs[0][i];
            double diff = a > b ? a - b : b - a;
            if (diff > 1e-9) {
                ok = 0;
                printf("  mismatch at %zu: full=%.6f continued=%.6f\n", i, a, b);
            }
        }
        printf(ok ? "  MATCH: partial+continued trendline equals full recompute\n"
                  : "  MISMATCH detected!\n");

        tulip_ffi_batch_result_free(br);
        instantaneoustrendline_state_free(state);
    }

    printf("\n=== INSTANTANEOUSTRENDLINE: state persistence (serialize / deserialize) ===\n");
    {
        const double *pinputs[INSTANTANEOUSTRENDLINE_INPUTS] = {close};
        CIndicatorResult pr = instantaneoustrendline_indicator(pinputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) { fprintf(stderr, "instantaneoustrendline_indicator failed\n"); return 1; }
        void *st = pr.state;
        tulip_ffi_result_free(pr);

        CBytes blob = tulip_state_serialize(C_INDICATOR_ID_INSTANTANEOUSTRENDLINE, C_STATE_FORMAT_BINCODE, st);
        if (blob.ptr == NULL) { fprintf(stderr, "serialize failed\n"); return 1; }
        printf("  blob: %zu bytes, magic=%.4s, name=%.32s\n",
               blob.len, (const char *)blob.ptr, (const char *)blob.ptr + 6);

        void *rs = tulip_state_deserialize(blob.ptr, blob.len);
        tulip_ffi_bytes_free(blob);
        if (rs == NULL) { fprintf(stderr, "deserialize failed\n"); return 1; }

        const double *rinputs[INSTANTANEOUSTRENDLINE_INPUTS] = {close + PARTIAL};
        CBatchResult a = instantaneoustrendline_batch(st, rinputs, REST, NULL, 0);
        CBatchResult b = instantaneoustrendline_batch(rs, rinputs, REST, NULL, 0);
        int persist_ok = a.error == C_INDICATOR_ERROR_OK && b.error == C_INDICATOR_ERROR_OK &&
                         a.output_lens[0] == b.output_lens[0] &&
                         allclose(a.outputs[0], b.outputs[0], a.output_lens[0]);
        printf(persist_ok ? "  MATCH: deserialized state continues identically\n"
                          : "  MISMATCH detected!\n");
        tulip_ffi_batch_result_free(a);
        tulip_ffi_batch_result_free(b);
        instantaneoustrendline_state_free(st);
        instantaneoustrendline_state_free(rs);
    }

    printf("\n=== INSTANTANEOUSTRENDLINE: SIMD by assets (N=4) ===\n");
    {
        // Asset 1: original data.
        const double *const asset1[INSTANTANEOUSTRENDLINE_INPUTS] = {close};

        // Asset 2: scaled up (+20%).
        double close_2[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) close_2[i] = close[i] * 1.2;
        const double *const asset2[INSTANTANEOUSTRENDLINE_INPUTS] = {close_2};

        // Asset 3: different upward trend.
        double close_3[TOTAL];
        for (size_t i = 0; i < TOTAL; i++)
            close_3[i] = 90.0 + (double)i * 0.5 + close[i] * 0.1;
        const double *const asset3[INSTANTANEOUSTRENDLINE_INPUTS] = {close_3};

        // Asset 4: downward trend.
        double close_4[TOTAL];
        for (size_t i = 0; i < TOTAL; i++)
            close_4[i] = 100.0 - (double)i * 0.3 + close[i] * 0.05;
        const double *const asset4[INSTANTANEOUSTRENDLINE_INPUTS] = {close_4};

        // simd_inputs is indexed by asset (the N=4 SIMD lanes), NOT by input series.
        const double *const *const simd_inputs[4] = {asset1, asset2, asset3, asset4};
        bool optional_outputs[4] = {true, true, true, true}; // trigger, dc_period, alpha

        CSimdResult r = instantaneoustrendline_simd_by_assets(simd_inputs, 4, TOTAL, options, optional_outputs, 4);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "instantaneoustrendline_simd_by_assets failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            printf("Asset %zu ", i + 1);
            print_row_head("trendline", r.outputs[i][0], r.output_lens[i][0], 5);
        }

        printf("\nVerification - calculating each asset individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = instantaneoustrendline_indicator(
                simd_inputs[i], TOTAL, options, optional_outputs, 4);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "instantaneoustrendline_indicator (asset %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            printf("  Asset %zu trendline: %s\n", i + 1, match ? "MATCH" : "MISMATCH");
            if (!match) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            instantaneoustrendline_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) instantaneoustrendline_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-assets equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    // Note: INSTANTANEOUSTRENDLINE has OPTIONS=0, so simd_by_options does NOT exist.
    printf("\n=== INSTANTANEOUSTRENDLINE: NO SIMD BY OPTIONS (OPTIONS_WIDTH=0) ===\n");
    printf("  This indicator has no options, so there is no instantaneoustrendline_simd_by_options function.\n");

    return 0;
}
