// KELTNERCHANNEL (Keltner Channel) example for tulip_rs_ffi.
// Mirrors tulip_rs_python/examples/ti_keltnerchannel_example.py: same sample data,
// same options, same "compute partial, continue via batch, verify against a
// full recompute" flow, plus SIMD by-assets/by-options demonstrations.
//
// KELTNERCHANNEL_INPUTS/KELTNERCHANNEL_OPTIONS come from ../include/tulip_rs_ffi_counts.h,
// generated by ../build.rs from the real tulip_rs::indicators::keltnerchannel::
// {INPUTS, OPTIONS} constants (run `cargo build` at least once so that file
// exists/is current). The main header is the cbindgen-generated one in
// ../include/, which is the up-to-date API surface.
//
// Build (from the tulip_rs_ffi directory):
//   cc -O2 -o keltnerchannel_example examples/keltnerchannel_example.c \
//       -L target/release -ltulip_rs_ffi -Wl,-rpath,target/release
// Run:
//   ./keltnerchannel_example

#include <stdio.h>
#include <stdlib.h>

#include "../include/tulip_rs_ffi.h"

static const double high[] = {82.15, 81.89, 83.03, 83.30, 83.85, 83.90, 83.33, 84.30, 84.84, 85.00,
                              85.90, 86.58, 86.98, 88.00, 87.87};
static const double low[] = {81.29, 80.64, 81.31, 82.65, 83.07, 83.11, 82.49, 82.30, 84.15, 84.11,
                             84.03, 85.39, 85.76, 87.17, 87.01};
static const double close[] = {81.59, 81.06, 82.87, 83.00, 83.61, 83.15, 82.84, 83.99, 84.55, 84.36,
                               85.53, 86.54, 86.89, 87.77, 87.29};

#define TOTAL 15
#define PARTIAL (TOTAL - 5)
#define REST (TOTAL - PARTIAL)

static void print_row(const char *label, const double *row, size_t len) {
    printf("  %-16s: [", label);
    for (size_t i = 0; i < len; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < len) printf(", ");
    }
    printf("]\n");
}

static void print_row_head(const char *label, const double *row, size_t len, size_t max_print) {
    printf("  %-16s: [", label);
    size_t n = len < max_print ? len : max_print;
    for (size_t i = 0; i < n; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < n) printf(", ");
    }
    printf(len > max_print ? ", ...]\n" : "]\n");
}

static int allclose(const double *a, const double *b, size_t len) {
    for (size_t i = 0; i < len; i++) {
        double diff = a[i] - b[i];
        if (diff < 0) diff = -diff;
        if (diff > 1e-9) return 0;
    }
    return 1;
}

int main(void) {
    const double options[KELTNERCHANNEL_OPTIONS] = {5.0, 2.0}; // period, step
    size_t full_lower_len = 0, full_middle_len = 0, full_upper_len = 0,
           full_atr_len = 0, full_tr_len = 0;
    double full_lower[15], full_middle[15], full_upper[15],
           full_atr[15], full_tr[15];

    CIndicatorInfo info = keltnerchannel_info();
    printf("=== %s (%s) ===\n", info.name, info.full_name);
    printf("Inputs: %u (high, low, close), Options: %u (period, step)\n",
           (unsigned)KELTNERCHANNEL_INPUTS, (unsigned)KELTNERCHANNEL_OPTIONS);
    printf("Outputs: %zu, Optional outputs: %zu\n",
           info.outputs.len, info.optional_outputs.len);
    printf("Minimum data required: %zu\n", keltnerchannel_min_data(options));

    printf("\n=== KELTNERCHANNEL: full calculation (all optional outputs) ===\n");
    {
        const double *inputs[KELTNERCHANNEL_INPUTS] = {high, low, close};
        bool optional_outputs[2] = {true, true}; // atr, tr

        CIndicatorResult r = keltnerchannel_indicator(inputs, TOTAL, options, optional_outputs, 2);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "keltnerchannel_indicator failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_outputs=%zu\n", r.num_outputs);

        print_row("lower", r.outputs[0], r.output_lens[0]);
        print_row("middle", r.outputs[1], r.output_lens[1]);
        print_row("upper", r.outputs[2], r.output_lens[2]);
        if (r.num_outputs > 3) {
            print_row("atr", r.outputs[3], r.output_lens[3]);
        }
        if (r.num_outputs > 4) {
            print_row("tr", r.outputs[4], r.output_lens[4]);
        }

        // Keep copies of all rows for later verification.
        full_lower_len = r.output_lens[0];
        for (size_t i = 0; i < full_lower_len; i++) full_lower[i] = r.outputs[0][i];

        full_middle_len = r.output_lens[1];
        for (size_t i = 0; i < full_middle_len; i++) full_middle[i] = r.outputs[1][i];

        full_upper_len = r.output_lens[2];
        for (size_t i = 0; i < full_upper_len; i++) full_upper[i] = r.outputs[2][i];

        full_atr_len = r.num_outputs > 3 ? r.output_lens[3] : 0;
        if (full_atr_len > 0) {
            for (size_t i = 0; i < full_atr_len; i++) full_atr[i] = r.outputs[3][i];
        }

        full_tr_len = r.num_outputs > 4 ? r.output_lens[4] : 0;
        if (full_tr_len > 0) {
            for (size_t i = 0; i < full_tr_len; i++) full_tr[i] = r.outputs[4][i];
        }

        void *unused_state = r.state;
        tulip_ffi_result_free(r);
        keltnerchannel_state_free(unused_state);
    }

    printf("\n=== KELTNERCHANNEL: partial calculation + batch continuation ===\n");
    {
        const double *partial_inputs[KELTNERCHANNEL_INPUTS] = {high, low, close};
        CIndicatorResult pr = keltnerchannel_indicator(partial_inputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "keltnerchannel_indicator (partial) failed: error=%d\n", pr.error);
            return 1;
        }
        print_row("lower (partial)", pr.outputs[0], pr.output_lens[0]);
        print_row("middle (partial)", pr.outputs[1], pr.output_lens[1]);
        print_row("upper (partial)", pr.outputs[2], pr.output_lens[2]);
        void *state = pr.state;
        tulip_ffi_result_free(pr); // outputs freed; state kept alive

        const double *rest_inputs[KELTNERCHANNEL_INPUTS] = {high + PARTIAL, low + PARTIAL, close + PARTIAL};
        CBatchResult br = keltnerchannel_batch(state, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "keltnerchannel_batch failed: error=%d\n", br.error);
            return 1;
        }
        print_row("lower (continued)", br.outputs[0], br.output_lens[0]);
        print_row("middle (continued)", br.outputs[1], br.output_lens[1]);
        print_row("upper (continued)", br.outputs[2], br.output_lens[2]);

        printf("\n=== Verification: partial+continued vs. full recompute ===\n");
        int ok = 1;
        size_t continued_len = br.output_lens[0];
        size_t tail_start = full_lower_len - continued_len;

        for (size_t i = 0; i < continued_len; i++) {
            double a = full_lower[tail_start + i];
            double b = br.outputs[0][i];
            double diff = a > b ? a - b : b - a;
            if (diff > 1e-9) {
                ok = 0;
                printf("  mismatch at %zu (lower): full=%.6f continued=%.6f\n", i, a, b);
            }
        }

        for (size_t i = 0; i < continued_len; i++) {
            double a = full_middle[tail_start + i];
            double b = br.outputs[1][i];
            double diff = a > b ? a - b : b - a;
            if (diff > 1e-9) {
                ok = 0;
                printf("  mismatch at %zu (middle): full=%.6f continued=%.6f\n", i, a, b);
            }
        }

        for (size_t i = 0; i < continued_len; i++) {
            double a = full_upper[tail_start + i];
            double b = br.outputs[2][i];
            double diff = a > b ? a - b : b - a;
            if (diff > 1e-9) {
                ok = 0;
                printf("  mismatch at %zu (upper): full=%.6f continued=%.6f\n", i, a, b);
            }
        }

        printf(ok ? "  MATCH: partial+continued lower/middle/upper equals full recompute\n"
                  : "  MISMATCH detected!\n");

        tulip_ffi_batch_result_free(br);
        keltnerchannel_state_free(state);
    }

    printf("\n=== KELTNERCHANNEL: SIMD by assets (N=4) ===\n");
    {
        // Asset 1: original data.
        const double *const asset1[KELTNERCHANNEL_INPUTS] = {high, low, close};

        // Asset 2: scaled up (+20%).
        double high_2[TOTAL], low_2[TOTAL], close_2[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_2[i] = high[i] * 1.2;
            low_2[i] = low[i] * 1.2;
            close_2[i] = close[i] * 1.2;
        }
        const double *const asset2[KELTNERCHANNEL_INPUTS] = {high_2, low_2, close_2};

        // Asset 3: different upward trend.
        double high_3[TOTAL], low_3[TOTAL], close_3[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_3[i] = 90.0 + (double)i * 0.5 + high[i] * 0.1;
            low_3[i] = 90.0 + (double)i * 0.5 + low[i] * 0.1;
            close_3[i] = 90.0 + (double)i * 0.5 + close[i] * 0.1;
        }
        const double *const asset3[KELTNERCHANNEL_INPUTS] = {high_3, low_3, close_3};

        // Asset 4: downward trend.
        double high_4[TOTAL], low_4[TOTAL], close_4[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_4[i] = 100.0 - (double)i * 0.3 + high[i] * 0.05;
            low_4[i] = 100.0 - (double)i * 0.3 + low[i] * 0.05;
            close_4[i] = 100.0 - (double)i * 0.3 + close[i] * 0.05;
        }
        const double *const asset4[KELTNERCHANNEL_INPUTS] = {high_4, low_4, close_4};

        // simd_inputs is indexed by asset (the N=4 SIMD lanes), NOT by input series.
        const double *const *const simd_inputs[4] = {asset1, asset2, asset3, asset4};
        bool optional_outputs[2] = {true, true}; // atr, tr

        CSimdResult r = keltnerchannel_simd_by_assets(simd_inputs, 4, TOTAL, options, optional_outputs, 2);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "keltnerchannel_simd_by_assets failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            printf("Asset %zu ", i + 1);
            print_row_head("middle", r.outputs[i][1], r.output_lens[i][1], 5);
        }

        printf("\nVerification - calculating each asset individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = keltnerchannel_indicator(
                simd_inputs[i], TOTAL, options, optional_outputs, 2);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "keltnerchannel_indicator (asset %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match = allclose(r.outputs[i][1], ind.outputs[1], r.output_lens[i][1]);
            printf("  Asset %zu middle: %s\n", i + 1, match ? "MATCH" : "MISMATCH");
            if (!match) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            keltnerchannel_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) keltnerchannel_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-assets equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    printf("\n=== KELTNERCHANNEL: SIMD by options (N=4) ===\n");
    {
        const double *inputs[KELTNERCHANNEL_INPUTS] = {high, low, close};

        static const double options_1[KELTNERCHANNEL_OPTIONS] = {5.0, 2.0};
        static const double options_2[KELTNERCHANNEL_OPTIONS] = {7.0, 1.5};
        static const double options_3[KELTNERCHANNEL_OPTIONS] = {10.0, 2.0};
        static const double options_4[KELTNERCHANNEL_OPTIONS] = {14.0, 2.0};
        // simd_options is indexed by option set (the N=4 lanes), each lane
        // pointing at KELTNERCHANNEL_OPTIONS values.
        const double *const simd_options[4] = {options_1, options_2, options_3, options_4};

        CSimdResult r = keltnerchannel_simd_by_options(
            inputs, TOTAL, simd_options, 4, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "keltnerchannel_simd_by_options failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            char label[32];
            snprintf(label, sizeof(label), "option set %zu", i + 1);
            print_row_head(label, r.outputs[i][1], r.output_lens[i][1], 5);
        }

        printf("\nVerification - calculating each option set individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = keltnerchannel_indicator(
                inputs, TOTAL, simd_options[i], NULL, 0);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "keltnerchannel_indicator (option set %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match = allclose(r.outputs[i][1], ind.outputs[1], r.output_lens[i][1]);
            printf("  Option set %zu middle: %s\n", i + 1, match ? "MATCH" : "MISMATCH");
            if (!match) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            keltnerchannel_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) keltnerchannel_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-options equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    return 0;
}
