// MSW (Mesa Sine Wave) example for tulip_rs_ffi.
// Mirrors tulip_rs_python/examples/ti_msw_example.py: same sample data,
// same options, same "compute partial, continue via batch" flow, plus
// SIMD by-assets/by-options usage demonstrations.
//
// MSW_INPUTS/MSW_OPTIONS come from ../include/tulip_rs_ffi_counts.h,
// generated by ../build.rs from the real tulip_rs::indicators::msw::
// {INPUTS, OPTIONS} constants (run `cargo build` at least once so that file
// exists/is current). The main header is the cbindgen-generated one in
// ../include/, which is the up-to-date API surface.
//
// Build (from the tulip_rs_ffi directory):
//   cc -O2 -o msw_example examples/msw_example.c \
//       -L target/release -ltulip_rs_ffi -Wl,-rpath,target/release
// Run:
//   ./msw_example

#include <stdio.h>
#include <stdlib.h>

#include "../include/tulip_rs_ffi.h"

static const double close[] = {81.59, 81.06, 82.87, 83.00, 83.61, 83.15, 82.84, 83.99, 84.55, 84.36, 85.53, 86.54, 86.89, 87.77, 87.29};

#define TOTAL 15
#define PARTIAL (TOTAL - 5)
#define REST (TOTAL - PARTIAL)

static void print_row(const char *label, const double *row, size_t len) {
    printf("  %-14s: [", label);
    for (size_t i = 0; i < len; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < len) printf(", ");
    }
    printf("]\n");
}

static void print_row_head(const char *label, const double *row, size_t len, size_t max_print) {
    printf("  %-14s: [", label);
    size_t n = len < max_print ? len : max_print;
    for (size_t i = 0; i < n; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < n) printf(", ");
    }
    printf(len > max_print ? ", ...]\n" : "]\n");
}

static int allclose(const double *a, const double *b, size_t len) {
    for (size_t i = 0; i < len; i++) { double d = a[i] - b[i]; if (d < 0) d = -d; if (d > 1e-9) return 0; }
    return 1;
}

int main(void) {
    const double options[MSW_OPTIONS] = {5.0}; // period

    CIndicatorInfo info = msw_info();
    printf("=== %s (%s) ===\n", info.name, info.full_name);
    printf("Inputs: %u, Options: %u (period), Optional outputs: %u\n",
           (unsigned)MSW_INPUTS, (unsigned)MSW_OPTIONS,
           (unsigned)info.optional_outputs.len);
    printf("Minimum data required: %zu\n", msw_min_data(options));

    printf("\n=== MSW: full calculation ===\n");
    {
        const double *inputs[MSW_INPUTS] = {close};

        CIndicatorResult r = msw_indicator(inputs, TOTAL, options, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "msw_indicator failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_outputs=%zu\n", r.num_outputs);
        print_row("msw_sine", r.outputs[0], r.output_lens[0]);
        print_row("msw_lead", r.outputs[1], r.output_lens[1]);

        void *unused_state = r.state;
        tulip_ffi_result_free(r);
        msw_state_free(unused_state);
    }

    printf("\n=== MSW: partial calculation + batch continuation ===\n");
    {
        const double *partial_inputs[MSW_INPUTS] = {close};
        CIndicatorResult pr = msw_indicator(partial_inputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "msw_indicator (partial) failed: error=%d\n", pr.error);
            return 1;
        }
        print_row("msw_sine (partial)", pr.outputs[0], pr.output_lens[0]);
        print_row("msw_lead (partial)", pr.outputs[1], pr.output_lens[1]);
        void *state = pr.state;
        tulip_ffi_result_free(pr); // outputs freed; state kept alive

        const double *rest_inputs[MSW_INPUTS] = {close + PARTIAL};
        CBatchResult br = msw_batch(state, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "msw_batch failed: error=%d\n", br.error);
            return 1;
        }
        print_row("msw_sine (continued)", br.outputs[0], br.output_lens[0]);
        print_row("msw_lead (continued)", br.outputs[1], br.output_lens[1]);

        tulip_ffi_batch_result_free(br);
        msw_state_free(state);
    }

    printf("\n=== MSW: state persistence (serialize / deserialize) ===\n");
    {
        const double *pinputs[MSW_INPUTS] = {close};
        CIndicatorResult pr = msw_indicator(pinputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) { fprintf(stderr, "msw_indicator failed\n"); return 1; }
        void *st = pr.state;
        tulip_ffi_result_free(pr);

        CBytes blob = tulip_state_serialize(C_INDICATOR_ID_MSW, C_STATE_FORMAT_BINCODE, st);
        if (blob.ptr == NULL) { fprintf(stderr, "serialize failed\n"); return 1; }
        printf("  blob: %zu bytes, magic=%.4s, name=%.32s\n",
               blob.len, (const char *)blob.ptr, (const char *)blob.ptr + 6);

        void *rs = tulip_state_deserialize(blob.ptr, blob.len);
        tulip_ffi_bytes_free(blob);
        if (rs == NULL) { fprintf(stderr, "deserialize failed\n"); return 1; }

        const double *rinputs[MSW_INPUTS] = {close + PARTIAL};
        CBatchResult a = msw_batch(st, rinputs, REST, NULL, 0);
        CBatchResult b = msw_batch(rs, rinputs, REST, NULL, 0);
        int persist_ok = a.error == C_INDICATOR_ERROR_OK && b.error == C_INDICATOR_ERROR_OK &&
                         a.output_lens[0] == b.output_lens[0] &&
                         allclose(a.outputs[0], b.outputs[0], a.output_lens[0]);
        printf(persist_ok ? "  MATCH: deserialized state continues identically\n"
                          : "  MISMATCH detected!\n");
        tulip_ffi_batch_result_free(a);
        tulip_ffi_batch_result_free(b);
        msw_state_free(st);
        msw_state_free(rs);
    }

    printf("\n=== MSW: SIMD by assets (N=4) ===\n");
    {
        // Asset 1: original data.
        const double *const asset1[MSW_INPUTS] = {close};

        // Asset 2: scaled up (+20%).
        double close_2[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) close_2[i] = close[i] * 1.2;
        const double *const asset2[MSW_INPUTS] = {close_2};

        // Asset 3: different upward trend.
        double close_3[TOTAL];
        for (size_t i = 0; i < TOTAL; i++)
            close_3[i] = 90.0 + (double)i * 0.5 + close[i] * 0.1;
        const double *const asset3[MSW_INPUTS] = {close_3};

        // Asset 4: downward trend.
        double close_4[TOTAL];
        for (size_t i = 0; i < TOTAL; i++)
            close_4[i] = 100.0 - (double)i * 0.3 + close[i] * 0.05;
        const double *const asset4[MSW_INPUTS] = {close_4};

        // simd_inputs is indexed by asset (the N=4 SIMD lanes), NOT by input
        // series -- hence [4] here stays a lane count.
        const double *const *const simd_inputs[4] = {asset1, asset2, asset3, asset4};

        CSimdResult r = msw_simd_by_assets(simd_inputs, 4, TOTAL, options, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "msw_simd_by_assets failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            printf("Asset %zu ", i + 1);
            print_row("msw_sine", r.outputs[i][0], r.output_lens[i][0]);
            print_row("msw_lead", r.outputs[i][1], r.output_lens[i][1]);
        }

        for (size_t i = 0; i < r.num_results; i++) msw_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
    }

    printf("\n=== MSW: SIMD by options (N=4) ===\n");
    {
        // Tile the base series 20x so longer-period option sets have enough data.
        #define EXPANDED_LEN (TOTAL * 20)
        static double close_expanded[EXPANDED_LEN];
        for (size_t i = 0; i < 20; i++) {
            for (size_t j = 0; j < TOTAL; j++) {
                close_expanded[i * TOTAL + j] = close[j];
            }
        }
        const double *expanded_inputs[MSW_INPUTS] = {close_expanded};

        static const double options_1[MSW_OPTIONS] = {3.0};
        static const double options_2[MSW_OPTIONS] = {5.0};
        static const double options_3[MSW_OPTIONS] = {7.0};
        static const double options_4[MSW_OPTIONS] = {10.0};
        // simd_options is indexed by option set (the N=4 lanes), each lane
        // pointing at MSW_OPTIONS values.
        const double *const simd_options[4] = {options_1, options_2, options_3, options_4};

        CSimdResult r = msw_simd_by_options(
            expanded_inputs, EXPANDED_LEN, simd_options, 4, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "msw_simd_by_options failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            char label[32];
            snprintf(label, sizeof(label), "option set %zu", i + 1);
            print_row_head(label, r.outputs[i][0], r.output_lens[i][0], 5);
        }

        for (size_t i = 0; i < r.num_results; i++) msw_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
    }

    return 0;
}
