// PIVOTPOINT (Pivot Point) example for tulip_rs_ffi.
// Mirrors tulip_rs_python/examples/ti_pivotpoint_example.py: same sample data,
// same options, plus SIMD by-assets/by-options demonstrations.
//
// PIVOTPOINT_INPUTS/PIVOTPOINT_OPTIONS come from ../include/tulip_rs_ffi_counts.h,
// generated by ../build.rs from the real tulip_rs::indicators::pivotpoint::
// {INPUTS, OPTIONS} constants (run `cargo build` at least once so that file
// exists/is current). The main header is the cbindgen-generated one in
// ../include/, which is the up-to-date API surface.
//
// Note: Pivotpoint has num_outputs=1 with 7 values per row (s3,s2,s1,pp,r1,r2,r3).
//
// Build (from the tulip_rs_ffi directory):
//   cc -O2 -o pivotpoint_example examples/pivotpoint_example.c \
//       -L target/release -ltulip_rs_ffi -Wl,-rpath,target/release
// Run:
//   ./pivotpoint_example

#include <stdio.h>
#include <stdlib.h>

#include "../include/tulip_rs_ffi.h"

static const double high[]  = {82.15, 81.89, 83.03, 83.30, 83.85, 83.90, 83.33, 84.30, 84.84, 85.00, 85.90, 86.58, 86.98, 88.00, 87.87};
static const double low[]   = {81.29, 80.64, 81.31, 82.65, 83.07, 83.11, 82.49, 82.30, 84.15, 84.11, 84.03, 85.39, 85.76, 87.17, 87.01};
static const double close[] = {81.59, 81.06, 82.87, 83.00, 83.61, 83.15, 82.84, 83.99, 84.55, 84.36, 85.53, 86.54, 86.89, 87.77, 87.29};

#define TOTAL 15
#define PARTIAL (TOTAL - 5)
#define REST (TOTAL - PARTIAL)

static void print_row(const char *label, const double *row, size_t len) {
    printf("  %-14s: [", label);
    for (size_t i = 0; i < len; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < len) printf(", ");
    }
    printf("]\n");
}

static void print_row_head(const char *label, const double *row, size_t len, size_t max_print) {
    printf("  %-14s: [", label);
    size_t n = len < max_print ? len : max_print;
    for (size_t i = 0; i < n; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < n) printf(", ");
    }
    printf(len > max_print ? ", ...]\n" : "]\n");
}

static int allclose(const double *a, const double *b, size_t len) {
    for (size_t i = 0; i < len; i++) {
        double diff = a[i] - b[i];
        if (diff < 0) diff = -diff;
        if (diff > 1e-9) return 0;
    }
    return 1;
}

int main(void) {
    const double options[PIVOTPOINT_OPTIONS] = {5.0}; // period
    double full_pp[TOTAL];
    size_t full_len = 0;

    CIndicatorInfo info = pivotpoint_info();
    printf("=== %s (%s) ===\n", info.name, info.full_name);
    printf("Inputs: %u, Options: %u (period), Optional outputs: %u\n",
           (unsigned)PIVOTPOINT_INPUTS, (unsigned)PIVOTPOINT_OPTIONS,
           (unsigned)info.optional_outputs.len);
    printf("Minimum data required: %zu\n", pivotpoint_min_data(options));

    printf("\n=== PIVOTPOINT: full calculation ===\n");
    {
        const double *inputs[PIVOTPOINT_INPUTS] = {high, low, close};

        CIndicatorResult r = pivotpoint_indicator(inputs, TOTAL, options, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "pivotpoint_indicator failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_outputs=%zu, output_lens[0]=%zu\n", r.num_outputs, r.output_lens[0]);
        // Pivotpoint has num_outputs=1 with 7 values in the row: s3,s2,s1,pp,r1,r2,r3
        print_row("s3", &r.outputs[0][0], r.output_lens[0]);
        print_row("s2", &r.outputs[0][1], r.output_lens[0]);
        print_row("s1", &r.outputs[0][2], r.output_lens[0]);
        print_row("pp", &r.outputs[0][3], r.output_lens[0]);
        print_row("r1", &r.outputs[0][4], r.output_lens[0]);
        print_row("r2", &r.outputs[0][5], r.output_lens[0]);
        print_row("r3", &r.outputs[0][6], r.output_lens[0]);

        // Keep a copy of the mandatory "pp" (pivot point) row for later verification.
        full_len = r.output_lens[0];
        for (size_t i = 0; i < full_len; i++) full_pp[i] = r.outputs[0][i]; // pp is at index 3

        void *unused_state = r.state;
        tulip_ffi_result_free(r);
        pivotpoint_state_free(unused_state);
    }

    printf("\n=== PIVOTPOINT: partial calculation + batch continuation ===\n");
    {
        const double *partial_inputs[PIVOTPOINT_INPUTS] = {high, low, close};
        CIndicatorResult pr = pivotpoint_indicator(partial_inputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "pivotpoint_indicator (partial) failed: error=%d\n", pr.error);
            return 1;
        }
        print_row("s3 (partial)", &pr.outputs[0][0], pr.output_lens[0]);
        print_row("s2 (partial)", &pr.outputs[0][1], pr.output_lens[0]);
        print_row("s1 (partial)", &pr.outputs[0][2], pr.output_lens[0]);
        print_row("pp (partial)", &pr.outputs[0][3], pr.output_lens[0]);
        print_row("r1 (partial)", &pr.outputs[0][4], pr.output_lens[0]);
        print_row("r2 (partial)", &pr.outputs[0][5], pr.output_lens[0]);
        print_row("r3 (partial)", &pr.outputs[0][6], pr.output_lens[0]);
        void *state = pr.state;
        tulip_ffi_result_free(pr); // outputs freed; state kept alive

        const double *rest_inputs[PIVOTPOINT_INPUTS] = {high + PARTIAL, low + PARTIAL, close + PARTIAL};
        CBatchResult br = pivotpoint_batch(state, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "pivotpoint_batch failed: error=%d\n", br.error);
            return 1;
        }
        print_row("s3 (continued)", &br.outputs[0][0], br.output_lens[0]);
        print_row("s2 (continued)", &br.outputs[0][1], br.output_lens[0]);
        print_row("s1 (continued)", &br.outputs[0][2], br.output_lens[0]);
        print_row("pp (continued)", &br.outputs[0][3], br.output_lens[0]);
        print_row("r1 (continued)", &br.outputs[0][4], br.output_lens[0]);
        print_row("r2 (continued)", &br.outputs[0][5], br.output_lens[0]);
        print_row("r3 (continued)", &br.outputs[0][6], br.output_lens[0]);

        printf("\n=== Verification: partial+continued vs. full recompute ===\n");
        int ok = 1;
        size_t continued_len = br.output_lens[0];
        size_t tail_start = full_len - continued_len;
        // All outputs have the same length for pivotpoint
        for (size_t i = 0; i < continued_len; i++) {
            double a_pp = full_pp[tail_start + i];
            double b_pp = br.outputs[0][i]; // pp is at index 3
            double diff_pp = a_pp > b_pp ? a_pp - b_pp : b_pp - a_pp;
            if (diff_pp > 1e-9) {
                ok = 0;
                printf("  mismatch at %zu: full_pp=%.6f continued_pp=%.6f\n", i, a_pp, b_pp);
            }
        }
        printf(ok ? "  MATCH: partial+continued pivotpoint equals full recompute\n"
                  : "  MISMATCH detected!\n");

        tulip_ffi_batch_result_free(br);
        pivotpoint_state_free(state);
    }

    printf("\n=== PIVOTPOINT: SIMD by assets (N=4) ===\n");
    {
        // Asset 1: original data.
        const double *const asset1[PIVOTPOINT_INPUTS] = {high, low, close};

        // Asset 2: scaled up (+20%).
        double high_2[TOTAL], low_2[TOTAL], close_2[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_2[i] = high[i] * 1.2;
            low_2[i] = low[i] * 1.2;
            close_2[i] = close[i] * 1.2;
        }
        const double *const asset2[PIVOTPOINT_INPUTS] = {high_2, low_2, close_2};

        // Asset 3: different upward trend.
        double high_3[TOTAL], low_3[TOTAL], close_3[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_3[i] = 90.0 + (double)i * 0.5 + high[i] * 0.1;
            low_3[i] = 90.0 + (double)i * 0.5 + low[i] * 0.1;
            close_3[i] = 90.0 + (double)i * 0.5 + close[i] * 0.1;
        }
        const double *const asset3[PIVOTPOINT_INPUTS] = {high_3, low_3, close_3};

        // Asset 4: downward trend.
        double high_4[TOTAL], low_4[TOTAL], close_4[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_4[i] = 100.0 - (double)i * 0.3 + high[i] * 0.05;
            low_4[i] = 100.0 - (double)i * 0.3 + low[i] * 0.05;
            close_4[i] = 100.0 - (double)i * 0.3 + close[i] * 0.05;
        }
        const double *const asset4[PIVOTPOINT_INPUTS] = {high_4, low_4, close_4};

        // simd_inputs is indexed by asset (the N=4 SIMD lanes), NOT by input
        // series -- hence [4] here stays a lane count.
        const double *const *const simd_inputs[4] = {asset1, asset2, asset3, asset4};

        CSimdResult r = pivotpoint_simd_by_assets(simd_inputs, 4, TOTAL, options, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "pivotpoint_simd_by_assets failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            // Pivotpoint has num_outputs=1 with 7 values in the row
            char label[32];
            snprintf(label, sizeof(label), "Asset %zu pp", i + 1);
            printf("  %-14s: [%.4f]\n", label, r.outputs[i][0][3]); // pp at index 3 of row 0
        }

        printf("\nVerification - calculating each asset individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = pivotpoint_indicator(
                simd_inputs[i], TOTAL, options, NULL, 0);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "pivotpoint_indicator (asset %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            // Pivotpoint has num_outputs=1 with 7 values in the row
            int match_all = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            printf("  Asset %zu: all_values=%s\n", i + 1,
                   match_all ? "MATCH" : "MISMATCH");
            if (!match_all) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            pivotpoint_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) pivotpoint_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-assets equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    printf("\n=== PIVOTPOINT: SIMD by options (N=4) ===\n");
    {
        // Tile the base series 20x so longer-period option sets have enough data.
        #define EXPANDED_LEN (TOTAL * 20)
        static double high_expanded[EXPANDED_LEN];
        static double low_expanded[EXPANDED_LEN];
        static double close_expanded[EXPANDED_LEN];
        for (size_t i = 0; i < 20; i++) {
            for (size_t j = 0; j < TOTAL; j++) {
                high_expanded[i * TOTAL + j] = high[j];
                low_expanded[i * TOTAL + j] = low[j];
                close_expanded[i * TOTAL + j] = close[j];
            }
        }
        const double *expanded_inputs[PIVOTPOINT_INPUTS] = {high_expanded, low_expanded, close_expanded};

        static const double options_1[PIVOTPOINT_OPTIONS] = {3.0};
        static const double options_2[PIVOTPOINT_OPTIONS] = {5.0};
        static const double options_3[PIVOTPOINT_OPTIONS] = {7.0};
        static const double options_4[PIVOTPOINT_OPTIONS] = {10.0};
        // simd_options is indexed by option set (the N=4 lanes), each lane
        // pointing at PIVOTPOINT_OPTIONS values.
        const double *const simd_options[4] = {options_1, options_2, options_3, options_4};

        CSimdResult r = pivotpoint_simd_by_options(
            expanded_inputs, EXPANDED_LEN, simd_options, 4, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "pivotpoint_simd_by_options failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            char label[64];
            snprintf(label, sizeof(label), "option set %zu pp", i + 1);
            print_row_head(label, &r.outputs[i][0][3], r.output_lens[i][0], 5); // print pp
        }

        printf("\nVerification - calculating each option set individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = pivotpoint_indicator(
                expanded_inputs, EXPANDED_LEN, simd_options[i], NULL, 0);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "pivotpoint_indicator (option set %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            // Pivotpoint has num_outputs=1 with 7 values in the row
            int match_all = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            printf("  Option set %zu: all_values=%s\n", i + 1,
                   match_all ? "MATCH" : "MISMATCH");
            if (!match_all) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            pivotpoint_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) pivotpoint_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-options equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    printf("\n=== PIVOTPOINT: state persistence (serialize / deserialize) ===\n");
    {
        const double *pinputs[PIVOTPOINT_INPUTS] = {high, low, close};
        CIndicatorResult pr = pivotpoint_indicator(pinputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) { fprintf(stderr, "pivotpoint_indicator failed\n"); return 1; }
        void *st = pr.state;
        tulip_ffi_result_free(pr);

        CBytes blob = tulip_state_serialize(C_INDICATOR_ID_PIVOTPOINT, C_STATE_FORMAT_BINCODE, st);
        if (blob.ptr == NULL) { fprintf(stderr, "serialize failed\n"); return 1; }
        printf("  blob: %zu bytes, magic=%.4s, name=%.32s\n",
               blob.len, (const char *)blob.ptr, (const char *)blob.ptr + 6);

        void *rs = tulip_state_deserialize(blob.ptr, blob.len);
        tulip_ffi_bytes_free(blob);
        if (rs == NULL) { fprintf(stderr, "deserialize failed\n"); return 1; }

        const double *rinputs[PIVOTPOINT_INPUTS] = {high + PARTIAL, low + PARTIAL, close + PARTIAL};
        CBatchResult a = pivotpoint_batch(st, rinputs, REST, NULL, 0);
        CBatchResult b = pivotpoint_batch(rs, rinputs, REST, NULL, 0);
        int persist_ok = a.error == C_INDICATOR_ERROR_OK && b.error == C_INDICATOR_ERROR_OK &&
                         a.output_lens[0] == b.output_lens[0] &&
                         allclose(a.outputs[0], b.outputs[0], a.output_lens[0]);
        printf(persist_ok ? "  MATCH: deserialized state continues identically\n"
                          : "  MISMATCH detected!\n");
        tulip_ffi_batch_result_free(a);
        tulip_ffi_batch_result_free(b);
        pivotpoint_state_free(st);
        pivotpoint_state_free(rs);
    }

    return 0;
}
