// PVI (Positive Volume Index) example for tulip_rs_ffi.
// Mirrors tulip_rs_python/examples/ti_pvi_example.py: same sample data,
// same options, same "compute partial, continue via batch, verify against a
// full recompute" flow, plus SIMD by-assets demonstration.
//
// Note: PVI has NO options (PPO_OPTIONS = 0), so it does NOT have simd_by_options.
// Only the SIMD by-assets section is included.
//
// PVI_INPUTS/PVI_OPTIONS come from ../include/tulip_rs_ffi_counts.h,
// generated by ../build.rs from the real tulip_rs::indicators::pvi::
// {INPUTS, OPTIONS} constants (run `cargo build` at least once so that file
// exists/is current). The main header is the cbindgen-generated one in
// ../include/, which is the up-to-date API surface.
//
// Build (from the tulip_rs_ffi directory):
//   cc -O2 -o pvi_example examples/pvi_example.c \
//       -L target/release -ltulip_rs_ffi -Wl,-rpath,target/release
// Run:
//   ./pvi_example

#include <stdio.h>
#include <stdlib.h>

#include "../include/tulip_rs_ffi.h"

static const double close[]  = {81.59, 81.06, 82.87, 83.00, 83.61, 83.15, 82.84, 83.99, 84.55, 84.36, 85.53, 86.54, 86.89, 87.77, 87.29};
static const double volume[] = {5653100.0, 6447400.0, 7690900.0, 3831400.0, 4455100.0, 3798000.0, 3936200.0, 4732000.0, 4841300.0, 3915300.0, 6830800.0, 6694100.0, 5293600.0, 7985800.0, 4807900.0};

#define TOTAL 15
#define PARTIAL (TOTAL - 5)
#define REST (TOTAL - PARTIAL)

static void print_row(const char *label, const double *row, size_t len) {
    printf("  %-14s: [", label);
    for (size_t i = 0; i < len; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < len) printf(", ");
    }
    printf("]\n");
}

static void print_row_head(const char *label, const double *row, size_t len, size_t max_print) {
    printf("  %-14s: [", label);
    size_t n = len < max_print ? len : max_print;
    for (size_t i = 0; i < n; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < n) printf(", ");
    }
    printf(len > max_print ? ", ...]\n" : "]\n");
}

static int allclose(const double *a, const double *b, size_t len) {
    for (size_t i = 0; i < len; i++) {
        double diff = a[i] - b[i];
        if (diff < 0) diff = -diff;
        if (diff > 1e-9) return 0;
    }
    return 1;
}

int main(void) {
    const double options[PVI_OPTIONS] = {}; // PVI has no options

    CIndicatorInfo info = pvi_info();
    printf("=== %s (%s) ===\n", info.name, info.full_name);
    printf("Inputs: %u, Options: %u (none), Optional outputs: %u\n",
           (unsigned)PVI_INPUTS, (unsigned)PVI_OPTIONS,
           (unsigned)info.optional_outputs.len);
    printf("Minimum data required: %zu\n", pvi_min_data(options));

    // Full calculation to get outputs for verification later
    const double *full_inputs[PVI_INPUTS] = {close, volume};
    CIndicatorResult full_r = pvi_indicator(full_inputs, TOTAL, options, NULL, 0);
    if (full_r.error != C_INDICATOR_ERROR_OK) {
        fprintf(stderr, "pvi_indicator (full for verification) failed: error=%d\n", full_r.error);
        return 1;
    }

    printf("\n=== PVI: full calculation ===\n");
    printf("num_outputs=%zu\n", full_r.num_outputs);
    print_row("pvi", full_r.outputs[0], full_r.output_lens[0]);

    printf("\n=== PVI: partial calculation + batch continuation ===\n");
    {
        const double *partial_inputs[PVI_INPUTS] = {close, volume};
        CIndicatorResult pr = pvi_indicator(partial_inputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "pvi_indicator (partial) failed: error=%d\n", pr.error);
            return 1;
        }
        print_row("pvi (partial)", pr.outputs[0], pr.output_lens[0]);
        void *state = pr.state;
        tulip_ffi_result_free(pr); // outputs freed; state kept alive

        const double *rest_inputs[PVI_INPUTS] = {close + PARTIAL, volume + PARTIAL};
        CBatchResult br = pvi_batch(state, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "pvi_batch failed: error=%d\n", br.error);
            return 1;
        }
        print_row("pvi (continued)", br.outputs[0], br.output_lens[0]);

        printf("\n=== Verification: partial+continued vs. full recompute ===\n");
        int ok = 1;
        size_t continued_len = br.output_lens[0];
        // Note: PVI is cumulative and stateful; we verify the continuation
        // produces the same tail values as a full recomputation.
        // Output length = data_len - min_data + 1, so:
        // - partial (10): output length = 10 - 2 + 1 = 9 (indices 0-8 of full)
        // - continued: should match indices 9-13 of full
        size_t tail_start = PARTIAL - pvi_min_data(options) + 1;
        for (size_t i = 0; i < continued_len; i++) {
            double a = full_r.outputs[0][tail_start + i]; // tail from full
            double b = br.outputs[0][i];
            double diff = a > b ? a - b : b - a;
            if (diff > 1e-9) {
                ok = 0;
                printf("  mismatch at %zu: full=%.6f continued=%.6f\n", i, a, b);
            }
        }
        printf(ok ? "  MATCH: partial+continued pvi equals full recompute\n"
                  : "  MISMATCH detected!\n");

        tulip_ffi_batch_result_free(br);
        pvi_state_free(state);
    }

    printf("\n=== PVI: state persistence (serialize / deserialize) ===\n");
    {
        const double *pinputs[PVI_INPUTS] = {close, volume};
        CIndicatorResult pr = pvi_indicator(pinputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) { fprintf(stderr, "pvi_indicator failed\n"); return 1; }
        void *st = pr.state;
        tulip_ffi_result_free(pr);

        CBytes blob = tulip_state_serialize(C_INDICATOR_ID_PVI, C_STATE_FORMAT_BINCODE, st);
        if (blob.ptr == NULL) { fprintf(stderr, "serialize failed\n"); return 1; }
        printf("  blob: %zu bytes, magic=%.4s, name=%.32s\n",
               blob.len, (const char *)blob.ptr, (const char *)blob.ptr + 6);

        void *rs = tulip_state_deserialize(blob.ptr, blob.len);
        tulip_ffi_bytes_free(blob);
        if (rs == NULL) { fprintf(stderr, "deserialize failed\n"); return 1; }

        const double *rinputs[PVI_INPUTS] = {close + PARTIAL, volume + PARTIAL};
        CBatchResult a = pvi_batch(st, rinputs, REST, NULL, 0);
        CBatchResult b = pvi_batch(rs, rinputs, REST, NULL, 0);
        int persist_ok = a.error == C_INDICATOR_ERROR_OK && b.error == C_INDICATOR_ERROR_OK &&
                         a.output_lens[0] == b.output_lens[0] &&
                         allclose(a.outputs[0], b.outputs[0], a.output_lens[0]);
        printf(persist_ok ? "  MATCH: deserialized state continues identically\n"
                          : "  MISMATCH detected!\n");
        tulip_ffi_batch_result_free(a);
        tulip_ffi_batch_result_free(b);
        pvi_state_free(st);
        pvi_state_free(rs);
    }

    printf("\n=== PVI: SIMD by assets (N=4) ===\n");
    {
        // Asset 1: original data.
        const double *const asset1[PVI_INPUTS] = {close, volume};

        // Asset 2: scaled up (+20%).
        double close_2[TOTAL], volume_2[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            close_2[i] = close[i] * 1.2;
            volume_2[i] = volume[i] * 1.2;
        }
        const double *const asset2[PVI_INPUTS] = {close_2, volume_2};

        // Asset 3: different upward trend.
        double close_3[TOTAL], volume_3[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            close_3[i] = 90.0 + (double)i * 0.5 + close[i] * 0.1;
            volume_3[i] = 90.0 + (double)i * 0.5 + volume[i] * 0.1;
        }
        const double *const asset3[PVI_INPUTS] = {close_3, volume_3};

        // Asset 4: downward trend.
        double close_4[TOTAL], volume_4[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            close_4[i] = 100.0 - (double)i * 0.3 + close[i] * 0.05;
            volume_4[i] = 100.0 - (double)i * 0.3 + volume[i] * 0.05;
        }
        const double *const asset4[PVI_INPUTS] = {close_4, volume_4};

        // simd_inputs is indexed by asset (the N=4 SIMD lanes), NOT by input
        // series -- hence [4] here stays a lane count.
        const double *const *const simd_inputs[4] = {asset1, asset2, asset3, asset4};

        CSimdResult r = pvi_simd_by_assets(simd_inputs, 4, TOTAL, options, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "pvi_simd_by_assets failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            printf("Asset %zu ", i + 1);
            print_row("pvi", r.outputs[i][0], r.output_lens[i][0]);
        }

        printf("\nVerification - calculating each asset individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = pvi_indicator(
                simd_inputs[i], TOTAL, options, NULL, 0);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "pvi_indicator (asset %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            printf("  Asset %zu: %s\n", i + 1, match ? "MATCH" : "MISMATCH");
            if (!match) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            pvi_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) pvi_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-assets equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    // Note: PVI has no options, so simd_by_options is NOT available.
    printf("\n=== PVI: No SIMD by-options (PVI has zero options) ===\n");

    return 0;
}
