// Shared C declarations for tulip_rs_ffi examples. Mirrors the extern "C"
// surface defined in src/common.rs, src/adosc.rs, src/macd.rs.
//
// This header is hand-written (not generated) since tulip_rs_ffi is a
// hand-rolled FFI wrapper, not a codegen'd binding.
//
// Parameter order convention: every pointer parameter is immediately
// followed by the count(s) that describe it, e.g.
// `inputs, data_len, options, ..., optional_outputs, num_optional`.

#ifndef TULIP_RS_FFI_H
#define TULIP_RS_FFI_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// Per-indicator INPUTS/OPTIONS counts (ADOSC_INPUTS, ADOSC_OPTIONS, ...) are
// generated by ../build.rs from the real `tulip_rs::indicators::<name>::
// {INPUTS, OPTIONS}` constants -- run `cargo build` at least once before
// compiling these examples so tulip_rs_ffi_counts.h exists here.
#include "tulip_rs_ffi_counts.h"

typedef enum {
    C_OK = 0,
    C_INVALID_INPUTS = 1,
    C_NOT_ENOUGH_DATA = 2,
    C_INVALID_OPTIONS = 3,
    C_INVALID_INDICATOR_STATE = 4,
} CIndicatorError;

typedef struct {
    CIndicatorError error;
    double **outputs;
    size_t *output_lens;
    size_t num_outputs;
    void *state;
} CIndicatorResult;

typedef struct {
    CIndicatorError error;
    double **outputs;
    size_t *output_lens;
    size_t num_outputs;
} CBatchResult;

// Result of a *_simd_by_assets()/*_simd_by_options() call: num_results
// parallel results, each with its own output rows and its own ordinary
// indicator state (reusable with the matching indicator's *_batch()/
// *_state_free() functions -- there's no separate SIMD state type).
typedef struct {
    CIndicatorError error;
    double ***outputs;      // [num_results][num_outputs] -> f64 row
    size_t **output_lens;   // [num_results][num_outputs] -> row length
    size_t num_outputs;     // output rows per result
    void **states;          // [num_results] opaque state handles
    size_t num_results;     // N: number of assets or option sets
} CSimdResult;

extern void tulip_ffi_result_free(CIndicatorResult result);
extern void tulip_ffi_batch_result_free(CBatchResult result);
// Frees outputs/output_lens and the outer `states` array wrapper, but NOT
// the individual state pointers in `states[i]` -- free each of those first
// with the matching indicator's `*_state_free()`.
extern void tulip_ffi_simd_result_free(CSimdResult result);

// Tulip-Indicators-style signatures: inputs is an array of pointers (one
// per input series), options is a flat array -- e.g. compare to
// https://tulipindicators.org/adosc's `ti_adosc(data_len, inputs, options, outputs)`.
extern CIndicatorResult adosc_indicator(
    double const *const *inputs, size_t data_len, double const *options,
    bool const *optional_outputs, size_t num_optional);
extern CBatchResult adosc_batch(
    void *state, double const *const *inputs, size_t data_len,
    bool const *optional_outputs, size_t num_optional);
extern void adosc_state_free(void *state);

// SIMD: N assets, one shared options array. num_assets must be 2, 4, 8, or 16.
extern CSimdResult adosc_simd_by_assets(
    double const *const *const *inputs, size_t num_assets, size_t data_len,
    double const *options, bool const *optional_outputs, size_t num_optional);
// SIMD: one asset, N option sets. num_option_sets must be 2, 4, 8, or 16.
extern CSimdResult adosc_simd_by_options(
    double const *const *inputs, size_t data_len, double const *const *options,
    size_t num_option_sets, bool const *optional_outputs, size_t num_optional);

extern CIndicatorResult macd_indicator(
    double const *const *inputs, size_t data_len, double const *options,
    bool const *optional_outputs, size_t num_optional);
extern CBatchResult macd_batch(
    void *state, double const *const *inputs, size_t data_len,
    bool const *optional_outputs, size_t num_optional);
extern void macd_state_free(void *state);

// SIMD: N assets, one shared options array. num_assets must be 2, 4, 8, or 16.
extern CSimdResult macd_simd_by_assets(
    double const *const *const *inputs, size_t num_assets, size_t data_len,
    double const *options, bool const *optional_outputs, size_t num_optional);
// SIMD: one asset, N option sets. num_option_sets must be 2, 4, 8, or 16.
extern CSimdResult macd_simd_by_options(
    double const *const *inputs, size_t data_len, double const *const *options,
    size_t num_option_sets, bool const *optional_outputs, size_t num_optional);

// ---- Candlestick ----
// Unlike every other indicator here, candlestick output is not numeric
// rows: each output bar carries zero or more matched pattern ids,
// CSR-packed into `bar_offsets`/`pattern_ids` (the patterns on bar i are
// pattern_ids[bar_offsets[i] .. bar_offsets[i+1]]; empty = no pattern).
// Resolve ids via candlestick_pattern_info()/candlestick_pattern_names().
// Candlestick is scalar-only (no *_simd_* entry points) and has no
// optional outputs.

typedef enum {
    C_FORECAST_BEARISH_REVERSAL = 0,
    C_FORECAST_BULLISH_REVERSAL = 1,
    C_FORECAST_BEARISH_CONTINUATION = 2,
    C_FORECAST_BULLISH_CONTINUATION = 3,
    C_FORECAST_BEARISH_REVERSAL_OR_CONTINUATION = 4,
    C_FORECAST_BULLISH_REVERSAL_OR_CONTINUATION = 5,
} CForecastType;

// A C array of null-terminated strings. Backing memory is leaked,
// process-lifetime: read it, do not free it.
typedef struct {
    const char *const *ptr;
    size_t len;
} CStringArray;

// Metadata for one candlestick pattern (the Rust/Python `get_info()` dict).
// All strings are leaked, process-lifetime: read them, do not free them.
// Out-of-range ids return id == UINT32_MAX with null strings.
typedef struct {
    uint32_t id;
    const char *name;
    const char *full_name;
    const char *japanese_name;
    CForecastType forecast;
    uint32_t bars;
} CCandlePatternInfo;

// Result of candlestick_indicator(): CSR pattern output plus an opaque
// continuation state (free buffers with candlestick_result_free(), the
// state separately with candlestick_state_free()).
typedef struct {
    CIndicatorError error;
    size_t num_bars;        // number of output bars
    size_t total_patterns;  // entries in pattern_ids
    uint32_t *bar_offsets;  // num_bars + 1 row offsets into pattern_ids
    uint32_t *pattern_ids;  // total_patterns pattern table ids
    void *state;            // opaque continuation state (NULL on error)
} CCandleStickResult;

// Result of candlestick_batch(): same CSR layout, no state (mutated in place).
typedef struct {
    CIndicatorError error;
    size_t num_bars;
    size_t total_patterns;
    uint32_t *bar_offsets;
    uint32_t *pattern_ids;
} CCandleStickBatchResult;

extern size_t candlestick_min_data(const double *options);
extern size_t candlestick_num_patterns(void);
extern CCandlePatternInfo candlestick_pattern_info(uint32_t id);
extern CStringArray candlestick_pattern_names(void);

// inputs: 4 series (open, high, low, close), each data_len long.
// options: 3 values (candle_period, trend_period, trend_signal_period).
// forecast: 0..=5 filters to that CForecastType; -1 (or any other value)
// returns all detected patterns.
extern CCandleStickResult candlestick_indicator(
    double const *const *inputs, size_t data_len, double const *options,
    int32_t forecast);
extern CCandleStickBatchResult candlestick_batch(
    void *state, double const *const *inputs, size_t data_len, int32_t forecast);

extern void candlestick_result_free(CCandleStickResult result);
extern void candlestick_batch_result_free(CCandleStickBatchResult result);
extern void candlestick_state_free(void *state);

#endif // TULIP_RS_FFI_H
