// VWAP (Volume Weighted Average Price) example for tulip_rs_ffi.
// Mirrors tulip_rs_python/examples/ti_vwap_example.py: same sample data,
// same options, same "compute partial, continue via batch, verify against a
// full recompute" flow, plus SIMD by-assets demonstration.
//
// Note: VWAP has 0 options (OPTIONS_WIDTH=0), so SIMD by-options is not available.
//
// VWAP_INPUTS/VWAP_OPTIONS come from ../include/tulip_rs_ffi_counts.h,
// generated by ../build.rs from the real tulip_rs::indicators::vwap::
// {INPUTS, OPTIONS} constants (run `cargo build` at least once so that file
// exists/is current). The main header is the cbindgen-generated one in
// ../include/, which is the up-to-date API surface.
//
// Build (from the tulip_rs_ffi directory):
//   cc -O2 -o vwap_example examples/vwap_example.c \
//       -L target/release -ltulip_rs_ffi -Wl,-rpath,target/release
// Run:
//   ./vwap_example

#include <stdio.h>
#include <stdlib.h>

#include "../include/tulip_rs_ffi.h"

static const double high[] = {82.15, 81.89, 83.03, 83.30, 83.85, 83.90, 83.33, 84.30,
                              84.84, 85.00, 85.90, 86.58, 86.98, 88.00, 87.87, 88.20,
                              88.70, 89.10, 88.50, 89.00, 89.60, 89.90, 89.30, 90.10,
                              90.50, 91.00, 90.30, 91.00, 91.60, 92.00, 91.30, 92.00,
                              92.60, 93.00, 92.30, 93.00, 93.60, 94.00, 93.30, 94.10};
static const double low[] = {81.29, 80.64, 81.31, 82.65, 83.07, 83.11, 82.49, 82.30,
                             84.15, 84.11, 84.03, 85.39, 85.76, 87.17, 87.01, 87.20,
                             87.80, 88.20, 87.60, 88.00, 88.60, 88.90, 88.30, 89.00,
                             89.40, 89.80, 89.20, 89.90, 90.50, 90.80, 90.20, 90.90,
                             91.50, 91.80, 91.20, 91.90, 92.50, 92.80, 92.20, 92.90};
static const double close[] = {81.59, 81.06, 82.87, 83.00, 83.61, 83.15, 82.84, 83.99,
                               84.55, 84.36, 85.53, 86.54, 86.89, 87.77, 87.29, 87.50,
                               88.10, 88.50, 87.90, 88.20, 88.80, 89.10, 88.70, 89.30,
                               89.70, 90.10, 89.50, 90.20, 90.80, 91.10, 90.50, 91.20,
                               91.80, 92.10, 91.50, 92.20, 92.80, 93.10, 92.50, 93.20};
static const double volume[] = {5653100, 6447400, 7690900, 3831400, 4455100,
                                3798000, 3936200, 4732000, 4841300, 3915300,
                                6830800, 6694100, 5293600, 7985800, 4807900,
                                5100000, 5300000, 4900000, 5200000, 4800000,
                                5600000, 5800000, 5400000, 6000000, 6200000,
                                5800000, 6400000, 6600000, 6200000, 6800000,
                                7000000, 6600000, 7200000, 7400000, 7000000,
                                7600000, 7800000, 7400000, 8000000, 8200000};

#define TOTAL 40
#define PARTIAL (TOTAL - 5)
#define REST (TOTAL - PARTIAL)

static void print_row(const char *label, const double *row, size_t len) {
    printf("  %-14s: [", label);
    for (size_t i = 0; i < len; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < len) printf(", ");
    }
    printf("]\n");
}

static void print_row_head(const char *label, const double *row, size_t len, size_t max_print) {
    printf("  %-14s: [", label);
    size_t n = len < max_print ? len : max_print;
    for (size_t i = 0; i < n; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < n) printf(", ");
    }
    printf(len > max_print ? ", ...]\n" : "]\n");
}

static int allclose(const double *a, const double *b, size_t len) {
    for (size_t i = 0; i < len; i++) {
        double diff = a[i] - b[i];
        if (diff < 0) diff = -diff;
        if (diff > 1e-9) return 0;
    }
    return 1;
}

int main(void) {
    const double options[VWAP_OPTIONS] = {}; // no options
    double full_vwap[TOTAL];
    size_t full_vwap_len = 0;

    CIndicatorInfo info = vwap_info();
    printf("=== %s (%s) ===\n", info.name, info.full_name);
    printf("Inputs: %u, Options: %u (none), Optional outputs: %u\n",
           (unsigned)VWAP_INPUTS, (unsigned)VWAP_OPTIONS,
           (unsigned)info.optional_outputs.len);
    printf("Minimum data required: %zu\n", vwap_min_data(options));

    printf("\n=== VWAP: full calculation (all optional outputs) ===\n");
    {
        const double *inputs[VWAP_INPUTS] = {high, low, close, volume};
        bool optional_outputs[1] = {true}; // typprice

        CIndicatorResult r = vwap_indicator(inputs, TOTAL, options, optional_outputs, 1);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "vwap_indicator failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_outputs=%zu\n", r.num_outputs);
        print_row("vwap", r.outputs[0], r.output_lens[0]);
        if (r.num_outputs > 1) {
            print_row("typprice", r.outputs[1], r.output_lens[1]);
        }

        // Keep a copy of the mandatory "vwap" row for later verification.
        full_vwap_len = r.output_lens[0];
        for (size_t i = 0; i < full_vwap_len; i++) full_vwap[i] = r.outputs[0][i];

        void *unused_state = r.state;
        tulip_ffi_result_free(r);
        vwap_state_free(unused_state);
    }

    printf("\n=== VWAP: partial calculation + batch continuation ===\n");
    {
        const double *partial_inputs[VWAP_INPUTS] = {high, low, close, volume};
        CIndicatorResult pr = vwap_indicator(partial_inputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "vwap_indicator (partial) failed: error=%d\n", pr.error);
            return 1;
        }
        print_row("vwap (partial)", pr.outputs[0], pr.output_lens[0]);
        void *state = pr.state;
        tulip_ffi_result_free(pr); // outputs freed; state kept alive

        const double *rest_inputs[VWAP_INPUTS] = {
            high + PARTIAL, low + PARTIAL, close + PARTIAL, volume + PARTIAL};
        CBatchResult br = vwap_batch(state, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "vwap_batch failed: error=%d\n", br.error);
            return 1;
        }
        print_row("vwap (continued)", br.outputs[0], br.output_lens[0]);

        printf("\n=== Verification: partial+continued vs. full recompute ===\n");
        int ok = 1;
        size_t continued_len = br.output_lens[0];
        size_t tail_start = full_vwap_len - continued_len;
        for (size_t i = 0; i < continued_len; i++) {
            double a = full_vwap[tail_start + i];
            double b = br.outputs[0][i];
            double diff = a > b ? a - b : b - a;
            if (diff > 1e-9) {
                ok = 0;
                printf("  mismatch at %zu: full=%.6f continued=%.6f\n", i, a, b);
            }
        }
        printf(ok ? "  MATCH: partial+continued vwap equals full recompute\n"
                  : "  MISMATCH detected!\n");

        tulip_ffi_batch_result_free(br);
        vwap_state_free(state);
    }

    printf("\n=== VWAP: state persistence (serialize / deserialize) ===\n");
    {
        const double *pinputs[VWAP_INPUTS] = {high, low, close, volume};
        CIndicatorResult pr = vwap_indicator(pinputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) { fprintf(stderr, "vwap_indicator failed\n"); return 1; }
        void *st = pr.state;
        tulip_ffi_result_free(pr);

        CBytes blob = tulip_state_serialize(C_INDICATOR_ID_VWAP, C_STATE_FORMAT_BINCODE, st);
        if (blob.ptr == NULL) { fprintf(stderr, "serialize failed\n"); return 1; }
        printf("  blob: %zu bytes, magic=%.4s, name=%.32s\n",
               blob.len, (const char *)blob.ptr, (const char *)blob.ptr + 6);

        void *rs = tulip_state_deserialize(blob.ptr, blob.len);
        tulip_ffi_bytes_free(blob);
        if (rs == NULL) { fprintf(stderr, "deserialize failed\n"); return 1; }

        const double *rinputs[VWAP_INPUTS] = {high + PARTIAL, low + PARTIAL, close + PARTIAL, volume + PARTIAL};
        CBatchResult a = vwap_batch(st, rinputs, REST, NULL, 0);
        CBatchResult b = vwap_batch(rs, rinputs, REST, NULL, 0);
        int persist_ok = a.error == C_INDICATOR_ERROR_OK && b.error == C_INDICATOR_ERROR_OK &&
                         a.output_lens[0] == b.output_lens[0] &&
                         allclose(a.outputs[0], b.outputs[0], a.output_lens[0]);
        printf(persist_ok ? "  MATCH: deserialized state continues identically\n"
                          : "  MISMATCH detected!\n");
        tulip_ffi_batch_result_free(a);
        tulip_ffi_batch_result_free(b);
        vwap_state_free(st);
        vwap_state_free(rs);
    }

    printf("\n=== VWAP: SIMD by assets (N=4) ===\n");
    {
        // Asset 1: original data.
        const double *const asset1[VWAP_INPUTS] = {high, low, close, volume};

        // Asset 2: scaled up price (+20%), volume (+10%).
        double high_2[TOTAL], low_2[TOTAL], close_2[TOTAL], volume_2[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_2[i] = high[i] * 1.2;
            low_2[i] = low[i] * 1.2;
            close_2[i] = close[i] * 1.2;
            volume_2[i] = volume[i] * 1.1;
        }
        const double *const asset2[VWAP_INPUTS] = {high_2, low_2, close_2, volume_2};

        // Asset 3: different upward trend (price), volume scaled (-10%).
        double high_3[TOTAL], low_3[TOTAL], close_3[TOTAL], volume_3[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_3[i] = 90.0 + (double)i * 0.5 + high[i] * 0.1;
            low_3[i] = 90.0 + (double)i * 0.5 + low[i] * 0.1;
            close_3[i] = 90.0 + (double)i * 0.5 + close[i] * 0.1;
            volume_3[i] = volume[i] * 0.9;
        }
        const double *const asset3[VWAP_INPUTS] = {high_3, low_3, close_3, volume_3};

        // Asset 4: downward trend (price), volume scaled (+30%).
        double high_4[TOTAL], low_4[TOTAL], close_4[TOTAL], volume_4[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_4[i] = 100.0 - (double)i * 0.3 + high[i] * 0.05;
            low_4[i] = 100.0 - (double)i * 0.3 + low[i] * 0.05;
            close_4[i] = 100.0 - (double)i * 0.3 + close[i] * 0.05;
            volume_4[i] = volume[i] * 1.3;
        }
        const double *const asset4[VWAP_INPUTS] = {high_4, low_4, close_4, volume_4};

        // simd_inputs is indexed by asset (the N=4 SIMD lanes), NOT by input
        // series -- hence [4] here stays a lane count.
        const double *const *const simd_inputs[4] = {asset1, asset2, asset3, asset4};
        bool optional_outputs[1] = {true};

        CSimdResult r = vwap_simd_by_assets(simd_inputs, 4, TOTAL, options, optional_outputs, 1);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "vwap_simd_by_assets failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            printf("Asset %zu ", i + 1);
            print_row("vwap", r.outputs[i][0], r.output_lens[i][0]);
        }

        printf("\nVerification - calculating each asset individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = vwap_indicator(
                simd_inputs[i], TOTAL, options, optional_outputs, 1);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "vwap_indicator (asset %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            printf("  Asset %zu: %s\n", i + 1, match ? "MATCH" : "MISMATCH");
            if (!match) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            vwap_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) vwap_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-assets equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    // Note: VWAP has 0 options, so SIMD by-options is not available.
    printf("\n=== VWAP: SIMD by options ===\n");
    printf("Note: VWAP has OPTIONS_WIDTH=0 (no options), so SIMD by-options is not implemented.\n");

    return 0;
}
