// WAD (Williams Accumulation/Distribution) example for tulip_rs_ffi.
// Mirrors tulip_rs_python/examples/ti_wad_example.py: same sample data,
// same options, same "compute partial, continue via batch, verify against a
// full recompute" flow, plus SIMD by-assets/by-options demonstrations.
//
// WAD_INPUTS/WAD_OPTIONS come from ../include/tulip_rs_ffi_counts.h,
// generated by ../build.rs from the real tulip_rs::indicators::wad::
// {INPUTS, OPTIONS} constants (run `cargo build` at least once so that file
// exists/is current). The main header is the cbindgen-generated one in
// ../include/, which is the up-to-date API surface.
//
// Note: WAD has 0 options and does NOT support SIMD by-options.
//
// Build (from the tulip_rs_ffi directory):
//   cc -O2 -o wad_example examples/wad_example.c \
//       -L target/release -ltulip_rs_ffi -Wl,-rpath,target/release
// Run:
//   ./wad_example

#include <stdio.h>
#include <stdlib.h>

#include "../include/tulip_rs_ffi.h"

static const double high[] = {82.15, 81.89, 83.03, 83.30, 83.85, 83.90, 83.33, 84.30, 84.84, 85.00, 85.90, 86.58, 86.98, 88.00, 87.87};
static const double low[]  = {81.29, 80.64, 81.31, 82.65, 83.07, 83.11, 82.49, 82.30, 84.15, 84.11, 84.03, 85.39, 85.76, 87.17, 87.01};
static const double close[] = {81.59, 81.06, 82.87, 83.00, 83.61, 83.15, 82.84, 83.99, 84.55, 84.36, 85.53, 86.54, 86.89, 87.77, 87.29};

#define TOTAL 15
#define PARTIAL (TOTAL - 5)
#define REST (TOTAL - PARTIAL)

static void print_row(const char *label, const double *row, size_t len) {
    printf("  %-14s: [", label);
    for (size_t i = 0; i < len; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < len) printf(", ");
    }
    printf("]\n");
}

static void print_row_head(const char *label, const double *row, size_t len, size_t max_print) {
    printf("  %-14s: [", label);
    size_t n = len < max_print ? len : max_print;
    for (size_t i = 0; i < n; i++) {
        printf("%.4f", row[i]);
        if (i + 1 < n) printf(", ");
    }
    printf(len > max_print ? ", ...]\n" : "]\n");
}

static int allclose(const double *a, const double *b, size_t len) {
    for (size_t i = 0; i < len; i++) {
        double diff = a[i] - b[i];
        if (diff < 0) diff = -diff;
        if (diff > 1e-9) return 0;
    }
    return 1;
}

int main(void) {
    const double options[WAD_OPTIONS] = {}; // no options
    double full_wad[TOTAL];
    size_t full_wad_len = 0;

    CIndicatorInfo info = wad_info();
    printf("=== %s (%s) ===\n", info.name, info.full_name);
    printf("Inputs: %u, Options: %u (none), Optional outputs: %u\n",
           (unsigned)WAD_INPUTS, (unsigned)WAD_OPTIONS,
           (unsigned)info.optional_outputs.len);
    printf("Minimum data required: %zu\n", wad_min_data(options));

    printf("\n=== WAD: full calculation ===\n");
    {
        const double *inputs[WAD_INPUTS] = {high, low, close};

        CIndicatorResult r = wad_indicator(inputs, TOTAL, options, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "wad_indicator failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_outputs=%zu\n", r.num_outputs);
        print_row("wad", r.outputs[0], r.output_lens[0]);

        // Keep a copy of the mandatory "wad" row for later verification.
        full_wad_len = r.output_lens[0];
        for (size_t i = 0; i < full_wad_len; i++) full_wad[i] = r.outputs[0][i];

        void *unused_state = r.state;
        tulip_ffi_result_free(r);
        wad_state_free(unused_state);
    }

    printf("\n=== WAD: partial calculation + batch continuation ===\n");
    {
        const double *partial_inputs[WAD_INPUTS] = {high, low, close};
        CIndicatorResult pr = wad_indicator(partial_inputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "wad_indicator (partial) failed: error=%d\n", pr.error);
            return 1;
        }
        print_row("wad (partial)", pr.outputs[0], pr.output_lens[0]);
        void *state = pr.state;
        tulip_ffi_result_free(pr); // outputs freed; state kept alive

        const double *rest_inputs[WAD_INPUTS] = {high + PARTIAL, low + PARTIAL, close + PARTIAL};
        CBatchResult br = wad_batch(state, rest_inputs, REST, NULL, 0);
        if (br.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "wad_batch failed: error=%d\n", br.error);
            return 1;
        }
        print_row("wad (continued)", br.outputs[0], br.output_lens[0]);

        printf("\n=== Verification: partial+continued vs. full recompute ===\n");
        int ok = 1;
        size_t continued_len = br.output_lens[0];
        size_t tail_start = full_wad_len - continued_len;
        for (size_t i = 0; i < continued_len; i++) {
            double a = full_wad[tail_start + i];
            double b = br.outputs[0][i];
            double diff = a > b ? a - b : b - a;
            if (diff > 1e-9) {
                ok = 0;
                printf("  mismatch at %zu: full=%.6f continued=%.6f\n", i, a, b);
            }
        }
        printf(ok ? "  MATCH: partial+continued wad equals full recompute\n"
                  : "  MISMATCH detected!\n");

        tulip_ffi_batch_result_free(br);
        wad_state_free(state);
    }

    printf("\n=== WAD: state persistence (serialize / deserialize) ===\n");
    {
        const double *pinputs[WAD_INPUTS] = {high, low, close};
        CIndicatorResult pr = wad_indicator(pinputs, PARTIAL, options, NULL, 0);
        if (pr.error != C_INDICATOR_ERROR_OK) { fprintf(stderr, "wad_indicator failed\n"); return 1; }
        void *st = pr.state;
        tulip_ffi_result_free(pr);

        CBytes blob = tulip_state_serialize(C_INDICATOR_ID_WAD, C_STATE_FORMAT_BINCODE, st);
        if (blob.ptr == NULL) { fprintf(stderr, "serialize failed\n"); return 1; }
        printf("  blob: %zu bytes, magic=%.4s, name=%.32s\n",
               blob.len, (const char *)blob.ptr, (const char *)blob.ptr + 6);

        void *rs = tulip_state_deserialize(blob.ptr, blob.len);
        tulip_ffi_bytes_free(blob);
        if (rs == NULL) { fprintf(stderr, "deserialize failed\n"); return 1; }

        const double *rinputs[WAD_INPUTS] = {high + PARTIAL, low + PARTIAL, close + PARTIAL};
        CBatchResult a = wad_batch(st, rinputs, REST, NULL, 0);
        CBatchResult b = wad_batch(rs, rinputs, REST, NULL, 0);
        int persist_ok = a.error == C_INDICATOR_ERROR_OK && b.error == C_INDICATOR_ERROR_OK &&
                         a.output_lens[0] == b.output_lens[0] &&
                         allclose(a.outputs[0], b.outputs[0], a.output_lens[0]);
        printf(persist_ok ? "  MATCH: deserialized state continues identically\n"
                          : "  MISMATCH detected!\n");
        tulip_ffi_batch_result_free(a);
        tulip_ffi_batch_result_free(b);
        wad_state_free(st);
        wad_state_free(rs);
    }

    printf("\n=== WAD: SIMD by assets (N=4) ===\n");
    {
        // Asset 1: original data.
        const double *const asset1[WAD_INPUTS] = {high, low, close};

        // Asset 2: scaled up (+20%).
        double high_2[TOTAL], low_2[TOTAL], close_2[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_2[i] = high[i] * 1.2;
            low_2[i] = low[i] * 1.2;
            close_2[i] = close[i] * 1.2;
        }
        const double *const asset2[WAD_INPUTS] = {high_2, low_2, close_2};

        // Asset 3: different upward trend.
        double high_3[TOTAL], low_3[TOTAL], close_3[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_3[i] = 90.0 + (double)i * 0.5 + high[i] * 0.1;
            low_3[i] = 90.0 + (double)i * 0.5 + low[i] * 0.1;
            close_3[i] = 90.0 + (double)i * 0.5 + close[i] * 0.1;
        }
        const double *const asset3[WAD_INPUTS] = {high_3, low_3, close_3};

        // Asset 4: downward trend.
        double high_4[TOTAL], low_4[TOTAL], close_4[TOTAL];
        for (size_t i = 0; i < TOTAL; i++) {
            high_4[i] = 100.0 - (double)i * 0.3 + high[i] * 0.05;
            low_4[i] = 100.0 - (double)i * 0.3 + low[i] * 0.05;
            close_4[i] = 100.0 - (double)i * 0.3 + close[i] * 0.05;
        }
        const double *const asset4[WAD_INPUTS] = {high_4, low_4, close_4};

        // simd_inputs is indexed by asset (the N=4 SIMD lanes), NOT by input
        // series -- hence [4] here stays a lane count.
        const double *const *const simd_inputs[4] = {asset1, asset2, asset3, asset4};

        CSimdResult r = wad_simd_by_assets(simd_inputs, 4, TOTAL, options, NULL, 0);
        if (r.error != C_INDICATOR_ERROR_OK) {
            fprintf(stderr, "wad_simd_by_assets failed: error=%d\n", r.error);
            return 1;
        }
        printf("num_results=%zu, num_outputs=%zu\n", r.num_results, r.num_outputs);
        for (size_t i = 0; i < r.num_results; i++) {
            printf("Asset %zu ", i + 1);
            print_row("wad", r.outputs[i][0], r.output_lens[i][0]);
        }

        printf("\nVerification - calculating each asset individually:\n");
        int simd_ok = 1;
        for (size_t i = 0; i < r.num_results; i++) {
            CIndicatorResult ind = wad_indicator(
                simd_inputs[i], TOTAL, options, NULL, 0);
            if (ind.error != C_INDICATOR_ERROR_OK) {
                fprintf(stderr, "wad_indicator (asset %zu) failed: error=%d\n", i + 1, ind.error);
                simd_ok = 0;
                continue;
            }
            int match = allclose(r.outputs[i][0], ind.outputs[0], r.output_lens[i][0]);
            printf("  Asset %zu: %s\n", i + 1, match ? "MATCH" : "MISMATCH");
            if (!match) simd_ok = 0;

            void *ind_state = ind.state;
            tulip_ffi_result_free(ind);
            wad_state_free(ind_state);
        }

        for (size_t i = 0; i < r.num_results; i++) wad_state_free(r.states[i]);
        tulip_ffi_simd_result_free(r);
        printf(simd_ok ? "  ALL MATCH: SIMD by-assets equals individual calculation\n"
                       : "  MISMATCH detected!\n");
    }

    // WAD has 0 options, so SIMD by-options is not available.
    printf("\n=== WAD: SIMD by options ===\n");
    printf("  N/A: WAD has 0 options and does not support simd_by_options.\n");

    return 0;
}
