// Auto-generated by tulip_rs_ffi/build.rs. Do not edit by hand.
//
// Indicator ids for tulip_state_serialize()/tulip_state_clone().
// Each value is fnv1a32(<lowercase indicator name>) and is stable for the
// lifetime of that name: adding indicators never renumbers existing ids.
// Serialized state blobs embed the name itself (TRFS header), so ids are
// an API convenience, not the wire authority.

#ifndef TULIP_RS_FFI_STATE_IDS_H
#define TULIP_RS_FFI_STATE_IDS_H

#define C_INDICATOR_ID_AD 0x4724fc58 /* fnv1a32("ad") */
#define C_INDICATOR_ID_ADAPTIVEMSW 0xf9aafa3c /* fnv1a32("adaptivemsw") */
#define C_INDICATOR_ID_ADOSC 0x563a9e3 /* fnv1a32("adosc") */
#define C_INDICATOR_ID_ADX 0x1f38e660 /* fnv1a32("adx") */
#define C_INDICATOR_ID_ADXR 0x38922e56 /* fnv1a32("adxr") */
#define C_INDICATOR_ID_AO 0x4224f479 /* fnv1a32("ao") */
#define C_INDICATOR_ID_APO 0x366aa761 /* fnv1a32("apo") */
#define C_INDICATOR_ID_AROON 0x2e9284a /* fnv1a32("aroon") */
#define C_INDICATOR_ID_AROONOSC 0xf9bf1045 /* fnv1a32("aroonosc") */
#define C_INDICATOR_ID_ATR 0x2961988e /* fnv1a32("atr") */
#define C_INDICATOR_ID_AVGPRICE 0x6be6cb94 /* fnv1a32("avgprice") */
#define C_INDICATOR_ID_BBANDS 0x88222d0f /* fnv1a32("bbands") */
#define C_INDICATOR_ID_BOP 0x78c68aca /* fnv1a32("bop") */
#define C_INDICATOR_ID_CANDLESTICK 0xdf26b608 /* fnv1a32("candlestick") */
#define C_INDICATOR_ID_CCFISHER 0x9a6bedaa /* fnv1a32("ccfisher") */
#define C_INDICATOR_ID_CCI 0xed6fb77e /* fnv1a32("cci") */
#define C_INDICATOR_ID_CHAIKINMF 0x214268ed /* fnv1a32("chaikinmf") */
#define C_INDICATOR_ID_CHANDELIEREXIT 0x6dd369de /* fnv1a32("chandelierexit") */
#define C_INDICATOR_ID_CMO 0xef924ce6 /* fnv1a32("cmo") */
#define C_INDICATOR_ID_CVI 0xf14f6a1f /* fnv1a32("cvi") */
#define C_INDICATOR_ID_CYBERCYCLE 0x270c53fc /* fnv1a32("cybercycle") */
#define C_INDICATOR_ID_DEMA 0xb8fd44f4 /* fnv1a32("dema") */
#define C_INDICATOR_ID_DI 0x601cd4ee /* fnv1a32("di") */
#define C_INDICATOR_ID_DM 0x641cdb3a /* fnv1a32("dm") */
#define C_INDICATOR_ID_DONCHIANCHANNEL 0x6f5a52f2 /* fnv1a32("donchianchannel") */
#define C_INDICATOR_ID_DPO 0xee2a60e2 /* fnv1a32("dpo") */
#define C_INDICATOR_ID_DX 0x511cbd51 /* fnv1a32("dx") */
#define C_INDICATOR_ID_EF 0x391a58f2 /* fnv1a32("ef") */
#define C_INDICATOR_ID_ELDERRAY 0xeb756059 /* fnv1a32("elderray") */
#define C_INDICATOR_ID_EMA 0x7f8ac522 /* fnv1a32("ema") */
#define C_INDICATOR_ID_EMV 0x6a8aa413 /* fnv1a32("emv") */
#define C_INDICATOR_ID_FISHER 0x45855c00 /* fnv1a32("fisher") */
#define C_INDICATOR_ID_FOSC 0x165ac3c0 /* fnv1a32("fosc") */
#define C_INDICATOR_ID_HIGHPASS 0x32aa3ad0 /* fnv1a32("highpass") */
#define C_INDICATOR_ID_HILBERTTRANSFORM 0x18e2d9df /* fnv1a32("hilberttransform") */
#define C_INDICATOR_ID_HMA 0xf7c819fd /* fnv1a32("hma") */
#define C_INDICATOR_ID_HOMODYNEDISCRIMINATOR 0xfcd31f7a /* fnv1a32("homodynediscriminator") */
#define C_INDICATOR_ID_ICHIMOKU 0x2efb4f1e /* fnv1a32("ichimoku") */
#define C_INDICATOR_ID_INSTANTANEOUSTRENDLINE 0xb2fc8596 /* fnv1a32("instantaneoustrendline") */
#define C_INDICATOR_ID_KAMA 0x42cb218f /* fnv1a32("kama") */
#define C_INDICATOR_ID_KELTNERCHANNEL 0x35db4b2d /* fnv1a32("keltnerchannel") */
#define C_INDICATOR_ID_KVO 0x76363221 /* fnv1a32("kvo") */
#define C_INDICATOR_ID_LINREG 0xafe110d2 /* fnv1a32("linreg") */
#define C_INDICATOR_ID_MACD 0xd09fc3a4 /* fnv1a32("macd") */
#define C_INDICATOR_ID_MAMA 0xc19b2ed9 /* fnv1a32("mama") */
#define C_INDICATOR_ID_MARKETFI 0xd5f01ad4 /* fnv1a32("marketfi") */
#define C_INDICATOR_ID_MASS 0xdf7738d1 /* fnv1a32("mass") */
#define C_INDICATOR_ID_MAX 0xd7a2e319 /* fnv1a32("max") */
#define C_INDICATOR_ID_MD 0x672e2914 /* fnv1a32("md") */
#define C_INDICATOR_ID_MEDPRICE 0xda23c85e /* fnv1a32("medprice") */
#define C_INDICATOR_ID_MFI 0xe6afc6a9 /* fnv1a32("mfi") */
#define C_INDICATOR_ID_MIN 0xc98f4557 /* fnv1a32("min") */
#define C_INDICATOR_ID_MOM 0xe69e7d88 /* fnv1a32("mom") */
#define C_INDICATOR_ID_MSW 0xd08045d2 /* fnv1a32("msw") */
#define C_INDICATOR_ID_NATR 0xadfb891a /* fnv1a32("natr") */
#define C_INDICATOR_ID_NVI 0x12791fc4 /* fnv1a32("nvi") */
#define C_INDICATOR_ID_OBV 0xab451766 /* fnv1a32("obv") */
#define C_INDICATOR_ID_PIVOTPOINT 0x4fe2b16f /* fnv1a32("pivotpoint") */
#define C_INDICATOR_ID_PPO 0x507f3e86 /* fnv1a32("ppo") */
#define C_INDICATOR_ID_PSAR 0x78f68ce7 /* fnv1a32("psar") */
#define C_INDICATOR_ID_PVI 0x6e706336 /* fnv1a32("pvi") */
#define C_INDICATOR_ID_QSTICK 0x1317555c /* fnv1a32("qstick") */
#define C_INDICATOR_ID_ROC 0x380e0a97 /* fnv1a32("roc") */
#define C_INDICATOR_ID_ROCR 0x231b267f /* fnv1a32("rocr") */
#define C_INDICATOR_ID_ROOFINGFILTER 0x7324db5b /* fnv1a32("roofingfilter") */
#define C_INDICATOR_ID_RSI 0x49dc8a21 /* fnv1a32("rsi") */
#define C_INDICATOR_ID_SMA 0xe93ac5d4 /* fnv1a32("sma") */
#define C_INDICATOR_ID_SMAENVELOPE 0xf630ea08 /* fnv1a32("smaenvelope") */
#define C_INDICATOR_ID_STDDEV 0x41229629 /* fnv1a32("stddev") */
#define C_INDICATOR_ID_STOCH 0xbf0c7edc /* fnv1a32("stoch") */
#define C_INDICATOR_ID_STOCHRSI 0x79c7cb36 /* fnv1a32("stochrsi") */
#define C_INDICATOR_ID_SUPERSMOOTHER 0x5a9e8325 /* fnv1a32("supersmoother") */
#define C_INDICATOR_ID_SUPERTREND 0xcf740313 /* fnv1a32("supertrend") */
#define C_INDICATOR_ID_TEMA 0xaf1ba504 /* fnv1a32("tema") */
#define C_INDICATOR_ID_TR 0x47455003 /* fnv1a32("tr") */
#define C_INDICATOR_ID_TRENDMODE 0xfbbbad43 /* fnv1a32("trendmode") */
#define C_INDICATOR_ID_TRIMA 0xc059e978 /* fnv1a32("trima") */
#define C_INDICATOR_ID_TRIX 0x68942752 /* fnv1a32("trix") */
#define C_INDICATOR_ID_TRVI 0x59afe632 /* fnv1a32("trvi") */
#define C_INDICATOR_ID_TSF 0xb519eca2 /* fnv1a32("tsf") */
#define C_INDICATOR_ID_TYPPRICE 0xd6324b9b /* fnv1a32("typprice") */
#define C_INDICATOR_ID_ULTOSC 0x13ab054b /* fnv1a32("ultosc") */
#define C_INDICATOR_ID_VHF 0x9014a80f /* fnv1a32("vhf") */
#define C_INDICATOR_ID_VIDYA 0xdd15a38a /* fnv1a32("vidya") */
#define C_INDICATOR_ID_VOLATILITY 0xbe155b9a /* fnv1a32("volatility") */
#define C_INDICATOR_ID_VORTEX 0xd8760e19 /* fnv1a32("vortex") */
#define C_INDICATOR_ID_VOSC 0x6574f8b0 /* fnv1a32("vosc") */
#define C_INDICATOR_ID_VWAP 0x8b807f03 /* fnv1a32("vwap") */
#define C_INDICATOR_ID_VWMA 0xa27615dc /* fnv1a32("vwma") */
#define C_INDICATOR_ID_WAD 0x21e2d343 /* fnv1a32("wad") */
#define C_INDICATOR_ID_WCPRICE 0x1cee7768 /* fnv1a32("wcprice") */
#define C_INDICATOR_ID_WILDERS 0xccdd160f /* fnv1a32("wilders") */
#define C_INDICATOR_ID_WILLR 0x48dd286d /* fnv1a32("willr") */
#define C_INDICATOR_ID_WMA 0xfced2660 /* fnv1a32("wma") */
#define C_INDICATOR_ID_ZLEMA 0xdb860ed4 /* fnv1a32("zlema") */

#endif // TULIP_RS_FFI_STATE_IDS_H
