//! Generic indicator-state serialization/deserialization for FFI.
//!
//! This module provides indicator-agnostic entry points to serialize and
//! deserialize the opaque state handles returned by `<name>_indicator()`,
//! so bindings in GC'd languages can persist streaming state (DB rows,
//! files) as opaque byte blobs and resume them later.
//!
//! Wire format (TRFS schema 2): fixed header followed by the encoded state:
//!   - magic: `[u8; 4]` = `*b"TRFS"` (Tulip FFI State)
//!   - schema version: `u8` = 2
//!   - format: `u8` (a `CStateFormat` discriminant)
//!   - indicator name: `[u8; 32]`, the canonical lowercase name,
//!     zero-padded (e.g. `b"adx"`)
//!   - payload: the encoded state, per `format`
//!
//! The NAME field -- not the numeric id -- is the authoritative wire
//! identity: deserialization dispatches entirely on the embedded name, so
//! `tulip_state_deserialize()` takes no indicator argument and a blob can
//! never be "cross-fed" a wrong type by argument mistake.
//!
//! `CIndicatorId`, its `TryFrom<u32>`, its name lookups and the three
//! concrete-type dispatchers are GENERATED by `build.rs` (see
//! `state_ids_generated.rs`) from the crate's indicator list. Ids are
//! `fnv1a32(<lowercase name>)`, a pure function of identity: adding or
//! removing indicators never renumbers an existing id, and list order
//! carries no wire meaning.
//!
//! Format selector is `CStateFormat` (Bincode or Json). The public API uses
//! `format: u32` parameters for C ABI compatibility; validation goes through
//! `CStateFormat::try_from(format)` so adding variants yields one obvious
//! dispatch point.
//!
//! # Format notes
//! - **bincode (`CStateFormat::Bincode`)**: Recommended for persistence.
//!   Compact, handles all f64 values including NaN/Inf.
//! - **JSON (`CStateFormat::Json`)**: Human-readable, for debugging and
//!   inspection. Fails on non-finite f64s (serde_json limitation).
//!
//! # Versioning
//! Schema 2 is the first published wire format (no deployed schema-1
//! blobs exist); blobs with any other version byte are rejected. If the
//! hash function or header layout ever changes, bump the version and
//! reject the old range here.

use serde::de::DeserializeOwned;
use serde::Serialize;
use std::os::raw::c_void;

/// Wire format selector for `tulip_state_serialize` (and the `format` byte
/// embedded in the blob header).
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CStateFormat {
    /// Compact binary encoding; recommended for persistence. Handles all
    /// f64 values including NaN/Inf.
    Bincode = 0,
    /// Human-readable JSON via serde_json, for debugging/inspection only:
    /// fails (null return) on non-finite f64s.
    Json = 1,
}

impl TryFrom<u32> for CStateFormat {
    type Error = ();

    fn try_from(value: u32) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(CStateFormat::Bincode),
            1 => Ok(CStateFormat::Json),
            _ => Err(()),
        }
    }
}

/// Wire format magic bytes.
const MAGIC: [u8; 4] = *b"TRFS";

/// Current schema version.
const SCHEMA_VERSION: u8 = 2;

/// Width of the zero-padded indicator-name field. MUST stay in sync with
/// `NAME_FIELD` in `build.rs` (which asserts every name fits it).
const NAME_FIELD: usize = 32;

/// Total fixed header size: magic(4) + version(1) + format(1) + name(32).
const HEADER_LEN: usize = 4 + 1 + 1 + NAME_FIELD;

// The generated enum CIndicatorId + TryFrom<u32> + ALL/name()/from_name()
// + serialize_dispatch()/deserialize_dispatch()/clone_dispatch(), one arm
// per indicator the crate wraps. Regenerated on every build; see build.rs.
include!("state_ids_generated.rs");

/// Build the fixed header for a serialized state blob.
fn header_bytes(id: CIndicatorId, fmt: CStateFormat) -> [u8; HEADER_LEN] {
    let mut header = [0u8; HEADER_LEN];
    header[0..4].copy_from_slice(&MAGIC);
    header[4] = SCHEMA_VERSION;
    header[5] = fmt as u8;
    let name = id.name();
    // build.rs asserts every name fits NAME_FIELD at generation time, so
    // a name here is always short enough; debug_assert documents the rest.
    debug_assert!(name.len() <= NAME_FIELD);
    header[6..6 + name.len()].copy_from_slice(name);
    header
}

/// Strip the zero padding from a header name field.
fn trim_name(name: &[u8]) -> &[u8] {
    let end = name.iter().rposition(|&b| b != 0).map_or(0, |i| i + 1);
    &name[..end]
}

/// Serialize a boxed indicator state into an opaque byte blob.
/// `state` is the `*mut c_void` handle from `<name>_indicator()` (READ ONLY
/// -- the state is not consumed). `indicator` must be the matching
/// `C_INDICATOR_ID_*` constant for that state's type. Returns
/// `CBytes { ptr: null }` on error. Free the blob with
/// `tulip_ffi_bytes_free`.
///
/// The blob is self-describing (it embeds the indicator name); pass it
/// straight to `tulip_state_deserialize` with no further arguments.
///
/// `format`: a `CStateFormat` discriminant (0 = Bincode, 1 = Json).
///
/// # Safety
/// `state` must be null, or a valid pointer previously returned by an
/// indicator's `<name>_indicator()` function (or `tulip_state_deserialize`/
/// `tulip_state_clone`) that matches `indicator` and has not been passed to
/// `<name>_state_free()` yet. The state is read-only (not consumed).
#[no_mangle]
pub unsafe extern "C" fn tulip_state_serialize(
    indicator: u32,
    format: u32,
    state: *const c_void,
) -> crate::common::CBytes {
    if state.is_null() {
        return crate::common::CBytes::null();
    }
    let id = match CIndicatorId::try_from(indicator) {
        Ok(id) => id,
        Err(_) => return crate::common::CBytes::null(),
    };
    let fmt = match CStateFormat::try_from(format) {
        Ok(fmt) => fmt,
        Err(_) => return crate::common::CBytes::null(),
    };
    serialize_dispatch(id, fmt, state)
}

/// Private helper for `serialize_dispatch` (generic over the concrete type).
/// All argument validation has already happened at this point.
unsafe fn serialize_state<S: Serialize>(
    id: CIndicatorId,
    fmt: CStateFormat,
    state: *const c_void,
) -> crate::common::CBytes {
    let s: &S = &*(state as *const S);
    let mut out: Vec<u8> = header_bytes(id, fmt).to_vec();
    let body = match fmt {
        CStateFormat::Bincode => bincode::serialize(s).ok(),
        CStateFormat::Json => serde_json::to_vec(s).ok(),
    };
    match body {
        Some(b) => {
            out.extend_from_slice(&b);
            crate::common::CBytes::from_vec(out)
        }
        None => crate::common::CBytes::null(),
    }
}

/// Reconstruct a boxed state from a blob produced by `tulip_state_serialize`.
/// The blob's header identifies the indicator (by name) and the encoding
/// format -- there is no indicator argument to mismatch. The returned
/// `*mut c_void` is indistinguishable from a fresh `<name>_indicator()`
/// state handle: use with `<name>_batch()` and release with
/// `<name>_state_free()`.
///
/// Returns null on error: null input, truncated data, bad magic, unknown
/// schema version, unknown format byte, unknown indicator name, or a
/// payload that fails to decode. Malformed input can never cause UB or a
/// panic -- only a null return.
///
/// # Safety
/// `bytes` must be null, or point to `len` readable bytes. Memory safety
/// holds for *any* contents; the validity requirement is only that the
/// pointer/len pair is dereferenceable.
#[no_mangle]
pub unsafe extern "C" fn tulip_state_deserialize(bytes: *const u8, len: usize) -> *mut c_void {
    if bytes.is_null() || len < HEADER_LEN {
        return std::ptr::null_mut();
    }

    let header: [u8; HEADER_LEN] = match std::slice::from_raw_parts(bytes, HEADER_LEN).try_into() {
        Ok(h) => h,
        Err(_) => return std::ptr::null_mut(), // unreachable given len check
    };

    if header[0..4] != MAGIC {
        return std::ptr::null_mut();
    }
    if header[4] != SCHEMA_VERSION {
        return std::ptr::null_mut();
    }
    let fmt = match CStateFormat::try_from(header[5] as u32) {
        Ok(fmt) => fmt,
        Err(_) => return std::ptr::null_mut(),
    };
    let id = match CIndicatorId::from_name(trim_name(&header[6..])) {
        Some(id) => id,
        None => return std::ptr::null_mut(),
    };

    deserialize_dispatch(id, fmt, bytes.add(HEADER_LEN), len - HEADER_LEN)
}

/// Private helper for `deserialize_dispatch` (generic over the concrete
/// type). Receives only the payload; the header (magic, version, format,
/// name) was validated by `tulip_state_deserialize`.
unsafe fn deserialize_state<S: DeserializeOwned>(
    fmt: CStateFormat,
    payload: *const u8,
    payload_len: usize,
) -> *mut c_void {
    let payload_slice = std::slice::from_raw_parts(payload, payload_len);
    let state: S = match fmt {
        CStateFormat::Bincode => match bincode::deserialize(payload_slice) {
            Ok(s) => s,
            Err(_) => return std::ptr::null_mut(),
        },
        CStateFormat::Json => match serde_json::from_slice(payload_slice) {
            Ok(s) => s,
            Err(_) => return std::ptr::null_mut(),
        },
    };
    Box::into_raw(Box::new(state)) as *mut c_void
}

/// Clone a boxed indicator state directly via Rust's `Clone` (core state
/// types all derive it -- no serde round-trip involved). Returns null on
/// error (null state, unknown indicator).
/// The cloned state is independent: use with `<name>_batch()` and release
/// with `<name>_state_free()`.
///
/// # Safety
/// `state` must be null, or a valid pointer previously returned by an
/// indicator's `<name>_indicator()` function (or `tulip_state_deserialize`/
/// `tulip_state_clone`) that matches `indicator` and has not been passed to
/// `<name>_state_free()` yet.
#[no_mangle]
pub unsafe extern "C" fn tulip_state_clone(indicator: u32, state: *const c_void) -> *mut c_void {
    if state.is_null() {
        return std::ptr::null_mut();
    }
    let id = match CIndicatorId::try_from(indicator) {
        Ok(id) => id,
        Err(_) => return std::ptr::null_mut(),
    };
    clone_dispatch(id, state)
}

/// Private helper for `clone_dispatch` (generic over the concrete type).
unsafe fn clone_state<S: Clone>(state: *const c_void) -> *mut c_void {
    let s: &S = &*(state as *const S);
    Box::into_raw(Box::new(s.clone())) as *mut c_void
}

#[cfg(test)]
mod tests {
    use super::{
        tulip_state_clone, tulip_state_deserialize, tulip_state_serialize, CIndicatorId,
        CStateFormat, HEADER_LEN,
    };
    use crate::common::test::build_synthetic_data;
    use crate::common::tulip_ffi_bytes_free;
    use std::os::raw::c_void;

    /// MUST match build.rs's fnv1a32 exactly; pinned by the official FNV
    /// reference vectors below so drift is impossible.
    fn fnv1a32(name: &[u8]) -> u32 {
        let mut hash: u32 = 0x811c9dc5;
        for &b in name {
            hash ^= b as u32;
            hash = hash.wrapping_mul(0x01000193);
        }
        hash
    }

    #[test]
    fn test_fnv1a32_pinned_to_reference_vectors() {
        assert_eq!(fnv1a32(b""), 0x811c_9dc5);
        assert_eq!(fnv1a32(b"a"), 0xe40c_292c);
        assert_eq!(fnv1a32(b"foobar"), 0xbf9c_f968);
    }

    #[test]
    fn test_generated_ids_match_hash_of_name() {
        for &id in CIndicatorId::ALL {
            assert_eq!(
                id as u32,
                fnv1a32(id.name()),
                "discriminant for {:?} is not fnv1a32 of its name",
                id
            );
            // TryFrom round-trips for every generated id...
            assert_eq!(CIndicatorId::try_from(id as u32), Ok(id));
            // ...and the name lookup agrees with the identity.
            assert_eq!(CIndicatorId::from_name(id.name()), Some(id));
        }
        // A few values outside the (hash-shaped, hence non-contiguous) id
        // space must be rejected, including the old positional ids.
        assert!(CIndicatorId::try_from(0).is_err());
        assert!(CIndicatorId::try_from(999).is_err());
        assert!(CIndicatorId::try_from(u32::MAX).is_err());
    }

    fn adx_state() -> *mut c_void {
        unsafe {
            let data_len = 60usize;
            let high: Vec<f64> = build_synthetic_data(data_len, 2);
            let low: Vec<f64> = build_synthetic_data(data_len, 0);
            let close: Vec<f64> = build_synthetic_data(data_len, 1);
            let inputs_ptr: [*const f64; 3] = [high.as_ptr(), low.as_ptr(), close.as_ptr()];
            let options: [f64; 1] = [14.0];
            let result = crate::adx::adx_indicator(
                inputs_ptr.as_ptr(),
                data_len,
                options.as_ptr(),
                std::ptr::null(),
                0,
            );
            assert_eq!(result.error, crate::common::CIndicatorError::Ok);
            result.state
        }
    }

    /// Serialize `state`, deserialize the blob, run an identical batch on
    /// the original and restored handles, and assert bar-for-bar equality.
    fn roundtrip_batch_matches(id: u32, fmt: u32, state: *mut c_void, lanes: usize) {
        unsafe {
            let bytes = tulip_state_serialize(id, fmt, state);
            assert!(!bytes.ptr.is_null());
            assert!(bytes.len > HEADER_LEN);

            let restored = tulip_state_deserialize(bytes.ptr, bytes.len);
            assert!(!restored.is_null());

            let extra_len = 10usize;
            let a: Vec<Vec<f64>> = (0..lanes)
                .map(|k| build_synthetic_data(extra_len, k))
                .collect();
            let ptrs: Vec<*const f64> = a.iter().map(|v| v.as_ptr()).collect();
            let orig = crate::adx::adx_batch(state, ptrs.as_ptr(), extra_len, std::ptr::null(), 0);
            let rest =
                crate::adx::adx_batch(restored, ptrs.as_ptr(), extra_len, std::ptr::null(), 0);
            assert_eq!(orig.error, crate::common::CIndicatorError::Ok);
            assert_eq!(rest.error, crate::common::CIndicatorError::Ok);
            assert_eq!(orig.num_outputs, rest.num_outputs);

            let lens_o = std::slice::from_raw_parts(orig.output_lens, orig.num_outputs);
            let lens_r = std::slice::from_raw_parts(rest.output_lens, rest.num_outputs);
            assert_eq!(lens_o, lens_r);
            let rows_o = std::slice::from_raw_parts(orig.outputs, orig.num_outputs);
            let rows_r = std::slice::from_raw_parts(rest.outputs, rest.num_outputs);
            for i in 0..orig.num_outputs {
                let vo = std::slice::from_raw_parts(rows_o[i], lens_o[i]);
                let vr = std::slice::from_raw_parts(rows_r[i], lens_r[i]);
                for j in 0..vo.len() {
                    assert_eq!(vo[j].to_bits(), vr[j].to_bits());
                }
            }

            crate::common::tulip_ffi_batch_result_free(orig);
            crate::common::tulip_ffi_batch_result_free(rest);
            crate::adx::adx_state_free(restored);
            tulip_ffi_bytes_free(bytes);
        }
    }

    #[test]
    fn test_adx_state_roundtrip_bincode() {
        let state = adx_state();
        unsafe {
            roundtrip_batch_matches(
                CIndicatorId::Adx as u32,
                CStateFormat::Bincode as u32,
                state,
                3,
            );
            crate::adx::adx_state_free(state);
        }
    }

    #[test]
    fn test_adx_state_roundtrip_json() {
        let state = adx_state();
        unsafe {
            roundtrip_batch_matches(
                CIndicatorId::Adx as u32,
                CStateFormat::Json as u32,
                state,
                3,
            );
            crate::adx::adx_state_free(state);
        }
    }

    #[test]
    fn test_rsi_state_roundtrip_bincode() {
        // A second indicator proves the build.rs-generated registry scales
        // beyond the hand-wired adx path (single input series here).
        unsafe {
            let data_len = 60usize;
            let close: Vec<f64> = build_synthetic_data(data_len, 1);
            let inputs_ptr: [*const f64; 1] = [close.as_ptr()];
            let options: [f64; 1] = [14.0];
            let result = crate::rsi::rsi_indicator(
                inputs_ptr.as_ptr(),
                data_len,
                options.as_ptr(),
                std::ptr::null(),
                0,
            );
            assert_eq!(result.error, crate::common::CIndicatorError::Ok);
            let state = result.state;

            let bytes = tulip_state_serialize(
                CIndicatorId::Rsi as u32,
                CStateFormat::Bincode as u32,
                state,
            );
            assert!(!bytes.ptr.is_null());

            // Name in the header must be "rsi" -- blob knows its own type.
            let name = std::slice::from_raw_parts(bytes.ptr.add(6), 4);
            assert_eq!(&name[..3], b"rsi");

            let restored = tulip_state_deserialize(bytes.ptr, bytes.len);
            assert!(!restored.is_null());

            let extra_len = 10usize;
            let extra: Vec<f64> = build_synthetic_data(extra_len, 1);
            let eptr: [*const f64; 1] = [extra.as_ptr()];
            let a = crate::rsi::rsi_batch(state, eptr.as_ptr(), extra_len, std::ptr::null(), 0);
            let b = crate::rsi::rsi_batch(restored, eptr.as_ptr(), extra_len, std::ptr::null(), 0);
            assert_eq!(a.error, crate::common::CIndicatorError::Ok);
            assert_eq!(b.error, crate::common::CIndicatorError::Ok);
            let la = std::slice::from_raw_parts(a.output_lens, a.num_outputs);
            let lb = std::slice::from_raw_parts(b.output_lens, b.num_outputs);
            assert_eq!(la, lb);
            let va = std::slice::from_raw_parts(*a.outputs, la[0]);
            let vb = std::slice::from_raw_parts(*b.outputs, lb[0]);
            for i in 0..va.len() {
                assert_eq!(va[i].to_bits(), vb[i].to_bits());
            }

            crate::common::tulip_ffi_batch_result_free(a);
            crate::common::tulip_ffi_batch_result_free(b);
            crate::rsi::rsi_state_free(state);
            crate::rsi::rsi_state_free(restored);
            tulip_ffi_bytes_free(bytes);
        }
    }

    #[test]
    fn test_state_serialize_errors() {
        unsafe {
            // Null state ptr -> null CBytes
            let bytes = tulip_state_serialize(
                CIndicatorId::Adx as u32,
                CStateFormat::Bincode as u32,
                std::ptr::null(),
            );
            assert!(bytes.ptr.is_null());

            let state = adx_state();

            // Unknown indicator id -> null CBytes
            let bytes = tulip_state_serialize(999, CStateFormat::Bincode as u32, state);
            assert!(bytes.ptr.is_null());

            // Valid id but wrong format (7) -> null CBytes
            let bytes = tulip_state_serialize(CIndicatorId::Adx as u32, 7, state);
            assert!(bytes.ptr.is_null());

            // A hash-shaped id of some OTHER indicator is "valid" for
            // serialize, but must not type-pun an adx state: it would
            // reinterpret the box. Guard: this call with Rsi's id on an
            // Adx state is UB per # Safety (caller error), so we only
            // assert unknown ids error out. (Deserialize cannot make this
            // mistake: the blob's own name wins.)
            crate::adx::adx_state_free(state);
        }
    }

    #[test]
    fn test_state_deserialize_misuse() {
        unsafe {
            let state = adx_state();
            let bytes = tulip_state_serialize(
                CIndicatorId::Adx as u32,
                CStateFormat::Bincode as u32,
                state,
            );
            assert!(!bytes.ptr.is_null());
            let blob = std::slice::from_raw_parts(bytes.ptr, bytes.len).to_vec();

            // Truncated below header length
            assert!(tulip_state_deserialize(blob.as_ptr(), HEADER_LEN - 1).is_null());
            // Header only, empty payload: decodes nothing -> null
            assert!(tulip_state_deserialize(blob.as_ptr(), HEADER_LEN).is_null());

            // Corrupted magic
            let mut bad = blob.clone();
            bad[0] = b'X';
            assert!(tulip_state_deserialize(bad.as_ptr(), bad.len()).is_null());

            // Unknown schema version (the retired v1 layout must be rejected)
            let mut bad = blob.clone();
            bad[4] = 1;
            assert!(tulip_state_deserialize(bad.as_ptr(), bad.len()).is_null());

            // Unknown format byte
            let mut bad = blob.clone();
            bad[5] = 7;
            assert!(tulip_state_deserialize(bad.as_ptr(), bad.len()).is_null());

            // Unknown/corrupted indicator name
            let mut bad = blob.clone();
            bad[6] = b'q';
            assert!(tulip_state_deserialize(bad.as_ptr(), bad.len()).is_null());

            // Name field with trailing junk after the NUL padding is not a
            // name match (only the exact unpadded name is).
            let mut bad = blob.clone();
            bad[9] = b'x'; // "adx\0..." -> "adx\0x"
            assert!(tulip_state_deserialize(bad.as_ptr(), bad.len()).is_null());

            // Structurally invalid payload: too short to decode (note:
            // random byte flips are NOT rejected -- this state is pure
            // f64/usize aggregates, and any bit pattern is a valid f64).
            let mut bad = blob.clone();
            bad.truncate(HEADER_LEN + 1);
            assert!(tulip_state_deserialize(bad.as_ptr(), bad.len()).is_null());

            crate::adx::adx_state_free(state);
            tulip_ffi_bytes_free(bytes);
        }
    }

    #[test]
    fn test_deserialized_state_survives_state_free_contract() {
        unsafe {
            let state = adx_state();
            let bytes = tulip_state_serialize(
                CIndicatorId::Adx as u32,
                CStateFormat::Bincode as u32,
                state,
            );
            let restored = tulip_state_deserialize(bytes.ptr, bytes.len);
            assert!(!restored.is_null());
            crate::adx::adx_state_free(restored);
            crate::adx::adx_state_free(state);
            tulip_ffi_bytes_free(bytes);
        }
    }

    #[test]
    fn test_adx_state_clone_roundtrip() {
        unsafe {
            let state = adx_state();
            let cloned = tulip_state_clone(CIndicatorId::Adx as u32, state);
            assert!(!cloned.is_null());

            let extra_len = 10usize;
            let a: Vec<Vec<f64>> = (0..3).map(|k| build_synthetic_data(extra_len, k)).collect();
            let ptrs: Vec<*const f64> = a.iter().map(|v| v.as_ptr()).collect();
            let ba = crate::adx::adx_batch(state, ptrs.as_ptr(), extra_len, std::ptr::null(), 0);
            let bb = crate::adx::adx_batch(cloned, ptrs.as_ptr(), extra_len, std::ptr::null(), 0);
            assert_eq!(ba.error, crate::common::CIndicatorError::Ok);
            assert_eq!(bb.error, crate::common::CIndicatorError::Ok);
            let la = std::slice::from_raw_parts(ba.output_lens, ba.num_outputs);
            let lb = std::slice::from_raw_parts(bb.output_lens, bb.num_outputs);
            assert_eq!(la, lb);
            let va = std::slice::from_raw_parts(*ba.outputs, la[0]);
            let vb = std::slice::from_raw_parts(*bb.outputs, lb[0]);
            for i in 0..va.len() {
                assert_eq!(va[i].to_bits(), vb[i].to_bits());
            }

            // Null / unknown-id error paths
            assert!(tulip_state_clone(CIndicatorId::Adx as u32, std::ptr::null()).is_null());
            assert!(tulip_state_clone(999, state).is_null());

            crate::common::tulip_ffi_batch_result_free(ba);
            crate::common::tulip_ffi_batch_result_free(bb);
            crate::adx::adx_state_free(state);
            crate::adx::adx_state_free(cloned);
        }
    }
}
